### ISSUE TITLE
Some useful features

### ISSUE THREAD

**Issue by datvq** [DaxStudio/DaxStudio#1006]
Can you add some features:

* Move lines of code with Alt + Up/Down.
* Keep the same layout after pinning tab to the right panel (save setting)
* Load text files (.dax) when opened with Dax Studio
* Auto connect last connection when open file .dax or new query
* User custom dax snippets.

Thanks for read.

**Comment by dgosbell** [comment]
Thanks for logging these. I really do appreciate people suggest new features. But I might actually close this issue since most of these items have either already been asked for in existing issues or they already exist. And it's also hard to track a single issue with multiple requests. If you want you can subscribe to notifications on the existing requests.

Do let me know if you think I've misunderstood any of your bullet points. 

> Move lines of code with Alt + Up/Down.

You can already do this with  Ctrl + +/-   but I'm not sure if I can alter these hot keys. Some of the edit actions are built in to the edit control and cannot be overridden easily.

> Keep the same layout after pinning tab to the right panel (save setting)

This is already logged as issue #974 but as noted there I'm having some issues with the docking framework that I have not been able to figure out yet.

> Load text files (.dax) when opened with Dax Studio

This should already work. If you use the installers it will add a file association for .dax files and double-clicking on a .dax file will open it in DAX Studio. The portable version will not do this as it requires making changes to the registry and the portable version does not do that.

> Auto connect last connection when open file .dax or new query

I'm not sure about this one. It will save one click. But some connections like Power BI XMLA and AzureAS can take 20-30 seconds to connect and if that is not what you wanted that would waste a lot of time. And for Power BI Desktop I can't guarantee that the same files will be open the next time you open DAX Studio and I have no way of knowing where the files are stored. We only get a connection to the model loaded into memory, not a link to the .pbix file. So there is no way to trigger the opening of a file if it is not already open.

However I have an idea for slight variation on this feature which might be an answer for this and other use cases, but I'm still prototyping some ideas here.

> User custom dax snippets.

This has been logged before here #447 but my DAX usually varies from model to model so I have not seen much use for this myself so it's not high on my priority list. To be honest I have a lot of other features I'd like to add before looking into this.

**Comment by datvq** [comment]
Thanks for reponse soon like that. 
* first, I tried again, right, Ctrl + =/- work well, strange for me but will soon become a habit.
* third, Load text files (.dax), sorry because I use English not good. I mean here DAX Studio can open .dax file, but is'nt load content of it. It's empty like create new from DAX Studio. Thanks.

**Comment by dgosbell** [comment]
> third, Load text files (.dax), sorry because I use English not good. I mean here DAX Studio can open .dax file, but is'nt load content of it. It's empty like create new from DAX Studio. Thanks.

I'm not sure what might cause this. I open .dax file in DAX Studio all the time. 

When you open these files in notepad can you see the content?

If so can you upload an example file which does not load the content to this issue so that I see if it's maybe something to do with the specific file?

**Comment by datvq** [comment]
![open_with_dax_studio](https://user-images.githubusercontent.com/13284830/206939919-1dcd1770-843f-46a8-a51c-7bd7566a044f.png)

Yes, I mean load content by open text file by double click (or open with) dax file, not open by Ctrl + O in dax studio.

**Comment by dgosbell** [comment]
Are there any errors in the Log pane?

Are you able to upload an example .dax file from your machine?

This is what I see when I do the same as you
![image](https://user-images.githubusercontent.com/8241830/206955872-1137f994-d388-4f01-97ba-9b0ca8897a35.png)

**Comment by datvq** [comment]
Thanks for your response, I will research and test more, and also feedback soon about this topic in the future.
