### ISSUE TITLE
Tracing doesn't work on Azure Analysis Services

### ISSUE THREAD

**Issue by o-o00o-o** [DaxStudio/DaxStudio#101]
Hi guys, we are moving our Cube to AAS from a VM based SSAS and are finding problems with the Trace features of DaxStudio

All Queries does seem to work fine
Server Timings and Query Plan both get an error "Trace Stopped: QueryEnd event not received - Tracing timout exceeded"

![image](https://user-images.githubusercontent.com/13693159/46365300-1e318a00-c670-11e8-9368-1d831d8b2b5a.png)

In order to run this I have to do a RunAs of DaxStudio as an admin account (as I need admin permissions to start the trace). I don't think that is causing any problems and this works fine with other applications but thought I would mention it.

Is there anything that I can do to make this work or is this a known limitation of AAS and DaxStudio right now?

**Comment by marcosqlbi** [comment]
I've never seen that issue and usually I'm not running as a local admin of the machine - but my user is a SSAS Admin, of course. Are you saying that you need a local admin account to run the trace on Azure Analysis Services?

**Comment by o-o00o-o** [comment]
It happens to be a local admin as well as the AAS admin but that isn't the problem. I have to runas so that I can authenticate with the cube with the correct user (not because I need local admin privs) . It works fine on a Ssas on VM but not on AAS. I do see a flash of the information on the tab but then this disappears when I get the yellow warning. It is totally consistent. Are you saying you have tried on an Azure Analysis Services cube and you dont get this behaviour? I don't believe this is anything special we have just spun up an AAS instance and deployed our cube.

**Comment by marcosqlbi** [comment]
Maybe you just need updated OLEDB drivers for Analysis Services?

**Comment by dgosbell** [comment]
@o-o00o-o I don't see this consistently, but I have seen it sporadically. 

Trace Events in SSAS are not 100% guaranteed to be delivered. Usually it would only be if the server was under massive load that it would drop trace events. But it's also possible that another admin could have killed the trace or there was some other networking issue. 

So for both server timings and query plans we start a timer once the results of the query have been received so that you don't potentially get stuck waiting forever for a QueryEnd event that does not arrive. I think in v2.7 this was set as something like 5-10 seconds which is fine for on-premises SSAS, but it appears that sometimes AAS can take longer than this. 

I was just running some tests and had no issues for the first 10 or so queries, then all of a sudden I got no trace events coming through at all from AAS for about 30 seconds, (which caused DAX Studio to timeout) then a whole bunch of events came through at once like something in Azure had caused them to be buffered.

In v2.8 we are adding some settings in the option screen to let you increase the timeouts, but we may also look at some AAS specific enhancements for later versions. (I'd prefer that these features just worked, rather than failing and people having to find the settings and change them manually)

**Comment by dgosbell** [comment]
It appears that sometimes the trace on AAS takes a while to start up. v2.8.0 which was just released exposes the Trace Startup Timeout as an option.
![image](https://user-images.githubusercontent.com/8241830/51500848-b623d100-1e23-11e9-8637-026bd76a4c84.png)
Can you try increasing the timeout to 20-30 seconds and see if this helps?
I've still noticed some strange behaviours when trace AAS. If you leaving the trace running for too long it appears to get disconnected or something. It's difficult to isolate these types of issues, I think it could be upstream of DAX Studio (ie. in the provider, the network or Azure) but it's hard to reproduce.

**Comment by dgosbell** [comment]
closing due to lack of response. Please feel free to open a new issue if this is still a problem under v2.8.1 or later
