### ISSUE TITLE
Result pane moves columns out of the view.

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#1038]
When previewing the results in the Results pane if the tables has many columns and you scroll to the far right and then start scrolling down the last few columns move out of the view and since the new columns are added towards end it become difficult while demonstrating the feature to new user.

**Comment by dgosbell** [comment]
Unfortunately this behaviour is "by design" as it is a built-in behaviour of the datagrid. 

The results grid is designed to be able to handle very large resultsets and it does this using a technique called virtualization. What this means is that the grid does not render all of the rows, it renders a few hundred rows initially, then as you scroll it releases earlier rows from memory and pages in new ones. This is very memory efficient, and it allows the grid to display results much faster than if it rendered the entire resultset up-front. The only downside to this is that there is no way for the grid to know how wide to make each of the columns until you have scrolled right to the bottom. The behaviour you are seeing is the grid re-sizing some of the columns as new data is paged in that is wider than the values previously seen.
