### ISSUE TITLE
Excel Add-in only in Admin Mode

### ISSUE THREAD

**Issue by domtrump** [DaxStudio/DaxStudio#107]
Running DAX Studio 2.7.4. I recently install the Excel Add-in KuTools. After doing so, the DAX Studio add-in no longer loads. IF I Run Excel As Administrator, DAX Studio loads. (I have several other proprietary add-ins as well and all need to be running). Is there something I can do so that DAX Studio loads without Running As Administrator? Right now, I am using two icons - one to launch Excel only when I need DAX Studio. Thanks.

**Comment by dgosbell** [comment]
If DAX Studio was working, then you installed KuTools and it stopped working then this sounds like some conflict between the two addins rather than a specific issue with DAX Studio. We do not have anything that requires Admin rights, it's possible that there is some side effect of running as admin which alters the order in which the addins load. If you disable KuTools does the DAX Studio add-in start working again?

**Comment by domtrump** [comment]
On first try, no, it did not start working. But then I disabled ALL addins and started putting them back one by one (starting with DAX Studio) and, for the moment, they are all running together without starting as Admin. We'll see what happens next time I reboot. Thanks.

-Dom
________________________________

**Comment by dgosbell** [comment]
Closing this issue as I'm assuming that no news is good news :)
