### ISSUE TITLE
Output to Excel Does not work by default

### ISSUE THREAD

**Issue by coder-koob** [DaxStudio/DaxStudio#108]
The data connection to power bi was not working, had to change the default provider that gets generated from Provider=MSOLAP.5 to Provider=MSOLAP.8.

**Comment by dgosbell** [comment]
So I'm guessing that you are talking about using the "Linked Excel" output against Power BI Desktop? 

The primary use case that we designed the linked Excel output for was so that users (primarily of PowerPivot) could create a table that could be refreshed at a later date or even on a different pc that may not have had the DAX Studio Addin installed. 

If it was just an issue of changing the MSOLAP version it would be relatively simple, but because Power BI randomizes it's port on startup the problem is actually more complicated. This change of port will effectively break the link between the workbook and Power BI. There are no hooks we can use in Excel to fix or update this connection so I'm actually thinking that maybe we should disable the linked Excel output when connected to Power BI (or SSDT) and only allow the static output.

Apart from the table formatting that gets automatically applied to the linked Excel output I don't believe there should be any significant differences in the data output between the linked and static options.

**Comment by dgosbell** [comment]
I'm assuming by the lack of response that you were trying to use the Linked Excel output, so I'm going to close this issue as we are planning to disable this option in future unless DAX Studio is connected to a PowerPivot model.
