### ISSUE TITLE
VSCode extension?

### ISSUE THREAD

**Issue by Kurren123** [DaxStudio/DaxStudio#1086]
VSCode is a great code editor. Have we thought about making a DAX extension for it? It could use the DAX Studio internals under the hood. I understand that this is a massive project but it could be simpler to eventually just migrate the whole of dax studio into a VSCode extension, as there will be far less UI to develop and support.

**Comment by marcosqlbi** [comment]
May I ask what are the features you use more often with DAX Studio? 
I would like to understand the use case for a VSCode integration.

**Comment by dgosbell** [comment]
This would be a massive re-write. What sort of end user benefits would you see this having?

**Comment by Kurren123** [comment]
I don't think bravo provides what DAX studio does. In DAX studio, you can connect to a power bi/SSDT model and start writing and executing DAX queries. This is [exactly what you do](https://learn.microsoft.com/en-us/sql/tools/visual-studio-code/sql-server-develop-use-vscode?view=sql-server-ver16) in VScode when writing and executing SQL: new file > connect > write your query with intellisense and auto formatting > execute (results show up in a new tab). It is this reason why VSCode is a great fit for superseding DAX studio.

**Comment by marcosqlbi** [comment]
What I'm saying is that the Bravo Template Editor (not Bravo) already has 95% of the features you need, and it's a better starting point for a VS Code extension because it's already in TypeScript, it has already the connection to PBI Desktop and uses Bravo as a bridge (as you cannot connect TypeScript to PBI Desktop directly because there are no client libraries for that).
Connecting to AAS / PBI Service through XMLA endpoint is technically possible but hard to implement. There is not much code you would use from DAX Studio in such an extension, whereas most of the code is already there (even though you don't see the feature you want now).
Who wants to do that is another story :) but I'm just to find the faster way to implement what you are asking!

**Comment by Kurren123** [comment]
Apologies for the misunderstanding. I wasn't aware of the bravo template editor but yes that seems like a better starting point.

**Comment by marcosqlbi** [comment]
Good. Now some volunteers need to write the code: they should know TypeScript (which is not my cup of tea).
SQLBI has sponsored the existing code for Bravo for Power BI, paying for the development of the TypeScript development.
