### ISSUE TITLE
Closing Dax Studio while exporting Metrics destroys SSAS installation

### ISSUE THREAD

**Issue by JJDatawise** [DaxStudio/DaxStudio#1142]
DAX Studio Version 2.17.3

During exporting Metrics from SSAS 2017 I closed DAX Studio because I wasn't aware that the export was still running. This destroyed the SSAS installation because some files (.dictionary) were missing.

Users were not able to query the database. I wasn't able to re-deploy or even delete the database. The error message was always the same, see screenshot.

We fixed the issue by changing the data directory in SSAS and re-deployed the model. There would probably be a smoother solution. 

Steps to reproduce the behavior (not tried it again):
1. Click "Export Metrics"
2. Close DAX Studio while metrics are still exported

![DS Error](https://github.com/DaxStudio/DaxStudio/assets/83476664/f306a4ad-6482-4241-bcd9-471d3568ac86)

**Comment by marcosqlbi** [comment]
DAX Studio does not directly access any of those files. DAX Studio connects to Analysis Services, which owns those files exclusively. Even though you close a client process unexpectedly (DAX Studio, Excel, Power BI, ...), it's still Analysis Services that manages those files, and a loss of any of those files (regardless of the client action) would be an Analysis Services bug that should be reported to Microsoft support.
Because you use a relatively old SSAS version (2017), are you sure you installed all the latest fixes and updates? The last one was released on February 14, 2023 (CU31).

**Comment by JJDatawise** [comment]
Dear Marco

Thank you for your quick response and the detailed explanation.

DAX Studio is a indispensable tool, thanks a lot for your great work!

**Comment by JJDatawise** [comment]
Dear Marco

Thank you for your quick response and the detailed explanation.

DAX Studio is a indispensable tool, thanks a lot for your great work!

**Comment by dgosbell** [comment]
Like Marco has said we only issue queries, we don't make any changes to the model and we definitely do not have any access to the file system on the SSAS server. So I'm going to close this as it's either a hardware issue on your server or a SSAS bug.
