### ISSUE TITLE
cRASH MANY TIMES

### ISSUE THREAD

**Issue by limber-git** [DaxStudio/DaxStudio#1150]
DAX Studio v3.0.8.945
Connection: PowerBIDesktop - 16.0.87.16

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
I'll need a lot more information to help identify this issue since it is not something that happens to me.

Does the crash reporting window pop up when this happens?
If so, what does the error message say and have you sent in the crash report?
Can you upload the latest log file from %LOCALAPPDATA%\DaxStudio\log ?

What are you doing when the crash happens?
* Does it happen on start up?
* Or when you connect?
* Or when you run a query?
* Or when you use a particular function?

**Comment by dgosbell** [comment]
closing due to lack of response, feel free to re-open if you have more information to share
