### ISSUE TITLE
Add code folding

### ISSUE THREAD

**Issue by TecnologiaCusezar** [DaxStudio/DaxStudio#1164]
Hello,

It would be great if you could add code folding to Dax Studio as it allows working with heavily indented measures.

Greetings from Colombia

**Comment by dgosbell** [comment]
I just released a preview feature that enables code folding see https://daxstudio.org/docs/features/indent-code-folding/

It uses indenting to figure out the folding rather than logical blocks of code because I do not have a full DAX parser, but it seems to be working pretty well if your code is formatted using the Format DAX button.
