### ISSUE TITLE
Timeout Problem

### ISSUE THREAD

**Issue by Stefanoeid** [DaxStudio/DaxStudio#1173]
**Timeout Error.**
Lately i'm encountering problems with timeouts when evaluating a long query. Usually all I had to do was change the timeout timer in the advanced options under the connection setting using ";Timeout=36000;" or set another timeout timer that was fit to finish the query. But lately it's not actually changing the timeout timer, since I still got the error after 3600 seconds passes (1 hour).

I'd love to know if there's another way to fix or surpass this error, as I don't find slicing the database really amusing.

Below or attached is 1 screenshot showing the error that I'm facing.

P.S.: Lowering the timeout timer works, as you can also see in the screenshot when i've tried changing it to 50 seconds, but increasing it is not working.

https://imageupload.io/pEVNmGCM2BzhtP9

**Comment by dgosbell** [comment]
This is not a DAX Studio error. It is coming from the server which has a default upper limit for the timeout of 3600 seconds. If this is Analysis Services you could possibly talk to your server admin about increasing the limit. If it is Power BI you probably have to look to simplify your query or filter it somehow so that it runs in less time. If you are trying to export a lot of data you may even be better not to use a DAX query and to try and go back to the original source data.
