### ISSUE TITLE
Timeout error when trying to export data from dax studio to SQL server.

### ISSUE THREAD

**Issue by vnavashree** [DaxStudio/DaxStudio#1175]
![image](https://github.com/DaxStudio/DaxStudio/assets/143633791/2c3b375a-576d-40cc-b645-8474d7d88e28)

The error I'm getting is "Error exporting data to SQL server Table: The wait operation timed out"

**Comment by dgosbell** [comment]
This is an error coming from SQL Server. You'll need to talk to your DBA to see if they can help you figure out why SQL Server is throwing this error

**Comment by nachazel** [comment]
I have the same problem described above and our SQL admin swears this is nothing in SQL server that can be configured that would generate these errors on the database side. I read elsewhere that setting a timeout to 0 bypasses the timeout period, but I don't know where to set that. My SQL exports fail often even with a ;Timeout=0 or ;Timeout=5000 at the end of the SQL connection string, so that must not be the right place. Does anyone know where specifically in SQL Server a setting can be changed so that my exports don't drop in the middle of transfers after like 15 seconds?

**Comment by dgosbell** [comment]
So the error about a "wait timeout" is typically due to a connection timeout (see https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/performance/troubleshoot-query-timeouts#query-time-out-is-not-the-same-as-connection-time-out ) particularly if you are seeing this after 15 seconds as the default connection timeout is 15 seconds. This usually indicates an overloaded SQL instance or possibly issues with slow authentication to AD. 

The `timeout=` parameter only sets the command timeout. To extend the connection timeout you would need to add `;Connect Timeout=60` to the connection string if you wanted to extend this to 60 seconds.

**Comment by nachazel** [comment]
Hi Darren:

Just following up to let you know that I have not had any problems since I stopped multi-tasking. I'm not using any connection strings, and the exports to SQL Server all complete successfully if I don't try to do anything with the dataset while it's working. In my case I have one dataset with a dozen dataflows loaded into it that I want to export to SQL Server. A few of the dataflows aren't ready by the time I start exporting data, so I have to run the process several times. Everything works as long as I don't try to refresh new data into the model while exporting data from it, even if they are different tables. I was not expecting that behavior, but it's a repeatable process and easy enough to work around. With that in mind, I don't have the problem anymore.

Thanks again,

David

**Comment by dgosbell** [comment]
> Everything works as long as I don't try to refresh new data into the model while exporting data from it, even if they are different tables

This actually makes a lot of senses. When a table finishes refreshing it has to perform a database level commit and this requires exclusive access to the database. So running any refresh while also exporting is likely to cause issues.
