### ISSUE TITLE
Trace Stopped: QueryEnd event not received - End Event Timeout exceeded.

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#1179]
If you switch on Query Plan and Server Timings and then run any query 26 times then DAX Studio disconnects from server and throws this error:
![image](https://github.com/DaxStudio/DaxStudio/assets/73054674/750ed447-fa5d-4efb-8c10-2530e0ceddb0)
Query: EVALUATE { COUNTROWS ( Sales ) }

Live Example:

https://github.com/DaxStudio/DaxStudio/assets/73054674/c23a04d9-3ceb-48d2-a19c-50c7a3ec1620

**Comment by dgosbell** [comment]
Is there a need to do this sort of thing? I suspect there is possibly and overlap of some of the start and end events being captured by the server timings. I could possibly disable the run button while a trace is waiting, but I don't normally start a new query until I've seen the trace results from the previous one, so I'm not sure that the value is in doing this.

**Comment by SharmaAntriksh** [comment]
The error was appearing frequently when DAX Studio has been running for a long time, so I decided to investigate the reason and found that running the same query many times throws this error. I opened this as it could appear due to many other reason at least there is now one example of why.

I have seen this issue even when using DS realistically 1 run per 5 minute or something while optimizing.

**Comment by dgosbell** [comment]
Ok so even though the error is the same I can pretty much guarantee that the cause is completely different and fixing the rapid execution of the same query 20+ times will not fix the long running session issue. The cause if this when running for a long time is likely to be due to issues with the underlying sessions. The difficulty here is reproducing the issue in order to debug it and test any fixes. 

Are you running DAX Studio against the Power BI service? I don't see this sort of error very often myself, but I tend to prefer performance tuning against a desktop model if I can.

If you are seeing this frequently can you try changing the logging to **Debug** in File > Options and then after you see this error attaching the relevant log file to this issue. (see here for the location of the [logging folder](https://daxstudio.org/docs/troubleshooting/logging-settings/#log-folder-location) )

**Comment by SharmaAntriksh** [comment]
@dgosbell Sure, will do that. Also, I faced the issue when connected with SSAS Tabular, but not too sure as I have 2 different session open 1 with PBI Desktop as well.

**Comment by SharmaAntriksh** [comment]
This is happening more frequently now, even in around 4-5 executions the trace stops. I have to disable both Query Plan and Server Timing for DS to connect again otherwise it doesn't.

This image is from today: It threw error in just 7 minutes
![image](https://github.com/DaxStudio/DaxStudio/assets/73054674/d4b47e92-9159-4ef9-836d-c8c704670ce9)

This one is from yesterday:
![image](https://github.com/DaxStudio/DaxStudio/assets/73054674/dd3dc74a-4840-4c14-a8b6-30e9af58692e)

Log file from today:
[DaxStudio-20240131.log](https://github.com/DaxStudio/DaxStudio/files/14111111/DaxStudio-20240131.log)

**Comment by dgosbell** [comment]
Ok, so something happend on the server/data model side of things that killed the initial connection. The query window automatically reconnected, but the 2 traces did not. I believe this is why they never received the QueryEnd event. I should be able to cascade the reconnect event to any running traces to fix this.
