### ISSUE TITLE
Problem with Dates Between when using Parameters

### ISSUE THREAD

**Issue by Kealkil4** [DaxStudio/DaxStudio#1180]
DAX Studio v3.0.10.962
Connection: PowerBIDesktop - 16.0.96.20

## Summary of Issue
Connected to Power BI Service data source.
Want to have variable start and end dates.
DAX Studio will not prompt for the @startdate which in turn leads to "@startdate  parameter not declared" error when you run the query.
![Dax Studio Problem](https://github.com/DaxStudio/DaxStudio/assets/32125650/3cfd5965-aa20-41c9-9bfe-7ec35ca64276)

  

## Steps to Reproduce
1.Generate a Query and enter explicit startdate and enddate  in the query
2. Run Query
3. Replace explicit startdate with VALUE(@startdate)  ... VALUE required to avoid string vs date comparison error
4. Replace explicit enddate with VALUE(@enddate)
5. Run Query
6. There is no prompt appearing for @startdate parameter

**Comment by dgosbell** [comment]
Thanks for logging this. I have a fix checked in which will go out in the next release and at that point this issue will automatically close. 

As a temporary work around if you split the line so that each parameter is on its own line it should work

eg.

KEEPFILTERS( FILTER( ALL( Dates[Date] ),
Dates[Date] >= VALUE( @Start_Date) &&
Dates[Date] <= (@End_Date ) )),
