### ISSUE TITLE
CPU Time information in All Queries trace

### ISSUE THREAD

**Issue by renanalmeidjr** [DaxStudio/DaxStudio#1208]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great to have the CPU time column and not only Duration to be able to identify the most consuming CPU queries.

**Describe alternatives you've considered**
For SSAS: Extended Events, for PBI Premium I think there's no alternatives

**Additional context**

**Comment by marcosqlbi** [comment]
It's impossible because All Queries captures an event that only provides the duration. Computing the CPU time requires collecting many more events (actually, too many...), which would increase the traffic, slow down the service, and produce a performance issue to the server's overall performance.
When you activate the Server Timings for a single query, you capture the events for a single request, limiting the additional workload required on the server. While it would be technically possible to collect all the events from a server, it's really a bad idea and something we discourage.
