### ISSUE TITLE
Formatting a measure output negates a retrieval of a filter for ",Not(ISBLANK( {measure with missing values} ))}"

### ISSUE THREAD

**Issue by DocVD** [DaxStudio/DaxStudio#1255]
DAX Studio v3.0.11.982
Connection: AzureAnalysisServices - 16.0.128.22

## Summary of Issue
When a filter is applied to three columns, one is a measure, the other two are summarized columns with keepfilters(treatas( {list of values} the FORMAT statement on the MEASURE is ignored.

## Steps to Reproduce
1. DAX
    Evaluate
         SummarizeCoulmns
              ( 'Table-1'[Field-A]
              , 'Table-2'[Field-B]
              ,  KEEPFILTERS( TREATAS( {"ListItem-1", "ListItem-2", "ListItem-3", table-1'[Field-A]
              ,  KEEPFILTERS( TREATAS( {"ListItem-1", "ListItem-2", "ListItem-3", table-2'[Field-A]
              ,  "MeasureName", [Measure], FORMAT([Measure], "0.00000")
              )
2. Modify the DAX to exclude blank measure values.
    Evaluate
         FILTER(
                      SummarizeCoulmns
                           ( 'Table-1'[Field-A]
                           , 'Table-2'[Field-B]
                           ,  KEEPFILTERS( TREATAS( {"ListItem-1", "ListItem-2", "ListItem-3", table-1'[Field-A]
                           ,  KEEPFILTERS( TREATAS( {"ListItem-1", "ListItem-2", "ListItem-3", table-2'[Field-A]
                           ,  "MeasureName", [Measure], FORMAT([Measure], "0.00000")
                           )
                   , NOT( ISBLANK( [Measure] ))
                   )
RESULT: The list is NOT filtered by NON-BLANKS. If the "FORMAT" statement is removed, the BLANKS are removed.

**Comment by dgosbell** [comment]
I don't think this is a DAX Studio specific issue. It looks like a generic DAX question and you may get a faster response from the DAX community forum where there are more DAX experts online https://community.fabric.microsoft.com/t5/DAX-Commands-and-Tips/bd-p/DAXCommands 

But it looks like you've edited your example queries since the syntax is not valid. SummarizeColumns is misspelt and the number of parameters is incorrect. Depending on how you've aliased the formatted measure you might actually be filtering on the formatted result vs using the underlying measure. We'd really need to see an actual syntactically valid query to provide an answer. 

Note that SummarizeColumns will normally remove any rows with blanks in the expression, BUT the documentation for the FORMAT function clearly states that blanks are converted to empty strings, so an alternative could be to use IF( NOT( ISBLANK( [Measure],  FORMAT([Measure], "0.00000") ) inside your SUMMARIZECOLUMNS
