### ISSUE TITLE
Error message DaxStudio.vsto not valid Office Add-in

### ISSUE THREAD

**Issue by CBLansdellJr** [DaxStudio/DaxStudio#1269]
**Describe the bug**
I am trying to install the DAX Studio Excel add-in to the Office 365 version of Excel on a Windows 10 machine. I am stopped by an error message that DAXStudio.vsto is not a valid Office Add-in.

**To Reproduce**
When I open Developer - COM Add-ins from the ribbon, I see "DAX Studio Excel Add-in" checked in Adds-ins available.

When I press the Add button in the COM Add-ins dialog box, then navigate to C:\Program Files\DAX Studio\bin\DaxStudio.vsto and then press Enter. I get an Error message box that says: 'C:\Program Files\DAX Studio\bin\DaxStudio.vsto' is not a valid Office Add-in.

Note: I did a Full Install  of DAX Studio 3.0.11 with the Excel Addin checked. No previous version was in place. I did not touch the DAXStudio.vsto file after installation. I am able to open the DAX Studio GUI, That is good, but what I need is to connect to an Excel Power Pivot model, which I can only do through the add-in.

**Expected behavior**
I expect the DAX Studio Excel Add-in to be installed and function properly. We have successfully used the Hitachi TRMTracker FARRMS add-in, which is also a VSTO add-in.

**Screenshots**
![image](https://github.com/DaxStudio/DaxStudio/assets/174155471/6982beda-bf29-4a63-b0c6-10ca5a9d0ff2)

![image](https://github.com/DaxStudio/DaxStudio/assets/174155471/e3ab77e9-fc1a-44b3-81e7-21b7a78e840c)

![image](https://github.com/DaxStudio/DaxStudio/assets/174155471/d54e312d-e7eb-4605-81d4-e2c4f4d67705)

**Additional context**
Data per DAX Studio Checker

    Version =  v3.0.11.982
    DaxStudio.exe Version =  v3.0.11.982

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSRelease       = 2009
    OSVersion       = 10.0.19045
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 31.78
    FreeMemoryGB    = 22.19

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
Display: \\.\DISPLAY4  
         X: -2400 Y: 0 Width: 2400 Height: 1350
Display: \\.\DISPLAY5  
         X: 2400 Y: 0 Width: 2400 Height: 1350
DPI X: 120 Y: 120 (Scaling: 125.0%)

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v2.0.50727\1033 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1033 -> 3.5.30729.4926
    v4\Client -> 4.8.04084
    v4\Client\1033 -> 4.8.04084
    v4\Full -> 4.8.04084
    v4\Full\1033 -> 4.8.04084
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 528372 (4.8)
    PASS > .Net Version 4.8 is above the required minimum

DAX Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 21
    AMO : <default>
    ADOMD : <default>

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
	HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\excel.exe
    Excel Architecture: x64

    DAX Studio Excel Add-in Registry keys
       Description: DAX Studio Excel Add-In
       FriendlyName: DAX Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=3.0.11.982, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60910
        Install 1
        InstallerPath c:\Program Files\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1

Registry Settings
=======================
    CurrentDownloadVersion = 3.0.11.982
    LastVersionCheckUTC = 2024-06-28T18:28:12Z
    WindowPosition = ﻿<?xml version="1.0" encoding="utf-8"?><WINDOWPLACEMENT xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><length>44</length><flags>0</flags><showCmd>1</showCmd><minPosition><X>-1</X><Y>-1</Y></minPosition><maxPosition><X>-1</X><Y>-1</Y></maxPosition><normalPosition><Left>160</Left><Top>6</Top><Right>1560</Right><Bottom>906</Bottom></normalPosition></WINDOWPLACEMENT>

**Comment by dgosbell** [comment]
The error from Excel is misleading. There are 2 types of VSTO addins - ones that need to be installed via an installer and those that support click once manifests. Only click once addins can be installed using the add button in the dialog. DAX Studio needs to be installed using the installer as it requires extra functionality which is not available to click once addins. 

The fact that you can see it installed and ticked means the installer has worked.

The DAX Studio button should be on the Add-ins ribbon tab. There are a couple of common reasons why you might not be able to see this button.

1. Some other addin is loading an older version of .net - try disabling all addins except DAX Studio and Power Pivot, restart Excel and see if this "fixes" the issue.
2. The Add-ins tab has been renamed - some poorly behaving add-ins rename the Add-ins tab instead of creating their own custom tab so the DAX Studio button may be on the tab that has another addins name.
3. The Add-ins tab is hidden - the addins tab should automatically unhide if it has any child buttons, but sometimes it does not. If you cannot unhide the add-ins ribbon it might mean some other issue (like the two above are blocking DAX Studio from running)

Other wise there are a few extra logging settings we can try.

In DAXStudioChecker there are a couple of Extra Logging settings at the bottom of [this page](https://daxstudio.org/docs/troubleshooting/daxstudio-checker/) 

Before changing these settings make sure all your Excel windows are closed, it's probably also worth checking in Task Manager that there are no running Excel.exe processes and kill them if you find any as these will block excel from attempting to reload the addins.

First try turning on the VSTO Alerts, then launch Excel. If you get any alert messages please post them back to this issue. Once you've tested this once you can go back into DAX Studio Checker and turn off the VSTO Alerts setting.

Second you can turn on Fusion logging and then launch Excel, once Excel has launch see if there are any logs for daxstudio.dll and if there are any zip them up and attach them to this issue.

**Comment by CBLansdellJr** [comment]
The FARMMS add-in renamed the add-ins tab to FARRMS in my copy of Excel.

When I looked on the FARMMS tab, the DAX Studio icon was there.

I invoked the DAX Studio add-in in an Excel workbook with a Power Pivot model and was able to output a 2 million row table to a .csv file, which is what I needed to do.

Thank you for helping me with this.

***@***.***


SmartestEnergy
​
Charles 
Lansdell He/Him
Lead ETRM Analyst
C(713) 906-0938
E ***@***.***
W
smartestenergy.com
Interested in leaving a review? 
​Let us know about your experience with SmartestEnergy by leaving us a Google review.

​SmartestEnergy US LLC, 110 West Fayette Street, Syracuse, NY 13202, USA.
SmartestEnergy US LLC, registered in Delaware with our head office located at 110 West Fayette Street, Syracuse, NY 13202, USA. Please note and read these warnings and requirements: This email and any attachments are confidential and may contain privileged information. If you are not the intended recipient you must not read, copy or distribute it or take any action in reliance upon it. If you have received this email in error please notify the sender, delete the e-mail immediately and do not disclose its contents. SmartestEnergy US LLC reserves the right to monitor e-mails and attachments entering or leaving its systems without prior notice. Telephone calls may be monitored or recorded. Please consider the environment before printing this e-mail. 
​
