### ISSUE TITLE
Add support for Display Folders in the metadata pane

### ISSUE THREAD

**Issue by dgosbell** [DaxStudio/DaxStudio#127]
Update the metadata pane so that it shows objects in the correct display folders

**Comment by jm98** [comment]
Was just about to raise this but it's already ticketed.

Very useful for tables with a large number of columns.  I would suggest adding an option to enable/disable display folder hierarchy as the alphabetical list is sometimes useful.  So BDD req would be:

As a developer
I would like the option to group a table's columns and measures using the table's display folder metadata (hierarchy and replication)
So that I can better browse tables with a large number of columns  and/or rows

**Comment by dgosbell** [comment]
Added in v2.9.0
