### ISSUE TITLE
Version 2.8 -- Unable to Open .dax Files

### ISSUE THREAD

**Issue by speschl** [DaxStudio/DaxStudio#129]
Just downloaded the most recent version of DAX Studio 2.8 and can't seem to open any of my files. When double-clicking on the file I wish to open in file explorer, a brief error appears stating that DAX Studio has crashed, but then disappears right away. It disappears so quick that I can't read the message or diagnose the problem. Luckily, I captured a screenshot of the issue and have attached it in this post. If I want to work on a file, I must open DAX Studio and then open a .dax file. 

![screenshot 5](https://user-images.githubusercontent.com/33437459/51562954-a79fde80-1e50-11e9-948a-caad47390707.png)

**Comment by dgosbell** [comment]
Thanks for logging this I really appreciated it. We've had one or two people somehow click "Send Report" on this, but I had no details on how it was being triggered. This seems to be happen when opening a file when no other document is open.  I'm testing a fix for this now.

**Comment by paul-preply** [comment]
I played a little bit with this crashing:
(1) I managed to launch DAX Studio inside XL. 
It works fine: loads model and executes just written DAX-queries.
(2) If I want to load pre-written DAX-script in DAX Studio it's just crashed. I suppose it's because of encoding: I noticed that all previously saved DAX-scripts were stored in 1200 encoding, now DAX Studio tries to work with 65001.
(3) If I launch DAX Studio, connect to PP with empty DAX-script window, then I can load prewritten DAX-script without any issues.

**Comment by dgosbell** [comment]
I don't think it's related to then encoding. I tested the file open routines with both types of encoding and they worked fine. 

However I did add some additional logic that checks if the current window is empty and has never been saved before and if so I open the file into that window. The problem appears to occurs if you either have no windows open (such as when double clicking on a .dax file) or when you close all the document windows and then try to open a file. And to make it worse this issue only happens in a release build, when testing in a debug the timing of the events appears to be slightly different which is why it was not noticed earlier.

If you are interested you could download and check the [preview 2.8.1 build](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/21814929/artifacts) to confirm that it fixes these issues for you.

**Comment by speschl** [comment]
After downloading the preview 2.8.1 build, it fixed the issue and I can open .dax files when double-clicking on them. Thanks for the help @dgosbell !

**Comment by dgosbell** [comment]
Great - thanks for confirming this. I'll promote this build to a full release shortly. Thanks for your help with reporting and testing this issue.
