### ISSUE TITLE
DAX Studio cannot parse email string correctly

### ISSUE THREAD

**Issue by markus-zhang** [DaxStudio/DaxStudio#135]
Hi expert,
Not sure if I'm doing the right stuff, basically I have a FILTER() like this:

FILTER(
    table,
    table[email] = "abcdefg@gmail.com"
)

However DAX Studio requests a query parameter for @gmail, which I have no idea why? Thank you!

**Comment by dgosbell** [comment]
Thanks for reporting this. This should not happen, we should not be looking for parameters in strings (or quoted tables or column names). I've added some extra unit tests to cover these scenarios.

A fix for this will be included in the next release. If you interested in testing the fix you can download a [preview build](https://ci.appveyor.com/api/buildjobs/5ryx3l5gflvmjvc1/artifacts/package%2FDaxStudio_2_8_2_setup.exe) off the build server 

This is part of a new feature that we included in the 2.8.0 release. The ability to run queries with embedded parameters has been part of the DAX Language since the begining. This is often used in reporting services reports. We now scan for parameter and popup that dialog you are seeing if we find parameters. So you should be able to write a query like the following:
```
EVALUATE 
FILTER( table
, table[email] = @param )
```
And DAX Studio will prompt for the value of @param each time you run it and you can fill in the parameter with different values.
