### ISSUE TITLE
How to gain repository access in order to commit changes?

### ISSUE THREAD

**Issue by DaveStabilify** [DaxStudio/DaxStudio#139]
Hey guys,

**This is a question and not an "issue".**

I added a minor enhancement to the latest version so how can I get those changes committed to the repository?

The enhancement allows users to view any objects that are dependent upon an individual table, column, or measure. This has proven to be an invaluable feature for me since many of my PBI reports consist of very complex data models and there doesn't seem to be an easy way to discover the objects that are dependent upon any given attribute.

The attached images demo the 3 variations of the new feature:
- Define Objects That Reference Table
- Define Objects That Reference Measure
- Define Objects That Reference Column

![objects that reference table-context](https://user-images.githubusercontent.com/33522415/51992760-99b71280-247b-11e9-8b1c-f4a7d1e99b3a.png)
![objects that reference table-result](https://user-images.githubusercontent.com/33522415/51992763-9cb20300-247b-11e9-880c-9b7f32d353dc.png)
![objects that reference measure-context](https://user-images.githubusercontent.com/33522415/51992771-9facf380-247b-11e9-811b-c8f20f133edc.png)
![objects that reference measure-result](https://user-images.githubusercontent.com/33522415/51992777-a176b700-247b-11e9-9196-119d1da86df7.png)
![objects that reference column-context](https://user-images.githubusercontent.com/33522415/51992781-a3d91100-247b-11e9-8049-e22e0140e5d0.png)
![objects that reference column-result](https://user-images.githubusercontent.com/33522415/51992787-a5a2d480-247b-11e9-90cf-ae8f1211ff93.png)

**Comment by dgosbell** [comment]
Hi @DaveStabilify , thanks, this looks like a nice little feature. The easiest way to submit a feature like this is to submit a pull request. If you are using the GitHub Desktop application it has an option to do this under the branch menu.

![image](https://user-images.githubusercontent.com/8241830/52006605-ac375780-2520-11e9-949f-0b468c06b33b.png)

The GitHub addin for Visual Studio has a similar function.

I can then review the changes and merge them to the develop branch. I currently have some changes to the menus due to a crash report I fixed which I'll have to merge. 

To date we've been doing all our new feature development in the `develop` branch and then we merge to `master` when we do a release. If your pull request is to the develop branch you may need to merge these changes yourself before it will let you submit. Basically I removed the 'Define All Measures' option from the Measure context menu, but at the same time I moved all the methods that only relate to the MetaDataPaneViewModel to that class instead of having them in the base class. (the tool pane base class  should only have options that are shared across all of the Metadata, DMV and Function "windows")

**Comment by DaveStabilify** [comment]
Thanks @dgosbell Darren. I will try another Pull Request per your instructions.

**Comment by DaveStabilify** [comment]
Hey Darren I submitted a Pull Request but I'm not sure if I did it properly.

**Comment by DaveStabilify** [comment]
I created my own Fork but I can't seem to update it via GitHub Desktop. So I'm not sure what else to do.

**Comment by dgosbell** [comment]
Closing this issue as this has now been submitted as a pull request
