### ISSUE TITLE
The syntax for [field] is incorrect

### ISSUE THREAD

**Issue by fzaleta** [DaxStudio/DaxStudio#142]
Good evening!

I'm working with SUMMARIZECOLUMNS and get an incorrect syntax error for the first field in the query below.

```
MfgByWeek =
SUMMARIZECOLUMNS (
    DimDate[MonthName],
    'EHours-RAW'[Item],
    FILTER ( 'EHours-RAW', 'EHours-RAW'[Type] = "FG" ),
    "Mfged2018", SUMX ( 'EHours-RAW', 'EHours-RAW'[Qty] )
)

```
**Error:
Query (3, 12) The syntax for '[MonthName]' is incorrect**

I tried changing the field name to another but receive the same error; I've also tried using `''` to enclose the table name` 'DimDate' ` and still get the error.

This query, however, works in Power BI Desktop as typed.

**Comment by dgosbell** [comment]
Your example is not a query, it is a Power BI measure expression. [DAX queries](https://docs.microsoft.com/en-us/dax/dax-queries) need to have the `EVALUATE` keyword in order to specify what data to return.

If you just want to test a single measure expression like the example you posted you could use the [ROW()](https://docs.microsoft.com/en-us/dax/row-function-dax) function to generate a single row table which you can return from `EVALUATE`.

eg.

```
DEFINE MEASURE 'EHours-RAW'[MfgByWeek] =
SUMMARIZECOLUMNS (
    DimDate[MonthName],
    'EHours-RAW'[Item],
    FILTER ( 'EHours-RAW', 'EHours-RAW'[Type] = "FG" ),
    "Mfged2018", SUMX ( 'EHours-RAW', 'EHours-RAW'[Qty] )
)
EVALUATE
ROW( "MfgByWeek", [MfgByWeek] )
```
