### ISSUE TITLE
Excel launch from DataSource not working

### ISSUE THREAD

**Issue by RuiRomano** [DaxStudio/DaxStudio#148]
After connecting to a Power BI Desktop datasource and click on "Advanced" -> "Excel" I get this error:

Error Launching Excel: Access to the path 'C:\Users\rromano\Documents\My Data Sources\DaxStudio.odc' is denied.

Also noticed that a folder with name "DaxStudio.odc" gets created instead of a file.

Tried to execute in "Run as Administrator" mode and the problem persists.

**Comment by dgosbell** [comment]
yes, this already been noted here #147 I did a "small" tweak to fix a crash that was happening in 2.8.0, but it had this unfortunate side effect if the "Launch Excel" feature has never been run before. You can doenload a preview build of the fix for this [here](https://ci.appveyor.com/api/buildjobs/tmrpug045ap17r6a/artifacts/package%2FDaxStudio_2_8_3_setup.exe)
