### ISSUE TITLE
"portable" version

### ISSUE THREAD

**Issue by thetom88** [DaxStudio/DaxStudio#154]
I don't know if anyone have encountered this problem, but I often have to develop on machines where I don't have an account with the privileges to install new software. So I'm asking if there's the possibility to create a portable version of DaxStudio that doesn't require installation.

**Comment by dgosbell** [comment]
I have come across this problem in 2 different forms.
1. Where users don't have admin rights, but can run .exe programs
2. Where users don't have admin rights and cannot run anything not installed by an admin

So we could possibly create a portable build that would fix scenario 1 but scenario 2 is not something that we can work around. :) I've also started looking at possibly building a "non-admin" installer which would be another option for scenario 2. 

How would you see this being delivered? Would it work for you to just have a zip file with all our .exe and .dll files included so that you could unzip then double click on daxstudio.exe? 

Or are you thinking of something that uses the launcher from https://portableapps.com/ ?

**Comment by thetom88** [comment]
Thank you dgosbell for your answer. I was thinking about the first scenario you've described and yes, I was thinking about a zip that contains all dll and executables needed to run DaxStudio. I was digging around portableapps, but I'm a little afraid of using it since it's not open source and I don't know what their software is doing.

**Comment by dgosbell** [comment]
The simpler approach of using a zip is easier to implement and I think it also fits the use case where you might be remoted onto a server and need to run DAX queries, but don't want to install anything. 

I'll just need to think about what to do with saving options settings (I don't really want to write these to the registry if we are not installed) as well as seeing if anything can be done if the version of .Net that we need is not installed.

**Comment by SemihBI** [comment]
Hi thetomm88,

great to see that you already created this issue, as I have the same request. 
dgosbell did you made any progress? Would be amazing to have DAXstudio as portable version as well.

Thank you.

**Comment by dgosbell** [comment]
@SemihBI no progress yet. To be truely portable there are a few settings and things that are written to the registry and user's profile which I would like to write to a relative path for a portable version.

**Comment by alexjj** [comment]
Other software that installs without admin permissions does so by putting everything in the users local folder, `c;\users\<username\%appdata%\{local, roaming}`, so I don't think absolutely everything needs to go in the folder with the exe and other files....if that makes it easier for you...

**Comment by dgosbell** [comment]
@alexjj - thanks for the comment. But a "portable" is different to a non-admin installer. 

To be portable you should be able to just copy a folder with all the files needed by the app to another location and run it by double clicking on the exe file. You can almost do that now with DAX Studio, but we do write our settings to the registry so we are not 100% portable yet.

I have also thought about a non-admin installer but it looks like I'd need to build a second separate installer and I'm not sure if there would be a lot of value in this. In the couple of organizations I've seen recently where they've removed admin rights from end users they've paired this with Applocker policies which also block users from running .exe files from the users local folders.

**Comment by alexjj** [comment]
I would be happy with purely portable :) Appreciate your time on this.

**Comment by shawnfactorial** [comment]
Would like to add a +1 to this.  As a consultant, I often have to use a laptop that is locked down to the extent that I can run standalone .exe's, but can't install things without admin rights.  Thankfully, I can get access to apps like Slack, VS Code, and Chrome because they all have installs that don't require admin -- and I would love it if DAX Studio were the same.  I know it would require you to maintain a separate installer, but it would be quite helpful -- even if it was just a one-off that you didn't update with every minor release.

**Comment by gflores1023** [comment]
I came in searching for a portable/zipped version of Dax Studio. Being able to use this on remote machines without admin access would be incredibly useful. 

Thanks for Dax Studio!

**Comment by Kuronno** [comment]
A portable version would help immensely!

**Comment by csatlos** [comment]
> But I have also been working on a "pure" portable build that is just a zip file which you can unzip and double click on daxstudio.exe. If you would like to try it and let me know how it goes there is a zip file on our build server at the following location for the 2.11.0 build https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/33382194/artifacts

Thanks very much for this. So far so good with portable versions 2.11.0 and 2.11.2.

**Comment by dgosbell** [comment]
@csatlos  thanks for the feedback. I think the portable build is pretty solid now so I might look at adding it as a second download option on our homepage.

**Comment by dgosbell** [comment]
We are now publishing both the installer and portal (zip) versions as of the 2.12 release
