### ISSUE TITLE
Text Editor Scaling

### ISSUE THREAD

**Issue by CatfishRow** [DaxStudio/DaxStudio#163]
Scaling within editor inconsistent with all other applications.  All 3 text editors in screenshot set to same font / fontsize / 100% scaling.  DAX Studio states 100% but is not.  All text within application is blurry.
![image](https://user-images.githubusercontent.com/48459612/54165901-cd437e80-44b6-11e9-9a4c-2198a7b3af95.png)

**Comment by CatfishRow** [comment]
DaxStudio appears to disregard Windows ClearType settings.

**Comment by CatfishRow** [comment]
Thanks Darren, I very much appreciate the quick response.
As one of those people who struggle to read smoothed (or scaled) fonts,
this scaling is critical to being able to use the software without
headaches.

Thanks again,
-Diz

**Comment by dgosbell** [comment]
So I've just double checked and none of the theme changes are live in any of the public builds, I still have that isolated in a private branch, so that will not be affecting clear type. 

The only issue I can confirm is that DAX Studio is using a different unit of measure for the font size from most other apps which will result in the font appearing about 33% smaller, but we are not doing any explicit enabling/disabling of Clear Type.

I've zoomed in to 300% on my machine and compared Word, Notepad and Notepad++ to DAX Studio at a similar font size (so setting DAX Studio to 15 and the others to 11) and I can't see any noticeable differences in the font rendering between the 4 of them on my machine.

Can you let me know what your display settings below are set to? If your's are different to mine this might explain why I can't seem to reproduce this issue.

In your Windows Display settings do you have the scale and layout set to 100% or some other percentage?

![image](https://user-images.githubusercontent.com/8241830/54240094-37b8f500-4571-11e9-8fc6-92fb79b456ea.png)

And under the "Advanced Setting" link to you have the option on to allow Windows to attempt to fix blurry apps and do you have the custom scale setting not set (so that it shows the 100 - 500 text)?

![image](https://user-images.githubusercontent.com/8241830/54240424-1d334b80-4572-11e9-94fc-63ec4729401f.png)

And if you have multiple screens connected does it make a difference if DAX Studio is on the main display or a secondary display?

**Comment by CatfishRow** [comment]
Hiya Darren,

I have all the same scaling settings as you. I have ClearType disabled.
The issue occurs irrespective of which monitor I use (I am working with
multiples but the issue is agnostic).

I'm aware that not many people prefer to disable ClearType but for me it
makes a hug difference.  From the following screen shot, I find the only
text that is clear and easy to read is "ClearType makes the text you see on
the screen sharper, clearer, and easier to read."  The other text,
including "Make the text on your screen easier to read" is blurry and
uncomfortable.
[image: image.png]
Hope this helps,
-Diz

**Comment by dgosbell** [comment]
> I have ClearType disabled.

Oh, I thought you were complaining that you had ClearType enabled but DAX Studio was not honouring this. Apparently there are some things (like transparent backgrounds on text boxes) that can interfere with the ClearType rendering if it is switched on. But I don't believe there is any way that an application can do the reverse and effectively "switch on" clear type if it's disabled globally.

So apart from the units of measure difference is DAX Studio render fonts any differently to other applications? (ie. if you set DAX Studio to a font size of 15px it should display roughly the same as other apps set to 11pt)

>  From the following screen shot, I find the only
text that is clear and easy to read is "ClearType makes the text you see on
the screen sharper, clearer, and easier to read."  The other text,
including "Make the text on your screen easier to read" is blurry and
uncomfortable.

I can't actually see your screen shot, you may actually have to paste it into the issue on github. I think attachments get stripped out of email replies.

**Comment by dgosbell** [comment]
The recent 2.8.4 release includes an update to fix the units of measure for the font sizes. I can't see any other issues on my test systems with font clarity so I'm going to close this issue, but if you have issues with font clarity in DAX Studio compared to other applications feel free to raise a new issue
