### ISSUE TITLE
Error attempting to export data to SQL Server

### ISSUE THREAD

**Issue by natasakvinfo** [DaxStudio/DaxStudio#174]
Hi,
I am trying to export data to SQL Server from Power BI using DAX Studio. I don't have administrator priviliges and I can login to the SQL Server as a user using Windows authentication. When I try to export data from DAX Studio I am getting the following error:
"Error when attempting to export all data - Login failed for user 'PROD\B045585'".

I am using the following connection string
Server=C1506998;Initial Catalog=QuantitativeTargets;User ID=PROD\B045585;Password=Password1;

Please help!

**Comment by dgosbell** [comment]
The "login failed" error means that your username or password is incorrect.

**Comment by natasakvinfo** [comment]
Hi,
Thanks for the answer.
The problem is that username and password are correct as I can login using SQL Server Management Studio. Can it be Windows authentication that gives problems or something else?

**Comment by dgosbell** [comment]
What authentication option are you using in SSMS "Windows Authentication" or "SQL Server Authentication"? Whenever you specify User ID/Password in a connection string you are implicitly using SQL Server Auth. If you want to use Windows Auth you would use a connection string like the following:

```Server=C1506998;Initial Catalog=QuantitativeTargets;Integrated Security=true;```

And the connection will automatically use the identity of the user that DAX Studio is running under.

**Comment by natasakvinfo** [comment]
Thanks a lot for the answer, that worked.
But I have another problem. When I try to export data to SQL Server, I am getting the following error:

"Error when attempting to export all data - An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias name. Aliases defined as "" or [] are not allowed. Change the alias to a valid name."

All my tables and columns are named properly. Also, DAX Studio added DateTableTemplate_e6ad4661-f374-4413-9068-5435c9f652b0' table which I don't have in my project.

Please help!

**Comment by dgosbell** [comment]
> All my tables and columns are named properly. 

This is probably caused by some sort of symbol character in a column name. I've just been doing some research and it turns out that there is one character, the vertical pipe | that can be included in DAX column names, but but causes issues in SQL column names. It looks like the column is created but the inserts throw this error.

Do you have any columns that include the pipe symbol "|" ?

>  Also, DAX Studio added DateTableTemplate_e6ad4661-f374-4413-9068-5435c9f652b0' table which I don't have in my project.

DAX Studio does not add this. Power BI generates this as a hidden table when you have the "Auto Date/Time" setting enabled in the "Data Load" options for you pbix file (and this is always enabled by default). If you are not using the Auto Date/Time features you can switch this off in Power BI and this template table will be removed. 

In a future version we are planning to hide the tables generated by this feature so the table list in DAX Studio will match the one you see in Power BI.

**Comment by natasakvinfo** [comment]
Thanks for the Auto Date/Time setting, I switched it off. 
I don't have columns that include pipe symbol?! I am testing with only two tables Countries with CountryID and CountryName and Years with YearID and YearName.
It must be something else.

**Comment by dgosbell** [comment]
Hmm, can't see anything in those names that would cause an issue. I created a test model with the same names and it exported fine.
![image](https://user-images.githubusercontent.com/8241830/55951539-dc2a7600-5c9a-11e9-80c9-ab1f787d0787.png)

Are you able to create a test model that reproduces this behaviour and upload it here?

What version of DAX Studio are you running? Is it at least 2.8.3?

**Comment by natasakvinfo** [comment]
I am running DAX Studio 2.8.3. I tried uploading the project but nothing happend. The test model you created looks the same as mine. How can I upload?

**Comment by dgosbell** [comment]
If you should be able to attach files by dragging & droping the file from Windows Explorer directly into a new comment on this issue on github or by copy and pasting it.

**Comment by natasakvinfo** [comment]
PowerBI files are not supported :-(

**Comment by dgosbell** [comment]
try zipping it first

**Comment by natasakvinfo** [comment]
[RepportV6.0.zip](https://github.com/DaxStudio/DaxStudio/files/3068435/RepportV6.0.zip)

**Comment by dgosbell** [comment]
That file works fine for me. Did you enter "dbo" or some other schema name into the schema box in the export dialog?

**Comment by natasakvinfo** [comment]
I didn't enter schema name and I left "Truncate" checked.

**Comment by dgosbell** [comment]
OK, it looks like if you leave the schema name blank it throws this error.  For the time being if you enter something in this box it should avoid this  error. Can you try this and see if that corrects this issue for you?

I'll fix this so that it defaults to "dbo" or something like that if it's left blank before we move this feature out of preview status. I think I'd also like to build something more user friendly that just entering a raw connection string to connect to SQL.

**Comment by natasakvinfo** [comment]
I tried entering dbo in the schema box and it worked :-). You are right with making export to database more user friendly... Anyway, I am very happy with having something like DAX Studio. Looking forward for new features.
Thanks a lot for help,
Regards,
Natasa.

**Comment by natasakvinfo** [comment]
Sorry, one more question: is it possible to export data from two different power bi project to the same sql table? I don't want to overwrite data in the table, I want to insert additional data to the table :-)

**Comment by dgosbell** [comment]
It would be if both tables are identical in every way (ie. have the same name and same columns with the same names and data types). If this is the case you would just untick the truncate option when exporting the second table. 

If the structures of the 2 tables are slightly different you could export one table direct to SQL then export the second one to a csv file and then use the import/export wizard in SSMS to add the data from the file to the first table.
