### ISSUE TITLE
Can't write "&" character

### ISSUE THREAD

**Issue by Arklur** [DaxStudio/DaxStudio#181]
Hello,

If I try to write the "&" character, DAX studio inserts "//" instead, and as I see, there is no option to disable this shortcut.

**Comment by dgosbell** [comment]
what sort of keyboard layout/regional settings are you using? The "//" commenting is tied to the Ctrl-Alt-C key combination, I'm not sure how you are getting this from typing "&". I certainly don't have any issue typing "&" on any of my machines.

**Comment by Arklur** [comment]
Oh I see, then probably that's the problem. I'm using "HUN", so the "&" is on the "C" for me.

**Comment by dgosbell** [comment]
Unfortunately the hotkeys are currently hardcoded into the UI layer so there is no way to disable or change them. I think I've found a technique which should make it possible to customize the hotkeys so that you could change or remove the key assignments. I'm just in the final stages of helping organize our local SQL Saturday which is coming up in a month so I may not be able to get around to working on this until after that

**Comment by Arklur** [comment]
Cool, looking forward to this "fix" (...rather feature I guess).

And love the tool anyway, thanks for making it, you are awesome!

**Comment by Arklur** [comment]
Sorry for pinging, but any update on this?

**Comment by dgosbell** [comment]
That's OK, thanks for the ping. The technique I found for removing the hard coding from the UI layer appears to be working well, I just forgot to come back and build a UI for setting the key bindings. I've put together an basic setting screen which I will release as a preview feature in the next release with an initial subset of the hotkeys.
