### ISSUE TITLE
Data Export

### ISSUE THREAD

**Issue by janizz** [DaxStudio/DaxStudio#187]
The Data Export ability is great (to csv and SQL Server!).... can you add the funcitonality to select tables?
It frustrates me when some errors get in the way (when given a complex model from clients) and I have to repeat export (to find another error) all tables which takes time.

ps: The last error I got is (down), but there is no column/measure moving avg price in the model!

05/06/2019 11:41:39		Error when attempting to export all data - OLE DB provider 'STREAM' for linked server '(null)' returned invalid data for column '[!BulkInsert].moving avg price 3m'.

**Comment by dgosbell** [comment]
Yes, we could do that. I think I'd also like to make the error handling better, so that it just logs the error and moves to the next table. I'd also like to improve the dialog box for connecting to SQL so users don't have to type in a raw connection string (which is why we've kept this as a preview feature for the time being)

> 05/06/2019 11:41:39	Error when attempting to export all data - OLE DB provider 'STREAM' for linked server '(null)' returned invalid data for column '[!BulkInsert].moving avg price 3m'.

The export feature just runs `EVALUATE tablename` for each table in the model and outputs the results. We don't list any column names explicitly, the export should output all columns (measures are not exported).

If you run the either of the following does it return any results?
```
SELECT * 
FROM $SYSTEM.DBSCHEMA_COLUMNS 
WHERE COLUMN_OLAP_TYPE = 'ATTRIBUTE'
AND COLUMN_NAME = 'moving avg price 3m'

SELECT * 
FROM $SYSTEM.TMSCHEMA_COLUMNS 
WHERE ExplicitName = 'moving avg price 3m'
```

**Comment by janizz** [comment]
@dgosbell thanks for your help, I found the error and moved over it. Anyways it would be excellent to be able to export as you described! :)
