### ISSUE TITLE
Dax Studio 2.9.1 can't read metadata when connecting to model with a lot of measures

### ISSUE THREAD

**Issue by wenihal** [DaxStudio/DaxStudio#189]
I have a tabular model with a lot of measures (3K+ measures). When connecting to this model, DAX Studio reads metadata forever. It's working ok (even with bigger models) in version 2.8.2.

**Comment by dgosbell** [comment]
I can't think of anything specific that might have caused this between 2.8.2 and 2.9.1

I have access to a model with 1.4k measures and I can't see any noticeable difference between these 2 versions. Even when I do an alter on the model (which causes the server to flush all it's metadata caches) it still only takes around 3 seconds to load the metadata on the first connection but that is a server side delay. After the initial load I can switch back and forth between this model and other models with sub-second refresh times.

What type of data source are you connecting to (PBI Desktop, SSAS, AzureAS)?
What version number does DAX Studio show in the status bar for this data source?
Is it possible to share a create script for this model (just the metadata, we don't need any data)?

**Comment by wenihal** [comment]
I thing that comes to my mind is "Display folders" feature that came to 2.9.x.

I'm connecting to SSAS instance (SQL 2016).

I could send by @ my model with 11K+ measures for testing. However, I don't want to make this publicity available.

**Comment by dgosbell** [comment]
Yes, I was looking at the routines reading the metadata, it occurred to me this morning that it's probably the display folders as my "big" model is an old one that pre-dates folder support. If you could email me the metadata for one of your large models that would be great. I have a gmail.com account with the address of dgosbell (I'm splitting this up to make it harder for the spammers to scrape)

**Comment by MichelPilote** [comment]
I have the same problem with 2.9.1,
I have a cube with ~900 measures and I cannot see any of them

I uninstalled 2.91 and reinstalled 2.8.3 and it works great


Thanks for the great tool it make my life a lot easier

**Comment by dgosbell** [comment]
@MichelPilote I can't tell from the limited information if your issue is the same or not. But currently I can't reproduce this issue. I used a script to generate a model with 10,000 measures in 100 folders and it takes about 20 to load (but Power BI Desktop takes about this long too) and there was a lag of 3-4 seconds when expanding the table to display the measures/folders.

@MichelPilote - Is it possible to attach or email a create script for your model? 

Or if you or @wenihal want to try a preview build - I have an update on our build server [here](https://ci.appveyor.com/api/buildjobs/60huq6exa1pkb3sn/artifacts/package%2FDaxStudio_2_9_2_setup.exe) where I've added an optimization on the metadata refresh which has doubled the performance on my test model, but I'm still not sure if this will fix this issue or not as I'm not sure if my generated model is representative of the behaviour you are seeing.

**Comment by MichelPilote** [comment]
Hello Darren,

See attached file for my project that does not display the measures.

I will try the version on the server today if my boss leave me alone for few minutes ☺

Thanks for all the stuff you do for our community

Michel Pilote

**Comment by reubster** [comment]
Having the same problem. I rolled back to 2.8.4 and it's fine. 

I think there was behaviour relating to whether hidden measures was checked or not, not completely sure. 

I had the same issue with both Azure AS models and a version on my desktop.

**Comment by dgosbell** [comment]
@reubster - I'm not sure what you mean by "the same problem" from what I can tell there are 2 different problems in this thread. Can you be more specific about the behaviour you are seeing? 

I'd love to fix these issue, but I don't have any way of reproducing either of them at the moment. None of the models I have access to exhibit any behaviours like either of the ones mentioned here. If you could either upload a create script of a model that exhibits this issue or email it to darren @ daxstudio.org it would really help. I'm hoping to get a copy of the model from Michel who I've contacted offline as github strips off any attachments if you just reply to the notification email.

**Comment by wenihal** [comment]
@dgosbell I've sent you my model with 11K+ measures that do not open in 2.9.x, but opens in 2.8.x

**Comment by reubster** [comment]
@dgosbell ... Sorry about that. 

When I open 2.9.x and connect to my model, the meta-data pane hangs indefinitely. 

![image](https://user-images.githubusercontent.com/19515061/59705081-8b348200-91f5-11e9-9fbf-32c94a2682ac.png)

Then; 
- while it's still retrieving the meta-data 
- I go to Options 
- change the hidden to EITHER checked or unchecked 
- switch back to Query window 
- the meta-data is displayed correctly 

If I click "Refresh Meta-data" ... it hangs again. 

![image](https://user-images.githubusercontent.com/19515061/59705350-1f9ee480-91f6-11e9-9d32-c2b5fc87699f.png)

I have been running a SQL Server Profiler trace for another reason and can see the Discover Begin/End and Server State Discover Begin/End commands have completed without error. 

So it's definitely the client-side meta-data handling. 

I'd prefer not to send you my model. 

I have about 50 measures in the model.

**Comment by dgosbell** [comment]
@reubster thanks very much for the follow with the screenshots, that really helps a lot. Your issue appears to match the one posted by @wenihal and he's sent me a copy of his model that I can use for testing, so I should be able to find a solution now. There are definitely 2 similar issues here as @MichelPilote sent me the metadata for his model and I've been able to identify a fix for that scenario.

I've checked the view hidden objects setting, but that appears to be a side effect rather than the direct cause.

**Comment by dgosbell** [comment]
A big thank-you to those who kindly provided access to the metadata for their models. Using this I was able to find and fix the following 4 issues and have unit tests in place for the first 3 issues:

- Loading models with a hierarchy in a folder caused an infinite loop on loading
- There was an edge case caused by certain combinations of display folders with & without spaces in the names that caused partial loading of the metadata
- The Hidden status on hierarchies was accidentally flipped (so visible hierarchies were tagged as Hidden=true and hidden ones were tagged as Hidden=false)
- I've adding caching for the internal references used in the CSDL metadata for linking objects to display folders which has resulted in metadata refresh performance increase of 200%-500% (a model that loads in 30 seconds on Power BI loads in 6 seconds in DAX Studio)

An update to the 2.9.2 preview is available [here](https://ci.appveyor.com/api/buildjobs/qaco9n04f1po2nyk/artifacts/package%2FDaxStudio_2_9_2_setup.exe) if any of you would like to test it. If everything goes smoothly I'll do a public release in the next few days.

**Comment by wenihal** [comment]
@dgosbell I tested preview and I can confirm that it now works ok with my big models. Meta data is loaded within few seconds for biggest model. Thanks a lot for this fix!

**Comment by MichelPilote** [comment]
Hello Darren,

It work great and very fast

Thanks ☺

Michel Pilote
