### ISSUE TITLE
Data Export to SQL Server

### ISSUE THREAD

**Issue by vipulgarg95** [DaxStudio/DaxStudio#194]
I get this error again and again while exporting to SQL server:

I have a local server instance and I use the windows authentication:
Server=US\MSSQLSERVER01;Initial Catalog=test data; Integrated Security=True; Trusted_Connection=yes;

Error when attempting to export all data - An object or column name is missing or empty. For SELECT INTO statements, verify each column has a name. For other statements, look for empty alias names. Aliases defined as "" or [] are not allowed. Change the alias to a valid name.

**Comment by dgosbell** [comment]
That's probably going to caused by some sort of special character in one of your table or column names in your model that is legal in DAX but not in SQL or maybe something that is legal, but is not being escaped correctly in the SQL we generate. 

Are you able to create a small test model that triggers this error and attach it to this issue on github?

**Comment by dgosbell** [comment]
Closing due to lack of response. If you have more information to add feel free to re-open this issue
