### ISSUE TITLE
IDEA: opportunity to connect not only to static tables but also objects created within the PBI dashboard

### ISSUE THREAD

**Issue by jasiluka** [DaxStudio/DaxStudio#207]
It seems dax studio now only allows to connect to a tables that are already connected to power bi.
What would be great to have is also to connect to the objects within the power bi (such as matrix table) and export the data from it. 

Such way we could overcome 30k / 150k row limitations on power bi

**Comment by dgosbell** [comment]
This is not possible they way you are describing it because visuals (like the matrix) do not hold any data that can be queried. They actually generate queries back against the tables stored in the Power BI tables. 

What you **can** do is to capture the query generated by a matrix visual using a technique like [the following](https://www.sqlbi.com/articles/capturing-power-bi-queries-using-dax-studio/) then you can edit that query in DAX Studio and adjust any TOPN restrictions in order to export whatever you like.

**Comment by jasiluka** [comment]
Thanks Darren,
very helpful! I was able to spot a measure that was causing the query to
run way too long and changed the calculation of it.
