### ISSUE TITLE
Cannot install DaxStudio... .NET Framework 4.7.1 failed to install

### ISSUE THREAD

**Issue by jschlereth** [DaxStudio/DaxStudio#209]
When trying to install DaxStudio I received this error message:

![DaxStudioError](https://user-images.githubusercontent.com/44686409/63108216-f081c680-bf4b-11e9-9565-f57314ad9611.png)

When I downloaded and attempted to install .Net Framework 4.7.1 I received this error message saying it wasn't supported by the OS:
![image](https://user-images.githubusercontent.com/44686409/63108276-1018ef00-bf4c-11e9-9249-5695a0f20fa1.png)

I'm currently running a 64bit version of Windows 10 Enterprise 2015 LTSB. I've tried restarting it and re-installing it, to no avail.

Any suggestions on how to fix?

Thanks.

**Comment by dgosbell** [comment]
Probably your only option on a version of Windows 10 that old is to use an old release of DAX Studio. I think 2.7.4 would probably work which you can get from here [https://github.com/DaxStudio/DaxStudio/releases/tag/2.7.4](https://github.com/DaxStudio/DaxStudio/releases/tag/2.7.4)

I try to keep DAX Studio on the lowest version of .Net that I possibly can that also supports all the functionality we need in order to work across a wide variety of machines.

The current version of DAX Studio requires .Net 4.7.1 for a number of features and it looks like only the 2016 LTSB or later has support for .Net 4.7.1 according to [this forum post](https://social.technet.microsoft.com/Forums/en-US/85467673-6e8c-49d2-b6df-371babd9f5f3/windows-10-enterprise-2015-ltsb-officially-supports-net-47?forum=win10itproapps). I also did a [search in the windows update catalog](https://www.catalog.update.microsoft.com/Search.aspx?q=.Net%20Framework%204.7.1%20for%20windows%2010%20version%20) and it does not show an installer for the 2015 LTSB release either.
