### ISSUE TITLE
multi-factor authentication not properly supported on AAS

### ISSUE THREAD

**Issue by o-o00o-o** [DaxStudio/DaxStudio#211]
I just tried to connect to an AAS instance and got the prompt for multifactor authentication as this is setup on our Azure Active Directory. It said I needed to re-enter my password but when I clicked on the next button I just got the error 

![image](https://user-images.githubusercontent.com/13693159/63449715-86c85780-c438-11e9-81cc-ff58c0c46778.png)

(I did it twice to check)

Doing the same thing with Tabular Editor gave me the same experieicne but it did continue correctly and now I have the token which now lets me connect but it would be good if Dax Studio supported MFA completely

**Comment by dgosbell** [comment]
What versions of DAX Studio and Tabular Editor are you using? The authentication support is actually built-in to the Microsoft provider libraries, it's not something explicit, so I'm not sure why the experience would be any different unless maybe it's a difference in the provider versions.

**Comment by dgosbell** [comment]
I've checked with some contacts at Microsoft and they've confirmed that this should work with the version of the ADOMD driver that the current version of DAX Studio is using. So my only guess is that you are on an old version. So I'm going to close this issue due to a lack of response. Feel free to re-open if you have more information to add.

**Comment by o-o00o-o** [comment]
Hi sorry for the delay, I was running the latest version at the time. It is tricky to repro this as it only happens when I get challenged which is every 30 days or so. I will update if I see it again. Is there anything else you would like me to try if it does happen again?

**Comment by dgosbell** [comment]
Hmm, that's going to be tricky to nail down then. 

So once you have a token does DAX Studio work OK?

Did you just enter the "asazure://..." server name into the server box on the connection dialog or did you try to add other parameters?

I've double checked the doco on [AzureAS connection strings](https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-connect) and it does not indicate any special handling for MFA. I've talked to the product team and they've confirmed that there is nothing special that client apps like DAX Studio should have to do in order to support MFA.

The current 2.9.4 release of DAX Studio does include the very latest Microsoft data providers, so maybe try with that and see how it goes. I don't currently have access to a tenant with MFA switched on so it's not something I can explicitly test myself.

**Comment by o-o00o-o** [comment]
Haven't seen this for a long time so I think this has been resolved
