### ISSUE TITLE
keyword where is not acknowledged by intellisence

### ISSUE THREAD

**Issue by hodoshow** [DaxStudio/DaxStudio#212]
keyword where is not acknowledged by intellisence

**Comment by marcosqlbi** [comment]
The word "where" is not a keyword in DAX...

**Comment by hodoshow** [comment]
Sorry, what about dax studio whether other standard SQL statements are keywords like
Select
From
Order by

**Comment by marcosqlbi** [comment]
DAX Studio is for DAX, not for SQL! :)

**Comment by hodoshow** [comment]
What about your documentation features via DMVs?

**Comment by marcosqlbi** [comment]
You're right, that's a special syntax for DMV only. Let's see what Darren says about that, I forgot that the editor highlights SELECT and FROM in those cases!

**Comment by hodoshow** [comment]
No worries!
Thanks for responding. Big fan of yours

**Comment by dgosbell** [comment]
Syntax highlighting is one thing, intellisense is another. 

We currently syntax highlight some of the MDX/DMX keywords (like SELECT, FROM) but we don't support intellisense for those keywords. I've checked in a fix to add WHERE as one of the static keywords for syntax highlighting, so that will come out in the next release. 

But Marco is correct that we only support DAX _intellisense_, we have no plans to add intellisense support for DMX or MDX (other than the current support we have for the $SYSTEM keyword). We do support executing DMX or MDX queries, but that is just because the tabular engine knows how to execute these. We don't need to do any special validation or parsing of the query or tell it what syntax we are sending we just pass through the text and the engine figures out the syntax on it's own.
