### ISSUE TITLE
Bug On Start if system's Date Format is MM/DD/YYYY: "String was not recognized as a valid DateTime"

### ISSUE THREAD

**Issue by boke44** [DaxStudio/DaxStudio#253]
![bug2](https://user-images.githubusercontent.com/57920230/69131980-7bc2a900-0ab3-11ea-97bf-3e542236106e.png)
DAX shows this bug report briefly for less than half a second before crashing and closing.

It got fixed after I changed system's date format from MM/DD/YYYY to DD.MM.YYYY.

**Comment by dgosbell** [comment]
Yes, this has been reported before (see #240 and #251) 

It only happens when you change the OS date format, but a proper fix is included in the [latest preview build](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/28649169/artifacts) and we will probably release an updated official version shortly.

**Comment by dgosbell** [comment]
This should now be fixed in the 2.10.0 release
