### ISSUE TITLE
XML for Analysis Request Timeout

### ISSUE THREAD

**Issue by rminder** [DaxStudio/DaxStudio#282]
I am using DAX Studio to export a Power BI table (25M rows) to SQL Server. After exactly 10 minutes, I get the following error:

**_Error export data to SQL Server: The XML for Analysis request timed out before it was completed. Timeout value: 3600 sec. The XML for Analysis timed out before it was completed. Timeout value: 3600 sec._**

I believe this has something to do with the ExternalCommandTimeout setting on SSAS which is set to 3600 seconds by default. I've tried changing this value but it seems DAX Studio isn't respecting the value.

Therefore, it seems that DAX Studio can only be used to export data to SQL Server as long as the process takes less than one hour. If it takes longer than that, this error occurs.

**Comment by dgosbell** [comment]
The **ExternalCommandTimeout** setting on the server relates to Server initiated connections to external data sources (so processing operations) not client connections. So I'm not surprised that changing that has no effect.

The details of this issue are not clear to me. You initially talk about a Power BI table, then you mention an SSAS setting. You also say it fails after 10 minutes with the error saying the 1 hour timeout has been exceeded. 

So which data source are you using and how long is it running before timing out?

We don't do any explicit timing out of queries in DAX Studio. That is all done by the data engine or the Microsoft client libraries. Typically any timeouts or memory errors come from the tabular engine not from DAX Studio (with the exception being some of the traces like server timings where we have a timeout in case some of the events don't get captured). Result sets currently have to be materialized in RAM on the "server" before being streamed to DAX Studio and this is usually where we see issues with large exports.

One thing you could try is setting the ```Timeout=``` parameter on the connection. Try setting this to something larger than 3600, like 7200 for 2 hours or even 36000 for 10 hours.
![image](https://user-images.githubusercontent.com/8241830/73695009-59910c80-472d-11ea-9c79-0debbf9a7ae1.png)

**Comment by rminder** [comment]
Hi Darren,

I am using DAX Studio to connect to a Power BI instance I have running. In
DAX Studio, I am using the Export to SQL Server feature to export a table
in the PBI database to SQL Server. The table has 25M rows. The process runs
for exactly 1 hour and then DAX Studio terminates with the error I
indicated in my bug report. I mentioned the SSAS setting because, as you
know, when PBI spins up it starts an instance of SSAS locally and SSAS has
a configuration setting named ExternalCommandTimeout of 3600 so I thought
that might be the culprit. Let me know if I can give you any more
information.

Randy

**Comment by rminder** [comment]
Just as an FYI I reconnected to my local PBI database and changed the timeout, as you suggested, to 36000. However, it’s not clear to me why this would help. What exactly is timing out after 1 hour?

I’ll keep you posted on what I find.

Randy

**Comment by rminder** [comment]
Darren - I set the timeout on the connection to 36000, as you suggested.
Instead of timing out after 1 hour, I got a different timeout error after
about an hour and 45 minutes of execution. I do not believe this is related
to any sort of memory constraints since Task Manager showed about 2GB being
consumed by SSAS and my computer has 16GB of RAM.

This is the error I received, which is a bit different than what I was
getting:

[image: image.png]

**Comment by dgosbell** [comment]
> What exactly is timing out after 1 hour?

So when you export a table all we are doing is running a query like ```EVALUATE <table>``` to get the data, then we send it to the specified output. So it is the query that is timing out and I believe that if you do not explicitly set the ```Timeout=``` property - that it will default to 1 hour.

> I set the timeout on the connection to 36000, as you suggested.
Instead of timing out after 1 hour, I got a different timeout error after
about an hour and 45 minutes of execution.

OK, so I think this proves we have "fixed" the timeout issue. But unfortunately it looks like you replied via email and Github strips out all images and attachments from email replies so I can't the error you got.

But from the fact you are talking about memory usage I assume you got an out of memory error. If you go into Help -> About in Power BI Desktop are you possibly running the 32-bit version? If so 32-bit programs cannot use more the 2Gb of RAM so this would explain seeing error at this level. 

When the tabular engine loads data it reads and compresses it in chunks. But when you run a DAX query the engine processes the query and builds a single, uncompressed result set in memory and once the entire result set has been assembled it then streams the results to the client. So this means that you can easily store hundreds of millions of rows in a model, but you may not be able to export them all out in one go.

The only work around at the moment is to export smaller sets of rows.

If you run something like ```EVALUATE FILTER( <table>,  <filter>)``` you could set a filter on something like ```'Date'[Year] = 2019``` or whatever else makes sense for your data set. If you use the File output in DAX Studio you can send the output to a series of csv files which you could then import back into a single SQL table.

**Comment by rminder** [comment]
Darren - I am running the 64-bit version. The error I received is:

Error exporting data to SQL Server: Execution Timeout Expired: The timeout
period elapsed prior to completion of the operation or the server is not
responding.

Thank you - Randy

**Comment by dgosbell** [comment]
That sounds like a timeout on the SQL connection side this time. 

Do you see the row count ticking over at all for this table? 

If you try exporting to CSV does that work?

Is your model using Import mode or Direct Query?

**Comment by rminder** [comment]
I don't believe it was a SQL timeout, but it doesn't really matter anymore.
I have found a different way of getting the data into SQL Server. I agree
with you that with large datasets, the DAX memory constraints make this
sort of thing almost impossible.

Thanks very much for your help. I love DAX Studio. In fact, I created a
Udemy course covering DAX Studio because I believe in it so much. You can
see it here:
https://www.udemy.com/course/mastering-dax-studio/learn/lecture/16367092#overview

Randy

**Comment by dgosbell** [comment]
This should have been fixed in v2.13.1 I added support for TOPNSKIP to the queries generated by the export function so we can now stream the data out of a Tabular model an into SQL Server in million row batches without having to materialize the whole resultset first.
