### ISSUE TITLE
DaxStudio not starting after install

### ISSUE THREAD

**Issue by monicaenders** [DaxStudio/DaxStudio#286]
**Describe the bug**

**To Reproduce**
1. Go to '.https://www.sqlbi.com/tools/dax-studio/ and download'
2. Run downloaded file'
3. When trying to launch  the splash screen pops up, but not the application

Run DaxChecker, and this is error report at end of file:

FATAL ERROR:
Object reference not set to an instance of an object.
   at DaxStudio.CheckerApp.Checker.CheckRegistrySettings()
   at DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

**Expected behavior**
DaxStudio should launch application

**Comment by dgosbell** [comment]
> Run DaxChecker, and this is error report at end of file:
>
>FATAL ERROR:
Object reference not set to an instance of an object.
at DaxStudio.CheckerApp.Checker.CheckRegistrySettings()
at DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

That's actually just a bug in the Checker app if the DAX Studio registry key does not exist (which it won't if you can't run it)

Can you follow the instructions [here](https://daxstudio.org/documentation/troubleshooting/logging-settings/) holding down the SHIFT key while trying to start DAX Studio - this should generate a diagnostic log file. 

Then open a Windows Explorer window and paste the following into the address bar ```%localappdata%\DaxStudio``` and hit the enter key can you see a "Log" folder? If so and there are some log files in there can you upload the log file with the most recent time stamp to this issue on github? (don't attach it to an email reply as Github strips out all attachments from emails)

**Comment by monicaenders** [comment]
Hello Darren, I was able to get a log file from holding the shift key like you suggested.  Attached is the [file.s](url)

[Log-20200206 - Copy.txt](https://github.com/DaxStudio/DaxStudio/files/4167956/Log-20200206.-.Copy.txt)

**Comment by monicaenders** [comment]
I also updated the registry using the instructions in the link provided.]

**Comment by dgosbell** [comment]
That log file appears to be from an old beta release from last year (v2.9.5) 

Can you try downloading and installing the current version (v2.10.2)

**Comment by monicaenders** [comment]
Oh, yes. Apologies.l  had installed that version as a troubleshooting mechanism to see if this error existed in previous versions. Attached is using updated .exe
[DaxStudio-0206-20200206.txt](https://github.com/DaxStudio/DaxStudio/files/4168056/DaxStudio-0206-20200206.txt)

**Comment by dgosbell** [comment]
Hmm, there are no signs of a crash in that log file. This could indicate an issue where the .Net framework is unable to load an external dependency that we require.

Do you see any error message or a anything or does the splash screen just display briefly then go away?

If you enabled the registry key under the **Startup Logging** section in the link I posted, that will have created a separate set of logs in the folder you specified in the ```LogPath``` setting. Can you zip up those files and upload them here. I've just double checked by installing 2.10.2 on a fresh machine and it worked fine there.

**Comment by monicaenders** [comment]
There are no error messages that popup. Just first a transparent splash icon, and then the icon like I have attached.
I did enable the registry as well. Attached is a .zip file with the files.

[tmp.zip](https://github.com/DaxStudio/DaxStudio/files/4168180/tmp.zip)

**Comment by monicaenders** [comment]
Here is another version that I ran to get the logging files.
[tmp2.zip](https://github.com/DaxStudio/DaxStudio/files/4168673/tmp2.zip)

**Comment by dgosbell** [comment]
OK, so this is not a fusion based issue as those **Startup** logs show nothing related to DAX Studio. So you should turn off that setting as it captures assembly load issues from all .net based applications.

However this still does not get us any closer to solving your issue. 

Can you open the Windows "Event Viewer" (you can search in the start menu for this) and check the application section for any errors relating to DAX Studio? Maybe try starting DAX Studio then go into the event view so that any new events will be right at the top of the list. If you can see any errors relating to the crash can you post the details?

Otherwise maybe try uninstalling and then deleting the **DAX Studio** folder under ```c:\program files\``` and the **DaxStudio** folder under ```%localappdata%``` and try installing again.

**Comment by monicaenders** [comment]
Hello Darren.
I searched the event viewer after starting daxstudio and there was absolutely nothing tagged or looked out of ordinary in the application log.
I have gone through this process multiple times:
Uninstall DaxStudio -> remove program files\daxstudio directory -> remove any reference to daxstudio in the registry -> reboot pc -> reinstall daxstudio.

**Comment by monicaenders** [comment]
Are there certain versions of the .net framework that are not compatible?

**Comment by dgosbell** [comment]
> Are there certain versions of the .net framework that are not compatible?

No, as long as you are running 4.7.1 or later there should be no issues (an the installer will check for this). And the fact that the diagnostic logging starts up and is recording log events means that the .net framework was able to start running the app. 

I've been doing some research and I may have found a way that unhandled crashes could slip past the error logging so I'll see if I can code in a fix for that and then send you a link to a preview build in the next few days.

**Comment by monicaenders** [comment]
Thank you Darren, 
I am running .NET Framework 4.7.02053.  
Should I upgrade to 4.7.1?

**Comment by monicaenders** [comment]
Update:
I uninstalled all the .net framework sdk's  and now it is working.
I had the .net core sdk as well as the framework sdks.  I removed them all.

**Comment by dgosbell** [comment]
Thanks for the update. The installer _should_ check the .Net framework and download and install 4.7.1 if you don't have it, I'm not sure what went wrong there. Having the other versions should not cause and issue, I have .Net core and a bunch of different SDK versions on my machine.

The way they do versioning of the .Net Frameworks is very complicated, I'm updating the code in the Checker app to not just print the raw information but to also translate that into the well known numbers (eg 4.7.0 / 4.7.1 / 4.7.2 etc) and print a warning if the version is too low so that hopefully I can catch any future issue like this faster in future.
