### ISSUE TITLE
Measures formatted in PowerBI are not formatted in DAX Studio

### ISSUE THREAD

**Issue by dimbroane** [DaxStudio/DaxStudio#287]
Hello

All the measures created in Power BI (as a source for DAX Studio) are formatted as numeric, digital (two digits with comma separator).
However, on writing code in Dax Studio - using these measures - the result is not formatted at all.
Could you please look into this? It's annoying.

Kind regards

Doru Imbroane

![DAXStudio](https://user-images.githubusercontent.com/29808068/73983587-a2e69380-499b-11ea-8dfe-0be87c61f307.PNG)
![PowerBI](https://user-images.githubusercontent.com/29808068/73983591-a37f2a00-499b-11ea-8db8-cda4ab2e6d8d.PNG)

**Comment by dgosbell** [comment]
The issue here is most likely line 8 in your query

```"Total Sales", [Sales Amount]```

By renaming the measure inside the query you've broken the link to the format string (DAX queries always return unformatted numbers and rely on the client tools to apply the format string)

If you change this line to 

```"SalesAmount", [Sales Amount]```

You should then find that we can match up the measure with it's format string and the results should be formatted appropriately.

**Comment by dgosbell** [comment]
@dimbroane did changing the measure names in your query resolve this issue?

**Comment by dimbroane** [comment]
Hello Darren, I am sorry for the late reply.
No, it was a change in settings that did the trick. Now everything works as expected.
