### ISSUE TITLE
Vertipaq Analyzer Preview bug

### ISSUE THREAD

**Issue by KavasiMihaly** [DaxStudio/DaxStudio#302]
Hi, 
I found 2 bugs with Vertipaq Analyzer View Metrics
- You cannot use the **table** column to sort. No highlighting happens when you mouse over.
- if you reorder the columns just the headers move but the data stays
![image](https://user-images.githubusercontent.com/23135061/77797779-91e80380-7069-11ea-8db3-ab29b690e363.png)

Best regards,
Mihaly

**Comment by KavasiMihaly** [comment]
> Hi,
> I found 2 bugs with Vertipaq Analyzer View Metrics
> 
> * You cannot use the **table** column to sort. No highlighting happens when you mouse over.
> * if you reorder the columns just the headers move but the data stays
>   ![image](https://user-images.githubusercontent.com/23135061/77797779-91e80380-7069-11ea-8db3-ab29b690e363.png)
> 
> Best regards,
> Mihaly

Version 2.10.1

**Comment by dgosbell** [comment]
> You cannot use the table column to sort. No highlighting happens when you mouse over.

Yes, this is by design as the sorting actually happens at the detail level and if you expand the table you will see that there is no data at the column level. So you cannot sort by Table Size, RI Violations, Hierarchy Size or Relationships size as these items are stored at the table level

> if you reorder the columns just the headers move but the data stays

This is a bug, so I've disabled the column re-ordering. It does not appear to be possible to support both the expand/collapse and column re-ordering at the same time.
