### ISSUE TITLE
After set Format String Expression of Calculation Item hides metadata in DAX Studio

### ISSUE THREAD

**Issue by jorgemlesteves** [DaxStudio/DaxStudio#303]
I had already reported this to Daniel Otykier(Tabular Editor) but since I don't know the source of the problem I ended up reporting also here.

Setting in Tabular Editor an expression ("0.00%", as an example) in the Format String Expression of a Calculation Item (from any Calculation Group) **hides**, in **DAX Studio** , any metadata information from tables that have measures defined. 

![image](https://user-images.githubusercontent.com/31868867/78179962-f89a6200-7459-11ea-97c3-40e5d8a55d5f.png)

![image](https://user-images.githubusercontent.com/31868867/78180111-313a3b80-745a-11ea-81fe-563bc8f5b3b4.png)

Could it be from JSON (model.bim) generated by the Tabular Editor?

**Comment by dgosbell** [comment]
Thanks for logging this. It's definitely a DAX Studio bug, nothing to do with Tabular Editor. The issue is that the formatstring expressions generate hidden measures with the same caption. 

![image](https://user-images.githubusercontent.com/8241830/78230432-0bc23600-751d-11ea-8ae2-5df177d0211c.png)

I have a fix for this in the current preview build [here](https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/31900999/artifacts) if you want to try testing this yourself. But I'd also like to push out a proper release for this in the next week or so once I address a few other things I have in flight at the moment.

**Comment by jorgemlesteves** [comment]
I already tested the fix you pointed and I'm waiting now for the next release.

![image](https://user-images.githubusercontent.com/31868867/78309754-cc5b1000-7543-11ea-86dc-29faf8418d0e.png)

Thanks a lot, Darren!
