### ISSUE TITLE
Can we have New query option as an icon

### ISSUE THREAD

**Issue by snama2020** [DaxStudio/DaxStudio#314]
Hi, I didn't know that we can do multiple query tabs using File -> New (or CTRL + N) without some research. Can we have this option as an icon on the main menu itself so that it is easy to use ? BTW, this is an excellent feature even otherwise, especially the CTRL + SHIFT + N hotkey.

Thanks,
SN

**Comment by dgosbell** [comment]
Actually I've been trying to get something like this to work for ages now. But what I really want to do is to get these common functions "pinned" in the "quick access" area so that they are available globally. 
![image](https://user-images.githubusercontent.com/8241830/79701871-da4eb600-82e3-11ea-8097-4d9320901c7c.png)
The good news is that I had go at this over the weekend and I think I figured out a work around. So I'm going to do a bit more testing and if everything goes well this will be in the next release.

**Comment by snama2020** [comment]
That's even better. Can't wait to see this...
