### ISSUE TITLE
Referring a different model

### ISSUE THREAD

**Issue by snama2020** [DaxStudio/DaxStudio#315]
I was wondering whether we can reference a different model something like we do in SSMS using schema/db reference using "." ex. SELECT * from dbo.dim_Employee.

Thanks,
SN

**Comment by dgosbell** [comment]
You cannot do anything like this in DAX as the tabular engine (written by Microsoft) does not support it. 

I can't see them ever supporting this sort of construct in the query language, but at the model level they are looking to add the ability to create composite models over 2 or more data models ( see [https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave1/business-intelligence/composite-models-over-power-bi-azure-analysis-services-datasets](https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave1/business-intelligence/composite-models-over-power-bi-azure-analysis-services-datasets) ) This makes more sense in the tabular modelling scenario since any joins are done in the modelling layer so that the end users can just drag and drop.
