### ISSUE TITLE
Import TabularModel to Excel through bim File or SSAS-Connection

### ISSUE THREAD

**Issue by openStove** [DaxStudio/DaxStudio#317]
I'm currently no more developping Tabular Models over Visual Studio anymore...
I use Tabular Editor, but for CalculatedColumns and Measures, it is nice to see directly the result on the Data...

The Extension you wrote, is able to connect to a PowerPivot model, I wonder, if it could be possible to somehow import a Bim file to Excel through the plugin ?

If you have some hints, maybe I'm able to start such a work by myself...

**Comment by marcosqlbi** [comment]
Excel Power Pivot uses a former version of the description of the model that is incompatible with the TOM API. The internal representation stores data in XML instead of JSON. Hopefully, in a future version of Excel they will update the internal engine, but this is unlikely to happen because it would break the compatibility of XLSX files between different Excel versions.

**Comment by dgosbell** [comment]
No, this is not possible. I have tried using the older AMO API (which does work with the XML format) to alter PowerPivot models, but even the smallest change crashes Excel is a spectacular way leaving you with a corrupt excel file that you can no longer open.

 I think from memory (as this was 6-7 years ago) I was able to _maybe_ edit the FormatString property, but any changes to an DAX expressions would corrupt the file and crash Excel.
