### ISSUE TITLE
Copy Database GUID from Query History

### ISSUE THREAD

**Issue by micwebnet** [DaxStudio/DaxStudio#321]
**Is your feature request related to a problem? Please describe.**
When pulling data from one PBIX to another both localhost port and database GUID change. I open DAX Studio to find out both, but it doesn't let me copy either. Port is easy enough to copy, but GUID is HARD! Why not just make them copy/pastable so I don't have to create mock AS connections every time I need to get to the new GUID?

**Describe the solution you'd like**
Add copy/paste for columns in Query History pane

**Describe alternatives you've considered**
What I do right now is create a mock Analysis Services Get Data once I find the local port from DAX Studio, cause I don't trust myself typing in the GUID through observation.

**Additional context**
![image](https://user-images.githubusercontent.com/29300459/80937493-3573b480-8d8a-11ea-93cf-aa7046e096cb.png)

**Comment by dgosbell** [comment]
These items both already have options for copying them.

The server/port details you can copy using the icon in the status bar
![image](https://user-images.githubusercontent.com/8241830/80938766-b0d27600-8e1d-11ea-90ca-3e5843541e0e.png)

And the database GUID you can copy by right clicking on the database name in the metadata pane
![image](https://user-images.githubusercontent.com/8241830/80938734-8c769980-8e1d-11ea-899a-b48b2dc6ef19.png)

**Comment by micwebnet** [comment]
I can confirm that both copies work and while server/port is moderately discoverable, right click on the DB to produce GUID is completely not discoverable. 😊 Sent from Mail for Windows 10 From: Darren GosbellSent: Sunday, May 3, 2020 10:42 PMTo: DaxStudio/DaxStudioCc: micwebnet; AuthorSubject: Re: [DaxStudio/DaxStudio] Copy Database GUID from Query History (#321) These items both already have options for copying them.The server/port details you can copy using the icon in the status barAnd the database GUID you can copy by right clicking on the database name in the metadata pane—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dgosbell** [comment]
>right click on the DB to produce GUID is completely not discoverable. 😊

Yep, I agree - I just figured this would get you a solution that will work now on the current release. 

I've just added a note to the database tooltip to help with this, but again you need to know that the id is in the tooltip. I actually go to extra effort to show the pbix file name instead of the guid in the database dropdown since the guid is generally meaningless to most people. 
![image](https://user-images.githubusercontent.com/8241830/80942573-74f0de00-8e28-11ea-9b49-12f51d3e32ca.png)

I can look at fixing the copying on the Query History, but I'm not sure if that is very discoverable either and it requires having run a query in order for there to be anything to copy. 

You can also run `SELECT * FROM $SYSTEM.DBSCHEMA_CATALOGS` to get the schema, but again, not at all discoverable.

So there are various ways of getting this information, but discoverability is an issue and I'm not sure how to make this better. But at the same time I don't believe that pulling from one Power BI model into another is something that a lot of people do regularly.

**Comment by micwebnet** [comment]
Pulling from one PBI to another is a quick inner loop solution to having to stand up proper SSAS. Unfortunately PBI Desktop keeps recycling the database GUIDs, but otherwise it works as expected. 

I think the advisory text in the tooltip is a good step forward! Maybe also surface the database name:guid in the status bar with a similar copy/paste icon that you have for server:port?

Best,  Michael

**Comment by dgosbell** [comment]
So, both the extra note about right-clicking on the database dropdown, plus the ability to copy a guid from the Query History pane are now released as part of v2.11.0
