### ISSUE TITLE
IN operator is missing

### ISSUE THREAD

**Issue by AstroBernal** [DaxStudio/DaxStudio#326]
The IN operators shows in green as text, and not in blue as an operator

I recognize that the issue I am dealing with might not be specific to Dax Studio, but maybe any of you can please help us by pointing us in the right direction

We cannot get the IN or CONTAINSROW operators to show up in neither Dax Studio, power BI or the Visual Studio Tabular solution.  Any ideas would be greatly appreciated

**Comment by marcosqlbi** [comment]
This should be already fixed in the development branch, so you should see it working in the next release.

**Comment by dgosbell** [comment]
So as Marco mentioned we've already got some coloring changes coming in the next release.

>We cannot get the IN or CONTAINSROW operators to show up in neither Dax Studio, power BI or the Visual Studio Tabular solution. Any ideas would be greatly appreciated

I'm not quite sure what you mean here by "show up" are you talking about the intellisense? Technically IN is an operator and we don't add operators (eg, + - * / = > < IN etc) to the intellisense dropdowns. 

And CONTAINSROW is a function and it depends on what version of the tabular engine you are connecting to. You need a recent version of Power BI or SSAS 2016 or later. If you are connecting to an older version of SSAS it will not have support for CONTAINSROW

**Comment by AstroBernal** [comment]
> This should be already fixed in the development branch, so you should see it working in the next release.

Thank you Marco... any estimated time frames around when the next DaxStudio release might be available?

**Comment by AstroBernal** [comment]
> So as Marco mentioned we've already got some coloring changes coming in the next release.
> 
> We cannot get the IN or CONTAINSROW operators to show up in neither Dax Studio, power BI or the Visual Studio Tabular solution. Any ideas would be greatly appreciated
> 
> I'm not quite sure what you mean here by "show up" are you talking about the intellisense? Technically IN is an operator and we don't add operators (eg, + - * / = > < IN etc) to the intellisense dropdowns.
> And CONTAINSROW is a function and it depends on what version of the tabular engine you are connecting to. You need a recent version of Power BI or SSAS 2016 or later. If you are connecting to an older version of SSAS it will not have support for CONTAINSROW

Thank you @dgosbell... Couple of things.. Turns out our SSAS servers had recently been upgraded to Enterprise, but to an older version from 2016 and that version doesn't have support for functions like COUNTROWS.  We just got our SSAS servers upgraded again, but to Enterprise 2019 and we are now able to use COUNTROWS and IN functions in our formulas on SSAS cubes and power BI, except for DAX Studio

To your first point, I wasn't referring to showing up in intellisense.  I recognize I wasn't clear.. that's on me.  What I meant is that functions such COUNTROWS and IN are not even coming up as functions available for us to use in our formulas.. ex: categoryID IN {1,2,3}  If that is what is being introduced in the next DAX Studio release, that is awesome.. is that the case?

**Comment by dgosbell** [comment]
> What I meant is that functions such COUNTROWS and IN are not even coming up as functions available for us to use in our formulas.. ex: categoryID IN {1,2,3} If that is what is being introduced in the next DAX Studio release, that is awesome.. is that the case?

In your first post you said these functions are not "showing up", now you say they are not "coming up" - that seems like the same thing to me so I'm still no closer to understanding what your issue is. 

Are you possibly getting an error message of some sort? If so can you post the text of the message? 

Can you also post an example of the types of queries that are not working? Maybe you just have a syntax error in your queries.

**Comment by AstroBernal** [comment]
@dgosbell thx, But Marco understood it without the back and forth and he mentioned that those functions will be available in the next version of DaxStudio.

As far as those functions being available in the SSAS, as I mentioned, that was addressed by upgrading SSAS to a newer version

**Comment by dgosbell** [comment]
> But Marco understood it without the back and forth and he mentioned that those functions will be available in the next version of DaxStudio.

@AstroBernal  In Marco's answer he was **only** talking about the fact that the color of the IN operator is fixed (in fact we've done a major change to the coloring to align with DaxFormatter.com and Tabular Editor) 

We don't implement DAX functions inside DAX Studio we pass them on to the Microsoft engine for execution. So if whatever you are doing now is not working it's not going to change in the next release. 

I'm only asking these questions because I'm worried that there is some other issue unrelated to the syntax highlighting. You talking about these functions being "unavailable" but you have not explained what you mean by that and the coloring is not related in any way to the ability to execute these functions.

**Comment by AstroBernal** [comment]
@dgosbell The functions started to work fine after we upgraded the SSAS tabular engine from 2016 to 2019, this week. The only caveat is that Dax Studio is still not highlighting the functions in blue (they are highlighted in green), but the functions are now working as expected.  You were right with your original comment around the version of the tabular engine.

I look forward to the next release of DaxStudio.. any estimates on when it would be available?

Have a great weekend!
