### ISSUE TITLE
Cannot see what server I am connected to

### ISSUE THREAD

**Issue by o-o00o-o** [DaxStudio/DaxStudio#332]
**Describe the bug**
The UI doesn't tell me what server I'm connected to when in AAS. The area in the status bar is too narrow for any AAS service

**To Reproduce**
Connect to an AAS host (something like asazure://westeurope.asazure.windows.net/myservername
Notice that nowhere will tell you what server you can connect to
Not even a tooltip if you hover over the server (it just says "Server Name")

**Expected behavior**
I should be able to see what server address I'm connected to by just looking at the status bar. a normal length AAS address should be totally visible with some room to spare. If the address really is too long for the status bar real-estate then a tooltip should show the full address

**Screenshots**
![image](https://user-images.githubusercontent.com/13693159/82309096-97533180-99ba-11ea-9338-c7c6f212d09f.png)

**Additional context**
I can see that there is a copy server address icon on the toolbar, does anyone actually use this? Seems a bit unconventional and unnecessary, we have recent connections in our new connection (where they should be) and somehow we got the address in, in the first place? This is taking up a small amount of valuable status bar space for something that I'm willing to bet is used hardly ever and out of those, most are probably accidental or clicking to see what it does, so please consider removing it to release the space.

**Comment by marcosqlbi** [comment]
The copy button is very useful to reuse the connection string in other applications (e.g. Power BI itself to connect to another PBIX file on your desktop).
I agree that we should figure out a way to display the complete name without having to do copy/paste, though!

**Comment by o-o00o-o** [comment]
I'm sure it is useful if you need it often and know it is there, but I don't know any other tool that behaves like this so it just doesn't feel very intuitive. Perhaps I'm thinking that this is a little bit like fire exits. Intuitively people go back through the door that they came in - even if they have a big flashing sign telling them something different. So in this case if I wanted to get the servername that I already used to connect in DAXStudio, I would go to the same place I got it from to put it into dax studio, rather than thinking that somewhere else in DAXStudio I can get this information into my clipboard. 

Anyway, my point isn't that the copy is never useful or rarely used, but more that that space on the status bar is precious, so shouldn't be used for static icons, it should be used for dynamic status of the current context and a static icon doesn't meet that test.

So as the copy is useful, how about instead of having a static  icon on the status bar, instead make it a click/double click on the server name copy to clipboard and perhaps add a note on a tooltip to tell people that this is what will happen,

e.g. tooltip says

> asazure://westeurope.asazure.windows.net/myreallyreallyreallyreallyreallyreallylongservername
>
> (double-click server name to copy this to clipboard)

This way those that need this still have it and we free 3 or 4 characters for more useful information on the status?

**Comment by marcosqlbi** [comment]
The real reason to use that "copy" button is when you connect to Power BI Desktop or to SSDT integrated workspace. In those cases, DAX Studio finds the connection port and you did not enter it.
I get your point about long names, let's see what Darren says about that.

**Comment by dgosbell** [comment]
I don't think removing the copy icon is the solution and it's something I use frequently (and we get a lot of positive feedback on) so I have no intention of removing it.

And in your example your server name would go from: 
> asazure://westeurope.asazur

to something like:
> asazure://westeurope.asazure.wi

Which does not really provide any further useful information

However I had already started looking at this and I've been looking at a number of improvements already in this area including:
1. Fixing the tooltip to display the full name
2. Increasing the allowed size for the server name region in the status bar
3. Applying more intelligent trimming 

On this third point instead of just cropping off the end of the server name I want to keep the last portion of the name for both powerbi:// and asazure:// connections.

so the following:
> asazure://westeurope.asazure.windows.net/myreallyreallyreallyreallyreallyreallylongservername

would become:
> asazure://.../myreallyreallyreallyreallyreallyreallylongservername

My theory is that most people probably don't have servers with the same name in multiple regions so the really important part of the uri is the last bit which has the server name or workspace name.

![image](https://user-images.githubusercontent.com/8241830/82385418-6c79e380-9a75-11ea-8eba-ccf5f24ae92a.png)
So the above is a connection to the read/write endpoint of my dev2 instance

**Comment by dgosbell** [comment]
v2.11.0 has just been released which includes the enhancements to the statusbar pictured above
