### ISSUE TITLE
Query Batch Completed with error with no details.

### ISSUE THREAD

**Issue by sukhomoyb** [DaxStudio/DaxStudio#334]
**Describe the bug**
Input : select * from $SYSTEM.MDSCHEMA_MEASURES where MEASURE_IS_VISIBLE = True
Output: Query Batch Completed with error;  

No description of the error. 

**Expected behavior**
There should not have any error. However, should be in detail if there is any syntax error.

**Comment by dgosbell** [comment]
What sort of data source are you connected to? Did you try scrolling the output pane up as I get an error message running against SSAS 2017

![image](https://user-images.githubusercontent.com/8241830/82381528-b5c63500-9a6d-11ea-884b-710a8b2f7b23.png)

The issue is that your syntax is not valid. The $SYSTEM DMV queries use a language called DMX and it does not support equality comparisons.  To filter using a boolean column in a DMX query you just put the column name.

eg
```select * from $SYSTEM.MDSCHEMA_MEASURES where MEASURE_IS_VISIBLE```

**Comment by sukhomoyb** [comment]
Hi dgosbell,
Thanks for your prompt reply.
I am working on Power BI Desktop Edition Apr2020. And data source for Power BI is multiple excel Tables. 
Cheers.

**Comment by dgosbell** [comment]
I can't reproduce this. I've already updated to Power BI May 2020 but I still get the detailed error message in addition to the "Query Batch completed with errors" message. And I get the same behaviour on older versions of the engine like SSAS 2017 and SSAS 2019.

So could you see another error by scrolling up on the output pane?

Did the valid query I posted earlier work?

Can you post a screenshot like the one I posted show the "Query Started" event and any following messages?

**Comment by dgosbell** [comment]
Closing due to lack of response. if you have further information to add feel free to re-open this
