### ISSUE TITLE
Azure Data Studio Extension for DaxStudio

### ISSUE THREAD

**Issue by isaac-gritz** [DaxStudio/DaxStudio#336]
Azure Data Studio (https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-ver15) is a great tool for working with SQL Server and Azure SQL and is built on top of VS Code and has Intelliense and a lot of extensions. However, it doesn't have any capabilities for interacting with SSAS/AAS cubes like DaxStudio. A DaxStudio plugin for Azure Data Studio would be the best of both worlds.

**Comment by isaac-gritz** [comment]
This is a huge unopened request that people have of the Azure Data Studio tool that can be filled: https://github.com/microsoft/azuredatastudio/issues/1026

**Comment by marcosqlbi** [comment]
It's a lot of work - and the first issue is that we don't have any connection library that can be used for JavaScript. As of today, one should rewrite the entire communication stack starting from XMLA. I'd say it's just too much work to do at the moment.

**Comment by dgosbell** [comment]
Since this is not strictly something we would add to DAX Studio I'm going to close this issue. Azure Data Studio is a Microsoft product, if they could add the basic connectivity to SSAS/AAS we might look at contributing some extensions, but at the moment, building an XMLA provider in javascript from scratch would be a lot of work.
