### ISSUE TITLE
Hierarchies not showing in Dax Studio

### ISSUE THREAD

**Issue by gooranga** [DaxStudio/DaxStudio#352]
Hi,

I am pretty new to Dax studio and have just migrated our first olap cube into tabular and this tool is amazing!

One thing I have noticed is my hierarchies have a yellow exclamation mark against them. I can see the hierarchy if it's not in a folder but if its in a folder I can only see the hierarchy name and can't drag an item into a query but queries run ok referencing items in the hierarchy . Not sure if it's something I have set up wrong in the tabular model or not.

Also see some yellow warnings.

![image](https://user-images.githubusercontent.com/18531348/84552155-ba49da80-ad07-11ea-94fa-6b8392de2f4a.png)

If they are not in a folder I still get the warning but I can see the levels.

![image](https://user-images.githubusercontent.com/18531348/84552195-dd748a00-ad07-11ea-9a00-ac02b54344f5.png)

I am also getting some warnings when connecting.

![image](https://user-images.githubusercontent.com/18531348/84552239-0432c080-ad08-11ea-9056-7b53f1763f07.png)

I am pretty new to tabular so it's probable a user error rather than a bug. I am using 2.11.0 of Dax Studio and the Tabular model is on SQL 2019.

**Comment by dgosbell** [comment]
Thanks for reporting this. The hierarchies not expanding when in a display folder is definitely a bug. I don't think I have any hierarchies in folders and no one else has reported this before. I'm working on a fix that should be in the next point release

The yellow triangles on the hierarchies is because they are probably unnatural hierarchies (see [https://www.sqlbi.com/articles/natural-hierarchies-in-power-pivot-and-tabular/](https://www.sqlbi.com/articles/natural-hierarchies-in-power-pivot-and-tabular/)) this can have an impact on performance, but is mainly an issue for MDX clients like Excel. The performance of unnatural hierarchies in Power BI is not really an issue.

I'm not entirely sure what is causing the object reference not set error. Are you able to replicate that on your system? If so could you try starting DAX Studio with the [diagnostic logging enabled](https://daxstudio.org/documentation/troubleshooting/logging-settings/) then replicate the issue and upload the log file to this issue on Github.

**Comment by gooranga** [comment]
Thanks for the speedy response, I see hierarchies are quite different to olap, I will amend mine for Excel use I think after reading that article.

It looks like the error was caused by connecting to the model that had changes deployed but hadn't been processed as it isn't showing anymore after overnight processes.

Thanks again for th ehelp and the excellent DAX studio!
