### ISSUE TITLE
Symantec and windows defender show Dax Studio 2.11 as a malware

### ISSUE THREAD

**Issue by cosmenizzo** [DaxStudio/DaxStudio#355]
Hello, I tried to update to 2.11 version but Symantec and windows defender think it is a malware. 
 Is it ok to proceed anyway?

![image](https://user-images.githubusercontent.com/32939249/84784775-155a2680-afc1-11ea-80f8-db51074191a6.png)

Thank you

**Comment by dgosbell** [comment]
I don't have access to symantic so I can't really comment on that, but I can't see any indication of malware in that message, it just says "inconclusive" and a new file. If I check at virustotal.com the 2.11.0 version shows as 100% clear see - [https://www.virustotal.com/gui/url/a0426d94fd35d4fb7380dd3429a28da4178c9b205fefca529d19f42df5679393/detection](https://www.virustotal.com/gui/url/a0426d94fd35d4fb7380dd3429a28da4178c9b205fefca529d19f42df5679393/detection)

If by Windows Defender you are talking about the Smart Screen feature at the moment we just have [documentation](https://daxstudio.org/documentation/installation/smart-screen/) about that. I'm doing my best to improve this experience, but because DAX Studio is not produced by a "company" it's difficult to get it recognised.

**Comment by dgosbell** [comment]
The new 2.12 release is now live with a new EV certificate which should prevent these warnings

**Comment by JohnTJennings** [comment]
I have a programmer that is looking to install Dax Studio and i found some issues i want to make sure the information i got is a false positive? But for now i won't be able to install it.
https://www.hybrid-analysis.com/sample/e8370999cd63ac8a220d1946f913968d51c33f2d6ab315cf77cc0b4c42d8feda/5f20524ac1253a457d21e280

If you could help me with that i can make sure that we can get this resolved for the programmer. 
Thank you

**Comment by dgosbell** [comment]
@JohnTJennings  We use InnoSetup to script our installer and most of the issues in that link appear to be related to the way the installer works. 

When I check the installer on VirusTotal it comes back with 0 detections so I think this is a false positive, but you really have to judge that for yourself.
[https://www.virustotal.com/gui/url/2f6acace40bbbed2b145c52734adf00258bd7da6035e72fbf982909c76b0dc7a/detection](https://www.virustotal.com/gui/url/2f6acace40bbbed2b145c52734adf00258bd7da6035e72fbf982909c76b0dc7a/detection)

And we do all our builds on AppVeyor build servers to try an minimize the chance of there being any malicious software on the build host.

If you don't need the Excel add-in or the Power BI External tools feature you could always just try the portable version.
