### ISSUE TITLE
Unused measures

### ISSUE THREAD

**Issue by stobbea** [DaxStudio/DaxStudio#359]
Just an idea that I think that would be very popular - ability to look at unused measures. When reviewing the work of others, or even our own work after models have been around for a while, we end up with measures we don't need anymore cluttering things up, and potentially causing data accuracy issues if old measures are not maintained and inadvertently used. 

When searching for a way to identify these - I came across a great article that breaks this down into:
1. What are all the measures
2. What measures are used in the visuals
3. What measures depend on other measures

If you can start with 1 and subtract 2 and 3 you end up with the answer - as laid out here: https://ssbi-blog.de/blog/technical-topics-english/how-to-identify-measures-not-used-in-your-pbix-file/

1 and 3 already come from DaxStudio - it would be great to have a feature available to do that matching!

**Comment by marcosqlbi** [comment]
The reason I don't like this approach is that it cannot evaluate whether a measure is used by other reports. It only works for measures used in a local PBIX file. The assumption you should make is that any visible measure could be potentially used by other reports.
I am interested in solving the bigger problem - scanning the reports in existing workspaces, getting the referenced measures and describe a references graph. But this is very complex, because you might have local measures in reports that are not exposes by any of the reports metadata structures.
I am worried that such a feature could be used the wrong way, breaking existing reports and losing the measures that have been removed (not everyone keeps track of model versions and Power BI doesn't provide a service to do that).

**Comment by dgosbell** [comment]
I agree with @marcosqlbi I think this feature is potentially dangerous as it's not safe to assume that the current report is the only thing referencing a given data model. 

With the ability to create reports linked to the data model of another report and with the newly announced [composite model feature over Power BI data sets](https://docs.microsoft.com/en-us/power-platform-release-plan/2020wave1/business-intelligence/composite-models-over-power-bi-azure-analysis-services-datasets) that will be coming later this year you can have data models over other data models.

What's really needed is some tool that can scan an entire Power BI tenant and trace the usage network, but I think that this is well beyond the scope of DAX Studio at the moment.

So while I really appreciate the suggestion and I think the concept is something that would be of value I don't think it's a good fit for DAX Studio at this point in time, so I hope you don't mind but I'm going to close this issue.

**Comment by stobbea** [comment]
That's fair, thanks for your consideration.
