### ISSUE TITLE
Absence of "Linked" Excel file among the Output options

### ISSUE THREAD

**Issue by afantini-afk** [DaxStudio/DaxStudio#371]
Hello,

I installed DAX Studio with the Excel add-in included, but when I open DAX STUDIO from Excel among the Excel outputs, only the "static" Excel file option appears, while the "Linked" Excel file option does not show up. 

Steps:
1. I open DAX Studio from the Add-in in an empty Excel file
2. I connect with my PowerBI report
3. I select the Output but among the Excel I can only find "Static" I do not see the "Linked" Excel file as output.

Why I do not see the option?

Thank you for the help you will be able to provide,

Agnese

**Comment by dgosbell** [comment]
This is by design as per the note here [https://daxstudio.org/documentation/features/excel-linked-results/](https://daxstudio.org/documentation/features/excel-linked-results/) since the port for Power BI Desktop is randomized every time it starts up the "link" would be broken as soon as you close the Power BI Desktop file so it makes no sense to use this output with Power BI Desktop so we do no show it as an option.
