### ISSUE TITLE
TOPNSKIP not recognized by intellisense

### ISSUE THREAD

**Issue by awbarbeau** [DaxStudio/DaxStudio#374]
Hi,
In 2.11.2, the TOPNSKIP function is not recognized by intellisense. The function is colored orange similar to integer values, and the DAX Guide prompts don't appear.

`EVALUATE
TOPNSKIP ( 10, 500, 'Table' )`
In this DAX, TOPNSKIP appears in Orange

vs. 

`EVALUATE
TOPN ( 10, 'Table' )`
In this DAX, TOPN appears in Blue

**Comment by marcosqlbi** [comment]
TOPNSKIP is a function not exposed by the DMV used by DAX Studio. Indeed, if you open DAX Studio without connecting to any database, the function name is recognized because an internal list used when a connection is not available.
@dgosbell we might add TOPNSKIP to the list of functions if the compatibility level is greater than or equal to 1200...

**Comment by dgosbell** [comment]
@marcosqlbi sure we could do something like that. But is it compatibility level (which is a database property) or is it the "server" version that determines support? 

From memory I think this was added in the SSAS 2016 timeframe (so v13), but dax.guide lists it as also working in Excel 2016 (and SSAS 2019 is not listed). However my Excel 2016 reports engine version 11.0.9166.190 and produces 1103 data models and TOPNSKIP is not working. If we can figure out the right conditions I should be able to inject this in without too much trouble.

**Comment by marcosqlbi** [comment]
@dgosbell I fixed DAX Guide so that now TOPNSKIP shows it's compatible with AS2019 and Excel 2019 (latest AS engine version here is 13.0.1700.1054), not with Excel 2016.
Now, if we rely on the compatibility level, it's easy but not accurate.
If we rely on the product version, it's accurate but potentially harder to validate.
Your call, TOPNSKIP is one of the few functions we update manually on DAX Guide but you can assume that newer versions are always compatible.

**Comment by dgosbell** [comment]
So I've had a go at implementing this just checking if the major version number of the engine is 13 or higher. This is a screenshot of it on SSAS 2017. I've just manually copied in the text from dax.guide and appended it to the data from the DMV. We don't refresh the function list when the database changes, so I think the engine version number is more reliable

![image](https://user-images.githubusercontent.com/8241830/87486611-fbbf0400-c67e-11ea-8d49-3064af29f19d.png)

**Comment by marcosqlbi** [comment]
Great - thanks!
