### ISSUE TITLE
How many records can Dax Studio process

### ISSUE THREAD

**Issue by cnederveen** [DaxStudio/DaxStudio#38]
I am loading a 2.5 million records csv file into Excel PowerPivot model. I am selelcting a 2 million records plus subset in DAX Studio writing the output to a csv file but it does not work. I get messages  "the server sent an unrecognizable response" and  "Object reference not set to an instance of an object". Anyone an idea?

**Comment by dgosbell** [comment]
So just for the interface with PowerPivot we currently have a limitation because we are buffering the result and the maximum size of the buffer is 2Gb. We are buffering uncompressed XMLA which results in this buffer filling up at around the 2 million row mark depending a bit on how many columns are included and how wide they are. At this point the result gets truncated and you get the "unrecognizable result" error. We are experimenting with a technique which might allow us to eliminate this intermediate buffer, so we are hoping that this limitation will not exist in the next release.

**Comment by cnederveen** [comment]
Thanks. I guess I have to write some Python code to do this.... :-)

**Comment by dgosbell** [comment]
This limitation has been fixed in the 2.7.2 release
