### ISSUE TITLE
Editing measure expression not working correctly

### ISSUE THREAD

**Issue by FrankFromGermany** [DaxStudio/DaxStudio#380]
**Describe the bug**
The edited measure returns wrong result.

**To Reproduce**
Before editing
// START QUERY BUILDER
EVALUATE
SUMMARIZECOLUMNS(
    DimProductCategory[EnglishProductCategoryName],
    DimProductSubcategory[EnglishProductSubcategoryName],
    DimProduct[EnglishProductName],
    FILTER(KEEPFILTERS(VALUES( DimDate[YearName] )), DimDate[YearName] = "2019"),
    "TotalSales", [TotalSales]
)
// END QUERY BUILDER

After editing
// START QUERY BUILDER
DEFINE
MEASURE Metrics[TotalSales] = **1000 +** SUMX(FactInternetSales,FactInternetSales[OrderQuantity]*FactInternetSales[UnitPrice]*(1-FactInternetSales[UnitPriceDiscountPct]))
EVALUATE
SUMMARIZECOLUMNS(
    DimProductCategory[EnglishProductCategoryName],
    DimProductSubcategory[EnglishProductSubcategoryName],
    DimProduct[EnglishProductName],
    FILTER(KEEPFILTERS(VALUES( DimDate[YearName] )), DimDate[YearName] = "2019"),
    "TotalSales", [TotalSales]
)
// END QUERY BUILDER

**Screenshots**
Before editing
![image](https://user-images.githubusercontent.com/26203785/87937787-a8d9b800-ca95-11ea-8661-dab7f91b0ca6.png)

After editing
![image](https://user-images.githubusercontent.com/26203785/87937056-3f0cde80-ca94-11ea-847c-55cbf0f5fe45.png)

**Comment by dgosbell** [comment]
If you create that same measure in Power BI and add it to a table visual I expect that you would see the same result. As such I do not believe that this is a DAX Studio issue (we also don't evaluate any of the DAX, we send it to the data source for evaluation)

Whenever you add a hard coded static value to a measure you force a value into cells that would normally be filtered out because they return blank because in DAX 1000 + BLANK = 1000
