### ISSUE TITLE
DAX Studio (opened via clicking external tools in PBI) once loses connection when pbi desktop is closed won't reconnect.

### ISSUE THREAD

**Issue by hemant1303** [DaxStudio/DaxStudio#381]
**Describe the bug**
Open DAX studio by clicking on external tools option in Power bi and then close the pbi model. Now re-poen the same desktop file and try to reconnect the dax studio which was opened during earlier instance you will find that dax studio won't reconnect to the pbi model. However if dax studio is opened independently (not via external tools) it will always reconnect to the pbi model no matter how many time pbi desktop file is closed or an active connection between them is lost.  

**To Reproduce**

**Expected behavior**
DAX studio irrespective of the fact whether opened via external tools in pbi or as an independent application should re-connect to the model after connection is lost. 

**Screenshots**
<img width="960" alt="Daxstudio opened via external tools (1) Tryied_Connecting_PBIOption_Failed" src="https://user-images.githubusercontent.com/28951031/88020685-37eddb00-cb3d-11ea-954f-03fe454c69f2.PNG">
<img width="960" alt="Daxstudio opened via external tools (1) Connected" src="https://user-images.githubusercontent.com/28951031/88020687-39b79e80-cb3d-11ea-8ef2-8e07ed97b2fb.PNG">
<img width="959" alt="Daxstudio opened via external tools (1) Connected   Running" src="https://user-images.githubusercontent.com/28951031/88020689-3a503500-cb3d-11ea-8efd-f1db191baeb0.PNG">
<img width="960" alt="Daxstudio opened via external tools (1) PBI_Closed" src="https://user-images.githubusercontent.com/28951031/88020690-3a503500-cb3d-11ea-831a-7c6f188a2251.PNG">
<img width="960" alt="Daxstudio opened via external tools (1) Trying_Reconnect" src="https://user-images.githubusercontent.com/28951031/88020691-3ae8cb80-cb3d-11ea-86dc-8e02ff890f74.PNG">
<img width="960" alt="Daxstudio opened via external tools (1) Tryied_Connecting_Tabularoption_Failed" src="https://user-images.githubusercontent.com/28951031/88020692-3b816200-cb3d-11ea-9f95-f6f467fd8c59.PNG">

**Additional context**

**Comment by dgosbell** [comment]
When you launch any tool from the External Tools ribbon, Power BI Desktop passes through the port that the tabular engine is running on for that file.

If you close and re-open the pbix file the tabular engine will start on a new randomized port.

So if you click on the Connect button to reconnect DAX Studio will try and connect to the initial port number that Power BI Desktop told it to use. You could override this by simply clicking on the "PBI / SSDT Model" option in which case DAX Studio will find the new port for the tabular engine itself. 

I'll have a think about it, but I'm not sure if there is a good solution to automatically reconnecting to a closed then re-opened PBIX file. I could maybe do something to default the connection to the "PBI / SSDT Model" option, but if there is more than one pbix file open the end user would still probably need to make sure they pick the right one.

**Comment by hemant1303** [comment]
Hi Darren,

Thanks for responding. Further, as I have stated in my bug report that i
tried connecting the "PBI/SSDT Model" option too as i knew that dax studio
will connect to the local host port as it used to do to connect a power
pivot model.Somehow using "powerBI/SSDT" option too it is not connecting
back to the pbi model. Did you try creating this scenario at your end?

find some more information.
PBI Version --  2.83.5894.661 64-bit (July 2020)
DAX studio --2.11.2
Windows - 10

Regards,
Hemant

Regards,
Hemant

**Comment by dgosbell** [comment]
> as I have stated in my bug report that i tried connecting the "PBI/SSDT Model" option too

I didn't notice any statement like this and the only screenshot with the Connection dialog shows the "Tabular Server" option selected. 

But I did find something interesting in that the GUID that Power BI Desktop assigns to the database is also randomized at every start up. If you expand the "Advanced Options" in the connection dialog you will see an "Initial Catalog=" setting in the Additional Options which has the previous database id. If you delete this is should allow you to connect when using the "PBI / SSDT Model" option.
![image](https://user-images.githubusercontent.com/8241830/88114788-07b74280-cbf8-11ea-8ab2-3acbbe1c2604.png)


I don't think we actually need the database id to connect anyway since Power BI Desktop only has the one database and DAX Studio will used the first database in the collection if one is not specified. So I might test with removing that parameter as that will make it much simpler to re-connect in the scenario where the pbix file is closed and re-opened.
