### ISSUE TITLE
DAX formatter button issue.

### ISSUE THREAD

**Issue by Oxenskiold-DAX** [DaxStudio/DaxStudio#387]
**Describe the bug**
When you press CRTL and press the DAX formatter button in the ribbon, DAX studio doesn't apply the complement function of the chosen default in the preferences.

If 'Long line' is the default CRTL+F6 will format using 'short line', however, when you just press CRTL and click on the DAX formatter button 'Long line' is still applied. 'Short line should be applied in line with the CRTL+F6 keyboard shortcut logic.

**Expected behavior**
CRTL + mouse click on the DAX formatter button should work the same way as CRTL+F6 on the keyboard.

**Comment by dgosbell** [comment]
In the next release "Format Query" will become a split button ( see #382 ) so that you can trigger the default style from the top half of the button or explicitly choose the formatting style by clicking on the bottom half of the button. I think this will be easier for people to discover than a ctrl-click

**Comment by Oxenskiold-DAX** [comment]
Yes, that solution quite fits the bill. Superb. Thanks.

**Comment by dgosbell** [comment]
The new 2.12 release is now live with this feature added
