### ISSUE TITLE
support connection to DAX Studio using public domain

### ISSUE THREAD

**Issue by joannahe** [DaxStudio/DaxStudio#39]
DAX studio is a great product. It makes Excel DirectQuery many data sources possible.
We would like to provide a solution using DAX Studio as a BI Server to our customer. Analysts using excel can DirectQuery a data source through DAX studio and Power BI. Such solution will need DAX studio as a Remote BI server that analysts can access from Excel using the public domain. However, during our test and by examing the code, we found that DAX Studio only listens on localhost. So it is impossible to access remotely from public domain. 

Is there any special reason for such design? Do you have a plan to support connection using public domain?

**Comment by dgosbell** [comment]
I'm not entirely sure I understand your question. But from trying to read between the lines I'm assuming that you are talking about trying to use DAX Studio to turn Excel into a server to allow multiple other client machines to connect to a single PowerPivot model.

If this assumption correct then this is by design and there are no plans to change this. Opening network connections to other machines would involve a number of significant security risks and challenges. But most significantly our understanding is that doing so would violate the Excel licensing conditions. The official supported way for multiple users to connect to and query a single Excel PowerPivot workbook is to host that workbook on a Sharepoint Farm that is configured for PowerPivot.

The DAX Studio connectivity to PowerPivot is designed as a learning tool to allow a user to connect to a local model in a copy of Excel running on their local machine only.

**Comment by joannahe** [comment]
No, I think you get it wrong. our product is a data source of Power BI Desktop, that user can DirectQuery using Power BI Desktop. Ultimately, we hope excel user can also DirectQuery our product too. The only way we figure out that this can happen is through DAX Studio. 

So  Excel user -> DAX Studio  -> Power BI Desktop -> our product as data source. 
We have verified this is working with condition that DAX, Power BI Desktop and Excel installed on the same machine. 
Just wonder if user can connect the DAX Studio remotely.

**Comment by dgosbell** [comment]
So DAX Studio is a client application, not a server application. It can connect to various data sources like PowerPivot, Power BI Desktop and Analysis Services, but other applications (like Excel) cannot connect to DAX Studio.

For the connectivity to Power BI Desktop it is Power BI Desktop that only listens on localhost, we cannot do anything to change that from the DAX Studio side of things. And even if we could I'm pretty sure that it would violate the license terms for Power BI Desktop. If you want to connect Excel to a Power BI model you need to host that model on powerbi.com. I'm not sure if you can make your data source work with that configuration, but that is pretty much the only option I am aware of at the current point in time.
