### ISSUE TITLE
New 2.7.1 Version crashes while connecting to Power BI Desktop Model

### ISSUE THREAD

**Issue by MahadevVasista** [DaxStudio/DaxStudio#40]
Error Screenshot

![image](https://user-images.githubusercontent.com/35061323/35190348-ec1982f6-fe84-11e7-8602-502695df57cb.png)
![image](https://user-images.githubusercontent.com/35061323/35190351-f8f0598c-fe84-11e7-8adb-dc36df1d3cc0.png)

Checking Operating System
=======================
OSCaption       = Microsoft Windows 10 Enterprise
OSVersion       = 10.0.16299
OSArchitecture  = 64-bit
VisibleMemoryGB = 15.88
FreeMemoryGB    = 9.77

Culture Name              = en-IN
Culture DisplayName       = English (India)
Culture EnglishName       = English (India)
Culture 2-Letter ISO Name = en
Culture DecimalSeparator  = .
Culture GroupSeparator    = ,
Culture CurrencySymbol    = ₹
Culture ShortDatePattern  = d-M-yyyy
Checking .Net Framework
=======================
v2.0.50727 -> 2.0.50727.4927
v2.0.50727\1033 -> 2.0.50727.4927
v3.0 -> 3.0.30729.4926
v3.0\Setup -> 3.0.30729.4926
v3.0\Setup\1033 -> 3.0.30729.4926
v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
v3.5 -> 3.5.30729.4926
v3.5\1033 -> 3.5.30729.4926
v4\Client -> 4.7.02556
v4\Client\1033 -> 4.7.02556
v4\Full -> 4.7.02556
v4\Full\1033 -> 4.7.02556
v4.0\Client -> 4.0.0.0

Checking AMO
=======================
PASS > Microsoft.AnalysisServices, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
PASS > Microsoft.AnalysisServices, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Checking ADOMD.NET
=======================
PASS > Microsoft.AnalysisServices.AdomdClient, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
WARN > Could not load file or assembly 'Microsoft.AnalysisServices.AdomdClient, Version=15.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Dax Studio Configuration
========================
Dax Studio registry key not found.

Checking Excel Add-in
=======================
Detected Excel Version: 16 - Excel_v16
Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
Excel Architecture: x86

DAX Studio Excel Add-in Registry keys
   Description: Dax Studio Excel Add-In
   FriendlyName: Dax Studio Excel Add-In
   Manifest: file:///C:/Program Files/DAX Studio/DaxStudio.vsto|vstolocal
   LoadBehavior: 3

Checking for Excel 2010 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2013 Disabled Add-ins
  PASS > No Disabled items found.
Checking for Excel 2016 Disabled Add-ins
  N/A  >  - \\10.116.26.48\dupontcc\concur\amit\script.xl
  N/A  >  - c:\program files\common files\microsoft shared\team foundation server\15.0\x86\tfsofficeadd-in.dll

**Comment by MahadevVasista** [comment]
#

**Comment by dgosbell** [comment]
I think this is probably caused by the mismatch between the maximum version of AMO and ADOMD.NET libraries. Can you find the daxstudio.exe.config file (which should be in "c:\program files\dax studio")? if the file bindings in there are pointing at the v14 libraries then either manually installing ADOMD v14  or re-installing DAX Studio should fix this. (the installer is meant to make sure that both libraries are at the same level)

**Comment by Dieterdde** [comment]
Have the exact same issue, I see you added a commit, when will a new version be available?

**Comment by dgosbell** [comment]
So I have good news and bad news. The good news is that v2.7.2 was just released. The bad news is that the referenced commit was a mistake and it does not appear that GitHub has any way to in-tag an issue.  

@Dieterdde  if you have the same config as this issue (ie. you configured for v14, but missing ADOMD.NET v14 then this is the issue here) the install tries to make sure that the target PC has both AMO and ADOMD at the same version but sometimes it does not work. We don't know why as we have been unable to reproduce this issue, but installing the matching versions of the dependent assemblies should fix this issue. 

Microsoft has just release a new way of deploying AMO/ADOMD in the last few days so in the next release after 2.7.2 we should be able to permanently fix all these dependency issues
