### ISSUE TITLE
Improve View Metrics functionality

### ISSUE THREAD

**Issue by SalCag** [DaxStudio/DaxStudio#403]
I used the View Metrics functionality on a model with 180 tables and I have some ideas.

1. Please add a piece of information, that it's loading the data. At the moment nothing is shown, that the metrics are collected. I have to wait for several minutes, without knowing what's going on, until the metric data is displayed
2. Please allow sorting by all columns. At the moment it's possible to sort only to the data type column on the table tab. To me, it's not clear why it's not possible to sort by the columns on the right of the data type column
3. Please set the default sorting by the Col Size, as this is the most interesting view for the analysis of a model
4. Please add Tooltips for the single column. For example, It would be great to see the difference between the RI Violations in the table tab and the Missing Keys on the Relationships tab.

That's all for the moment.

I hope that these suggestions are helpful to improve this, already great, product.

Thank you to providing this for free. It's extremely valuable.

Best regards
Salvatore

**Comment by dgosbell** [comment]
> 1. Please add a piece of information, that it's loading the data. At the moment nothing is shown, that the metrics are collected. I have to wait for several minutes, without knowing what's going on, until the metric data is displayed

So currently it should show in the status bar that it is loading the metrics, but you are correct that it is inconsistent with the screens which show a loading overlay, so I will correct this so that it does not look like the application is stuck.

> 2. Please allow sorting by all columns. At the moment it's possible to sort only to the data type column on the table tab. To me, it's not clear why it's not possible to sort by the columns on the right of the data type column

I'm not sure if this is possible. Technically the "Tables' is actually 'Columns grouped by Table' so when I sort I'm doing it at the column level, the columns that don't currently support sorting only have data at the table level and are blank at the column level

> 3. Please set the default sorting by the Col Size, as this is the most interesting view for the analysis of a model

This is already set as the default sort the first time you open the View Metrics open. Although I've noticed that if you click the Col Size header twice you seem to get a slightly different sort order where it seems to be taking the total table size into account. I'm not entirely sure why this control is behaving like this, but I'll see if I can figure it out and make it behave consistently.

> 4. Please add Tooltips for the single column. For example, It would be great to see the difference between the RI Violations in the table tab and the Missing Keys on the Relationships tab.

This is a good idea, I will try and go through all the tabs and add tool tips.

In relation to your example those two columns are related, if there is an RI Violation present in the table tab, we show 3 examples of values that have violated the referential integrity (RI) in the missing keys column on the relationships tab.

**Comment by SalCag** [comment]
Thank you for the comments.
I would be happy to see these additions to the tool

**Comment by dgosbell** [comment]
OK, so I've added the loading progress, I figured out how to override the default sort and it now does a nest sort so I've implemented sorting on all columns and I've added tooltips. These updates will be part of the next release

**Comment by SalCag** [comment]
Thank you.
This sounds very good.

Regards
Salvatore
