### ISSUE TITLE
How does DaxStudio fetch the DAX queries executed by Power BI?

### ISSUE THREAD

**Issue by Mudassar045** [DaxStudio/DaxStudio#410]
Sorry, I guess this is not the right way to ask a question but I really want to know how DaxStudio grab the queries executed by Power BI reports. Can anybody help me to understand this?

**Comment by dgosbell** [comment]
Asking a question here is fine. Github does not really have any better alternatives for questions.

I assume you are asking about the "All Queries" trace? Internally Power BI uses an embedded instance of Analysis Services. To capture the queries we use the [AMO](https://docs.microsoft.com/en-us/analysis-services/amo/amo-concepts-and-object-model?view=asallproducts-allversions) library from Microsoft to connect to the Analysis Services instance in Power BI and we then create a trace and subscribe to events that the engine raises. You can also connect using SQL Profiler and capture these same events (and many others).

The source code for DAX Studio is complicated because of some of the work arounds we had to implement to also get tracing working against PowerPivot.  A simpler set of samples is available on the [Analysis Services github repo](https://github.com/microsoft/Analysis-Services) which has a sample called ASTrace which is a service which captures trace events.

**Comment by Mudassar045** [comment]
Yes, asking about `All Queries`. Thanks for the explanation @dgosbell :+1:

**Comment by dgosbell** [comment]
No worries 👍

**Comment by Mudassar045** [comment]
Hi @dgosbell !
I investigated the [Analysis-Services Repo](https://github.com/microsoft/Analysis-Services) and looked into `AsTrace`, all version have the dependency to install `SQL Profiler`. I was also be able to read the code `DaxStudio.QueryTrace`, I've just quick questions:

- Can we use `DaxStudio.QueryTrace` as a reference project to a simple .NET application? (I'm working on a learning project, desktop app which gets the data model from PowerBI using Analysis Services, now interested in tracing events)
- Is there any other way, where we can simply write trace event functionality and consume in the app?
 
I'm beginner, just learning about these stuff. Please help me out, if you have time. Thanks

**Comment by dgosbell** [comment]
> all version have the dependency to install SQL Profiler

That does not sound right. I've used custom versions of ASTrace in the past on servers without Profiler installed. In fact the project was created specifically so that you did **not** need to run Profiler.

> Can we use DaxStudio.QueryTrace as a reference project to a simple .NET application?

That assembly was never designed as a general use tracing library. It might work, but it is not something I could really support or recommend. The only reason it's split out separately is because I needed a different implementation for PowerPivot vs other data sources.

> Is there any other way, where we can simply write trace event functionality and consume in the app?

The second answer from Adrian Dumitrascu on the following post
[https://social.msdn.microsoft.com/Forums/sqlserver/en-US/e9f87b28-a8c2-40fc-b6e6-68dfa59b07a6/capturing-processing-status-and-progress-messages?forum=sqlanalysisservices](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/e9f87b28-a8c2-40fc-b6e6-68dfa59b07a6/capturing-processing-status-and-progress-messages?forum=sqlanalysisservices) has a number of simple examples of how to work with traces. You should be able to paste these into a simple console app and add a reference to the [Microsoft.AnalysisServices.retail.amd64 nuget package](https://www.nuget.org/packages/Microsoft.AnalysisServices.retail.amd64/).

The UseCustomTrace() method is probably as simple an example as you can get. You would just want to alter it from using the progress* events to using either QueryBegin or QueryEnd
