### ISSUE TITLE
V2.12.2 Installation performed partially

### ISSUE THREAD

**Issue by Grosbeta** [DaxStudio/DaxStudio#415]
I installed today the latest version of the tool.

Installation processed stopped before end : daxstudio.pbitool.json file creation in .. \Microsoft Shared\Power BI Desktop\External Tools interrupted (Select action).

Any idea ?

Thanks for this great tool anyway.

**Comment by dgosbell** [comment]
Yes, this is probably due to issue #405. I'm guessing that you chose the "Current User" install - in this case the install script is incorrectly trying to add the Power BI External Tools registration. This will be fixed in the next release so that only the default "All Users" installation tries to run this step (since it requires admin rights).

In the short term the portable build should work for you if you want to use the latest version. Otherwise I should have the next release out shortly.

**Comment by dgosbell** [comment]
This should be fixed in the recent 2.13 release
