### ISSUE TITLE
Error Connecting: The connection either time our or was lost

### ISSUE THREAD

**Issue by attilamezes** [DaxStudio/DaxStudio#422]
Hi, I have an error in connecting my DAX Studio to PowerPivot data models.

The Excel Add-in (version 2.12.2) is unable to connect to Excel. I am getting the "Error Connecting: The connection either timed out or was lost" error message continuously.

1. Go to Add-ins
2. Click on DAX Studio
3. Select PowerPivot Model   [file name]
4. I am getting the Error Connecting ... message immediately.

I expect the DAX Studio connects to the data model

![DAX Studio-Error Connection](https://user-images.githubusercontent.com/39393032/91954243-d7d48200-ed01-11ea-99f3-ff46770fca5c.jpg)

I tried to see any issues with the DAX Studio checker, but I do not see any problem there. I have no clue which setting destroys the connection. I would appreciate your help. Thank you!

**Comment by dgosbell** [comment]
Does this issue happen with all PowerPivot models or just this one?

Can you start up Excel with the SHIFT key held down to enable [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) then reproduce this error, closed down DAX Studio and Excel and then upload the 2 log files to this issue?

**Comment by attilamezes** [comment]
It happens with other models also. I have one which works (interestingly). However, my Excel DAX Studio Add-in never was absolutely stable. 

My Excel version is an Office 365, MS Excel Version 2002 (Build: 12527_20988); I have refreshed DAX Studio this morning. DAX Studio works well with my Power BI models.

Attached are the log files.

[DaxStudio-20200902.log](https://github.com/DaxStudio/DaxStudio/files/5161063/DaxStudio-20200902.log)
[DaxStudioExcel-20200902.log](https://github.com/DaxStudio/DaxStudio/files/5161064/DaxStudioExcel-20200902.log)

**Comment by dgosbell** [comment]
Thanks for those logs they were really helpful. The issue is due t the apostrophe ( ' ) character in the file path. In the short term you could either rename that folder or copy the Excel file out to another location without an apostrophe in the path. I've just added a fix to the code base, so a proper fix for this will be in the next release.

**Comment by attilamezes** [comment]
Thank you!!! 

It works! You are awesome. This is a new learning point for me... the reason I did not suspect the file path (including the apostrophe) because the Power BI files worked fine from the same folder.

It is working as expected. Thank you once again!

Attila

**Comment by rndldvl** [comment]
Hello, I am encountering the same issue as stated in the OP. It was working a few days ago on v3.0.0, however despite reinstalling and downgrading to v2.17, the issue persists.


[DaxStudioExcel-.log](https://github.com/DaxStudio/DaxStudio/files/9668235/DaxStudioExcel-.log)
[DaxStudio-20220929.log](https://github.com/DaxStudio/DaxStudio/files/9668234/DaxStudio-20220929.log)

**Comment by dgosbell** [comment]
@rndldvl - The current PowerPivot connection issues are due to a change in Excel. I cannot fix this from the DAX Studio side. This is being tracked in issue #884 if you want to follow that. But I've been in contact with the Excel team, they have a fix in the works, but it needs to go through reviews before it can be pushed out. Once the Excel fix goes out the existing copies of DAX Studio should start working again
