### ISSUE TITLE
Add toggle to disable DAX Formatter, crash reporting and other connections to Internet sites (due to security limitation at bank)

### ISSUE THREAD

**Issue by spectre9** [DaxStudio/DaxStudio#423]
I work at a bank and we are extra sensitive to data leakage.
I would like a feature to disable DAX Formatter and Crash Reporting web functionality so that DAX Studio could be run on a private network without any interaction with the Internet.

Our bank will not allow usage of DAX Studio because the "DAX Formatter" feature sends DAX to the Internet in background, and errors or crash reports will go to the Internet. 

 The DAX itself could contain things like account numbers or customer names which we are not allowed to disclose to third parties unless we have a contract with them and of course we do not with DAX Formatter (and even if we did, it is not a bank so likely would not have sufficient controls.

**Comment by dgosbell** [comment]
Something like that should not be too hard to implement.

Would you want **ALL** internet functionality blocked (so including checks for new versions) or just those that could potentially leak data like DAX Formatter and the Crash Reporter?

I'll have to have a think about how best to implement this. I'm thinking that if the app was installed just using the "Current User" option or if it's running as a portable app then the user should be able to toggle this on and off through the options screen. By definition the settings for these two modes are stored in user accessible locations so even if there was not a visible option the setting could not be protected.

But if it's installed for "All Users" then I'm thinking that the option needs to be written under the local machine settings in the registry so that it can only be altered by someone with admin rights. So the installer would configure this and the user would not have any option to change it (so it would require a re-install to re-enable this). And that in turn probably means that I need to add a parameter so that the installer can be run silently using a tool like SCCM.

**Comment by marcosqlbi** [comment]
@spectre9 I also have a question: would an "anonymizer" feature be enough to use DAX Formatter, or no matter what you would disable that? The issue with DAX Formatter is that for a number of reasons it is better to implement it as a service now, but the string sent to the service might replace all the strings/names/numbers with random values known only by the client.
However, implementing such a feature is useless if it would not be useful to users like your company, so we can prioritize other features first.
Thanks!

**Comment by marcosqlbi** [comment]
@spectre9 thanks for the feedback, I will not prioritize this feature, then.

**Comment by spectre9** [comment]
BTW DAX Formatter is not the driving force for our uptake... rather I desire to leverage Vertipaq Analyzer.  

Our security team is literally running a trace and doesnt' want to see any internet traffic. They are not going to invest the time, I think, into provign that DAX Studio "meets requiremetns" since it is open source... because we won't have a contract with them.

So maybe this is selfish thinking but at least for us it is an all or nothing - if we cannot remove the Internet traffic for tool I am almost certainly not going to be able to use DAX Studio in this bank.

**Comment by marcosqlbi** [comment]
@spectre9 I think other people might be in the same situation, so if Darren can implement and document a setting that disable all the features requiring external connections, we could make more people happy.
Thanks for your feedback!

**Comment by dgosbell** [comment]
This should be fixed in the 2.14 release which was just published
