### ISSUE TITLE
Datetime column output with FormatString in model

### ISSUE THREAD

**Issue by mst42a** [DaxStudio/DaxStudio#426]
Datetime column with formatString doesn't' showup properly. I have set FormatString in TabularEditor

![image](https://user-images.githubusercontent.com/63145285/92688302-6c139a00-f33d-11ea-9b9e-84f70469d204.png)

but in DaxStudio in results tab this show up like that:
![image](https://user-images.githubusercontent.com/63145285/92688790-41761100-f33e-11ea-9571-cd9002bb8eff.png)

Did I miss something? (if I add  format('Planning Calendar PCAL'[Pl Day],"YYYY-MM-DD") in query statement, the output is correct)

**Comment by dgosbell** [comment]
I'm not sure what is going on here, I've never seen this behaviour before. When I query DateTime columns they display as datetime values
![image](https://user-images.githubusercontent.com/8241830/92691427-e405b280-f385-11ea-9722-f6dd7a7d0e23.png)

We currently only apply format strings to measures, not columns, but datetimes columns should still show in a default datetime format. (we might be able to improve this but there are some complexities trying to map column names to the query output)

Do you have SSMS installed? If so does it produce a similar result

> (if I add format('Planning Calendar PCAL'[Pl Day],"YYYY-MM-DD") in query statement, the output is correct)

I'd expect that since the FORMAT function returns a string

**Comment by mst42a** [comment]
In Sample data it is showing correct:
![image](https://user-images.githubusercontent.com/63145285/92709732-7347a180-f357-11ea-9f16-f77d2c2996b9.png)

I didn't even think to check what the result in SSMS looks like.
And yes it is produced similar results.
![image](https://user-images.githubusercontent.com/63145285/92710385-097bc780-f358-11ea-8f79-b08ceef00b7a.png)

I try to figuredout what is going on and the root cause is my DAX query.
I wanna to mimic old mdx query:

SELECT {[Measures].[ParameterCaption], [Measures].[ParameterValue], [Measures].[ParameterLevel]} ON COLUMNS 
, [Planning Calendar PCAL].[PCAL Planning All].ALLMEMBERS ON ROWS FROM [Everything]


with this one:

evaluate
UNION(
SUMMARIZECOLUMNS(
'Planning Calendar PCAL'[Pl Year]
,'Planning Calendar PCAL'[Pl Season]
,'Planning Calendar PCAL'[Pl Quarter]
,'Planning Calendar PCAL'[Pl Month]
,'Planning Calendar PCAL'[Pl Week]
,'Planning Calendar PCAL'[Pl Day]
,"ParameterCaption", format(SELECTEDVALUE('Planning Calendar PCAL'[Pl Day]),"YYYY-MM-DD")
,"ParameterValue","[Planning Calendar PCAL].[PCAL Planning All].[Pl Year].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Year])&"].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Season])&"].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Quarter])&"].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Month])&"].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Week])&"].&["& format(SELECTEDVALUE('Planning Calendar PCAL'[Pl Day]),"YYYY-MM-DD") & "T00:00:00]"
,"ParameterLevel",6
),
SUMMARIZECOLUMNS(
'Planning Calendar PCAL'[Pl Year]
,'Planning Calendar PCAL'[Pl Season]
,'Planning Calendar PCAL'[Pl Quarter]
,'Planning Calendar PCAL'[Pl Month]
,'Planning Calendar PCAL'[Pl Week]
,"Pl Day", BLANK()
,"ParameterCaption", SELECTEDVALUE('Planning Calendar PCAL'[Pl Week])
,"ParameterValue","[Planning Calendar PCAL].[PCAL Planning All].[Pl Year].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Year])&"].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Season])&"].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Quarter])&"].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Month])&"].&["&SELECTEDVALUE('Planning Calendar PCAL'[Pl Week])&"]"
,"ParameterLevel",5
) [...]


I thought that after union with BLANK() which is scalar A single value of any type.
The BLANK value does not have a data type. That I get Type for whole column from my first UNION Statement.
Executing only first SUMMARIZECOLUMNS. Results is fine
![Uploading image.png…]()

**Comment by dgosbell** [comment]
> I thought that after union with BLANK() which is scalar A single value of any type.
The BLANK value does not have a data type. That I get Type for whole column from my first UNION Statement.
Executing only first SUMMARIZECOLUMNS. Results is fine

Yes, the UNION with the BLANK() value appears to result in the whole column being treated as a Variant datatype. So this is not really a DAX Studio issue as such, it's more of a behaviour of the Microsoft engine. 

So you could either use an explicit FORMAT in your first table expression to force the value to a string.

Or you could try using an expression like the following in your second part of the union:
```
,"Pl Day", IF( FALSE(), DATE(2000,1,1), BLANK() )
```
The value of the date inside the "then" part of the IF expression does not matter as it will never be returned, but because an IF can only return a single data type this will force the BLANK() to be a blank datetime value rather than a variant.

I tested this with the following 3 queries
```
EVALUATE
UNION({ DATE( 2030, 5, 15 )}, { DATE( 2030, 5, 16 ) } )

EVALUATE
UNION( { DATE( 2030, 5, 15 ) }, { BLANK() } )

EVALUATE
UNION( { DATE( 2030, 5, 15 ) }, { IF( FALSE(), DATE( 2030, 5, 17 ) ) } )
```

The first query returns 2 dates, the second one returns the internal numeric value for the date (same as your query) and a blank. The third query returns a date and a blank.
