### ISSUE TITLE
Text is missing in 2k resolution

### ISSUE THREAD

**Issue by tuanphongnt** [DaxStudio/DaxStudio#435]
**Describe the bug**
My monitor is 2k resolution and it's showing the Dax studio with many missing text.
Please help to fix it

**To Reproduce**
1. Any screen as attachments

**Expected behavior**
Text should be fit with 2k resolution

**Screenshots**
![image](https://user-images.githubusercontent.com/61046622/94930377-8251e780-04f0-11eb-95c4-25719fc8c448.png)
![image](https://user-images.githubusercontent.com/61046622/94930416-90a00380-04f0-11eb-9653-2181de223fd7.png)
![image](https://user-images.githubusercontent.com/61046622/94930497-b0cfc280-04f0-11eb-8605-3d34f7bb3f27.png)

**Additional context**

**Comment by marcosqlbi** [comment]
I regularly work with DAX Studio with different resolutions, including 4k and HDPMI - this should work, so first of all we should be able to reproduce the issue.

Can you provide more details from Settings/Display?
- Scale and layout (it should be a percentage)
- Display resolution

Thanks!

**Comment by dgosbell** [comment]
I have both 4k and 1080p monitors and I have not seen this before either. However it looks like might have an increased font scaling applied

If you go into Settings and search for **text size** then click on the **Make text size bigger** option it should take you to a screen like the following

![image](https://user-images.githubusercontent.com/8241830/94982473-030af500-057e-11eb-8907-781ad9fb699d.png)

On your system is the **Make text bigger** slider somewhere in the middle? 

If it is, hover over the slider position and it should tell you what percentage increase you have applied. Then you should change the font scaling back to 100% and instead change the option under **Make everything bigger** to a percentage close to what you had the font size set to.

It looks like the problem is that the fonts are being scaled independently from the other elements on the screen. If you choose the option to scale everything both the icons and the text will get larger which should keep the layout looking normal.

**Comment by tuanphongnt** [comment]
> I have both 4k and 1080p monitors and I have not seen this before either. However it looks like might have an increased font scaling applied
> 
> If you go into Settings and search for **text size** then click on the **Make text size bigger** option it should take you to a screen like the following
> 
> ![image](https://user-images.githubusercontent.com/8241830/94982473-030af500-057e-11eb-8907-781ad9fb699d.png)
> 
> On your system is the **Make text bigger** slider somewhere in the middle?
> 
> If it is, hover over the slider position and it should tell you what percentage increase you have applied. Then you should change the font scaling back to 100% and instead change the option under **Make everything bigger** to a percentage close to what you had the font size set to.
> 
> It looks like the problem is that the fonts are being scaled independently from the other elements on the screen. If you choose the option to scale everything both the icons and the text will get larger which should keep the layout looking normal.

Issues resolved by this solution,
Many thanks guys
