### ISSUE TITLE
Last Updated info in UTC instead of local time

### ISSUE THREAD

**Issue by mAlvarado1986** [DaxStudio/DaxStudio#450]
**Describe the bug**
On Metadata pane, the database name tooltip show Last Update time on UTC instead of local time (GMT-6 in my case)

**To Reproduce**
1. Open Dax Studio
2. Connect to a database
3. On Metadata Pane, put the cursor over the database name picker
4. Check Last Update time
![image](https://user-images.githubusercontent.com/24321784/98022165-e0613b80-1dca-11eb-9321-23447c6f9c7a.png)

**Expected behavior**
Last Update must show local time instead of UTC

**Comment by dgosbell** [comment]
Thanks for logging this idea. You are correct that the last updated datetime is reported in UTC, but I think it is a great idea to show this in local time. I've added the actual timezone offset so that it is clear that this is now in local time. 

This will be part of the next release, below is a screenshot of what it will look like (I'm in GMT+10)

![image](https://user-images.githubusercontent.com/8241830/98195622-505ff500-1f76-11eb-9332-58039a9b1e5b.png)

**Comment by mAlvarado1986** [comment]
Than you!
