### ISSUE TITLE
Version checking is not working

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#46]
With DAX Studio 2.7.1 the about box says "Ahead of Production Version - 2.7.0"
With DAX Studio 2.7.2 the about box says "Checking for updates..." and never shows any update

**Comment by marcosqlbi** [comment]
Also DAX Studio 2.7.2 in the about box now says "Ahead of Production Version - 2.7.0"

**Comment by dgosbell** [comment]
The version number on github has been updates so this should be correct now. I've found the issue with it sticking on the "Checking for updates..." occassionally. There were actually 2 points triggering the update check asynchronously and depending which one finished first sometimes the update status does not get refreshed. This should be fixed in the next release.

**Comment by marcosqlbi** [comment]
It works now!
