### ISSUE TITLE
Relationships tab blank in Vertipaq Analyzer Metrics 

### ISSUE THREAD

**Issue by NigelBarrett** [DaxStudio/DaxStudio#463]
Using 
DaxStudio v2.13.1
Excel O365
No error message.
All the other tabs have data in. 
I am using Vertipaq Analyzer for the first time so I don't know if it was working before or if I just misunderstand what generates metrics for this tab.
The data model has several tables linked - so should there be something on this tab?

**Comment by marcosqlbi** [comment]
It seems there is a regression of the VertiPaq Analyzer library when we connect to Excel.
Thanks for reporting it, I will update as soon as we find the time to fix it.

**Comment by marcosqlbi** [comment]
Unfortunately, we cannot fix it because it is not a regression.
Excel does not provide the information about relationships we need to populate the "relationships" pane.
A workaround you can use is the following:

1. Import the Power Pivot model in a Power BI file. Open Power BI and click on File / Import / Power Query, Power Pivot, Power View.
2. Select the xlsx file containing your Power Pivot model
3. Click "Start"
4. Click "Copy Data"

If the migration completes successfully, you have a new Power BI file with the same model and data of your Power Pivot model. You can run DAX Studio from Power BI and see the Relationship pane correctly populated.
If the migration fails, you should open a support ticket with Microsoft - I see that the latest versions of Power BI have bugs importing data from Power Pivot models!
