### ISSUE TITLE
Unable to Connect to Power BI Service Data Set

### ISSUE THREAD

**Issue by ThreadRider2000** [DaxStudio/DaxStudio#466]
**Describe the bug**

Trying to connect to Power BI Workspace Dataset gives error regarding semi-colon not being allowed.

I copied the connection string from the Power BI Workspace==>Datasets==> Settings==>Server Settings==>Connection string which is in format 

_powerbi://api.powerbi.com/v1.0/myorg/xxx Dashboard**;**initial catalog=xxx Dashboard_

When I entered it in DAX Studio v2.13.1 it gives me error regarding semi-colon which is part of connection string (between Dashboard and initial).

**Expected behavior**

I had DAX Studio v2.11.x installed before and using the same connection string worked,

**Screenshots**

![image](https://user-images.githubusercontent.com/47873685/99757994-9bbdeb80-2abe-11eb-84b8-4fefeb8de286.png)

![image](https://user-images.githubusercontent.com/47873685/99758120-e475a480-2abe-11eb-920b-65dfed313623.png)

**Additional context**

**Comment by dgosbell** [comment]
Thanks for logging this.

> I had DAX Studio v2.11.x installed before and using the same connection string worked,

Yes this is because I fixed a bug recently where connection strings with special characters did not work, so I now wrap the data source in quotes so the connection string will actually look like:
```
Data Source="powerbi://api.powerbi.com/v1.0/myorg/xxx Dashboard;initial catalog=xxx Dashboard"
```
so it will be treating the `;initial catalog=xxx Dashboard` as part of the workspace name.

I have not actually used that option to get that sort of partial connection string from the Dataset directly, I normally just grab the details at the workspace level. So I really appreciate this detailed bug report.

I've just checked in a fix that will deal with this partial connection string format which will be included in the next release.

In the mean time if you remove the `initial catalog=` section from the server name, but then expand the **Advance Options** setting and type the data set name into the **Initial Catalog** option there. (the fix I have checked in will do this automatically for you.
