### ISSUE TITLE
DAX Query Batch Mode

### ISSUE THREAD

**Issue by tobimax** [DaxStudio/DaxStudio#476]
It would be nice to be able to run queries in batch mode. with a batch separator. i.e. the below won't execute. But if you could separate the queries with a "GO" then we could get multiple results sets.

DEFINE
    VAR __FilterTableOptInByOptIn =
        TREATAS ( { "N" }, 'Opt In'[OptIn] )
    VAR __DS0CoreCustomerByValidEmail =
        CALCULATETABLE (
            VALUES ( 'Customer'[ValidEmail] ),
            KEEPFILTERS ( __FilterTableOptInByOptIn )
        )
EVALUATE
__DS0CoreCustomerByValidEmail
ORDER BY 'Customer'[ValidEmail]

DEFINE
    VAR __FilterTableOptInByOptIn =
        TREATAS ( { "N" }, 'Opt In'[OptIn] )
    VAR __DS0CoreCustomerByAge =
        CALCULATETABLE (
            VALUES ( 'Customer'[Age] ),
            KEEPFILTERS ( __FilterTableOptInByOptIn )
        )
EVALUATE
__DS0CoreCustomerByAge
ORDER BY 'Customer'[Age]

**Comment by marcosqlbi** [comment]
The DAX Syntax allows multiple EVALUATE in the same statement. This returns multiple results sets already.
The presence of ";" would enforce DAX Studio to run separate queries (the syntax doesn't allow that) and this would be confusing because the multiple results would be results provided by different requests and not by different statements in the same request. This would make it more complex to handle server timings and query plan information, too.
Let's see what Darren thinks about that, I would say that it would create too many issues, even though I understand the cases where you would like to use it.

**Comment by dgosbell** [comment]
Marco is correct in that the DAX syntax already allows for multiple result sets and DAX Studio already supports this. The only reason your example would not execute is that a batch in DAX can only have a single DEFINE block. So if you re-wrote it as follows it should work fine.

DEFINE
VAR __FilterTableOptInByOptIn =
TREATAS ( { "N" }, 'Opt In'[OptIn] )
VAR __DS0CoreCustomerByValidEmail =
CALCULATETABLE (
VALUES ( 'Customer'[ValidEmail] ),
KEEPFILTERS ( __FilterTableOptInByOptIn )
)
VAR __DS0CoreCustomerByAge =
CALCULATETABLE (
VALUES ( 'Customer'[Age] ),
KEEPFILTERS ( __FilterTableOptInByOptIn )
)

EVALUATE
__DS0CoreCustomerByValidEmail
ORDER BY 'Customer'[ValidEmail]

EVALUATE
__DS0CoreCustomerByAge
ORDER BY 'Customer'[Age]

**Comment by dgosbell** [comment]
Since this functionality already exists I'm going to close this issue.

**Comment by tobimax** [comment]
It only works as a single batch. i.e. multiple DEFINE's break it. i.e. It would be nice to be able to paste in a sequence from Power BI Performance Analyzer and just have it run.
