### ISSUE TITLE
Batch Mode not available in the latest version of DAX Studio.

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#495]
**Describe the bug**
Earlier versions of DAX studio had the Batch mode which are helpful in query tuning but the in the recent versions it seems to be removed. 

Apologies if I didn't follow the ways of GitHub, I have never used it before today :)

**Expected behavior**
![1](https://user-images.githubusercontent.com/73054674/103459882-10c84600-4d38-11eb-89d7-51dce17964b2.png)

**Current Scenario**
![2](https://user-images.githubusercontent.com/73054674/103459962-9d730400-4d38-11eb-8d0b-2defe792eb20.png)

**Comment by marcosqlbi** [comment]
The bug is very clear and already solved in version 2.13.2.
We just moved those options on the "Layout" tab that appears when you activate the Server Timings pane.
If you want to try a preliminary version, use this preview build:
https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/36991123

**Comment by SharmaAntriksh** [comment]
Thank you!
