### ISSUE TITLE
bug in Dax Studio when launched from Power BI

### ISSUE THREAD

**Issue by rdodworth** [DaxStudio/DaxStudio#507]
I am fully up to date with both PBI (: 2.88.1144.0 64-bit (December 2020)) and Daz Studio (2.13.1) but when I launch Dax studio via external tools in PBI it doesn't automatically load my report model but a random instance of one of our deployed SSAS tabular models

**Comment by dgosbell** [comment]
Thanks for logging this. However I have no idea what could possibly cause this. When DAX Studio is launched from the External Tools ribbon Power BI passes us the connection details. And we don't have any code that will scan for SSAS instances so I don't see how we could find a random instance. 

What storage mode is your report using? Is it an import model or are you using live connect to SSAS? if you are using live connect to SSAS then Power BI will pass DAX Studio the connection details to SSAS since that is where the model is hosted.

If this does not explain the issue can you hold down the shift key when you click on the DAX Studio button in the external tools ribbon, this will cause DAX Studio to generate a [diagnostic log](https://daxstudio.org/documentation/troubleshooting/logging-settings/) file. If you can then close DAX Studio and attache the latest log from the `%LOCALAPPDATA%\DaxStudio\log` folder to this issue on Github it might give some more information on what is going on.

**Comment by dgosbell** [comment]
Closing due to a lack of response
