### ISSUE TITLE
DAX Studio 2.7.3: Traces for SSAS Tabular are Timing Out

### ISSUE THREAD

**Issue by markew1** [DaxStudio/DaxStudio#51]
Just installed version 2.7.3. Having difficulties w/ Query Plan and Server Timings traces while evaluating a measure from a SSAS Tabular model. Message: Trace Stopped: QueryEnd event not received - Tracing timeout exceeded.

**Comment by marcosqlbi** [comment]
I am not able to reproduce - which version of Analysis Services are you using?

**Comment by markew1** [comment]
In reply to Macro Russo ... SQL Server 2016 version 13.0.4001

**Comment by marcosqlbi** [comment]
I tried with SQL Server 2016 version 13.0.4457.0 and it works. It seems you have SQL 2016 SP1, I have SQL 2016 SP1 CU6 ma CU7 is available now. However, I don't think it's an issue caused by SSAS, more likely to be caused by client drivers. If you run DAX Studio on a PC other than SSAS server, try installing the latest libraries: https://docs.microsoft.com/en-us/azure/analysis-services/analysis-services-data-providers

**Comment by dgosbell** [comment]
I've double checked on 2012, 2016 & 2107 and cannot reproduce this either. 

Does your query run without errors and return some results?

Does this happen every time you have the Query Plan / Server Timings traces enabled?

Is the server possibly under heavy load at the time? Under heavy load some trace events can get dropped which is why we introduced the timeout so that DAX Studio does not wait forever.

**Comment by markew1** [comment]
I followed Marco Russo's advice, and installed the latest client libraries on my PC, and that seemed to fix my problem.  Thanks for the follow-up by all on this thread.

**Comment by dgosbell** [comment]
Great - thanks for letting us know. We're actually working on a new way of referencing the client libraries to prevent this sort of situation happening in future
