### ISSUE TITLE
Dax Studio stay stuck in the logo 

### ISSUE THREAD

**Issue by vanessa2509** [DaxStudio/DaxStudio#513]
Hello, 

I install Dax studio but he stay stuck on the logo start 

    Version =  v2.14.1.484
    DaxStudio.exe Version =  v2.14.1.484

Checking Operating System
=======================
    OSCaption       = Microsoft Windows 10 Enterprise
    OSRelease       = 1803
    OSVersion       = 10.0.17134
    OSArchitecture  = 64-bit
    VisibleMemoryGB = 15.81
    FreeMemoryGB    = 7.08

    Culture Name              = en-US
    Culture DisplayName       = English (United States)
    Culture EnglishName       = English (United States)
    Culture 2-Letter ISO Name = en
    Culture DecimalSeparator  = .
    Culture GroupSeparator    = ,
    Culture CurrencySymbol    = $
    Culture ShortDatePattern  = M/d/yyyy

Checking Displays
=======================
Display: \\.\DISPLAY1 (Primary) 
         X: 0 Y: 0 Width: 1920 Height: 1080
DPI X: 120 Y: 120 (Scaling: 125.0%)

Checking .Net Framework
=======================
    v2.0.50727 -> 2.0.50727.4927
    v3.0 -> 3.0.30729.4926
    v3.0\Setup -> 3.0.30729.4926
    v3.0\Setup\1031 -> 3.0.30729.8795
    v3.0\Setup\1033 -> 3.0.30729.4926
    v3.0\Setup\1036 -> 3.0.30729.8795
    v3.0\Setup\1043 -> 3.0.30729.8795
    v3.0\Setup\Windows Communication Foundation -> 3.0.4506.4926
    v3.0\Setup\Windows Presentation Foundation -> 3.0.6920.4902
    v3.5 -> 3.5.30729.4926
    v3.5\1031 -> 3.5.30729.5003
    v3.5\1033 -> 3.5.30729.4926
    v3.5\1036 -> 3.5.30729.5003
    v3.5\1043 -> 3.5.30729.5003
    v4\Client -> 4.7.03056
    v4\Client\1031 -> 4.7.03056
    v4\Client\1033 -> 4.7.03056
    v4\Client\1036 -> 4.7.03056
    v4\Client\1043 -> 4.7.03056
    v4\Full -> 4.7.03056
    v4\Full\1031 -> 4.7.03056
    v4\Full\1033 -> 4.7.03056
    v4\Full\1036 -> 4.7.03056
    v4\Full\1043 -> 4.7.03056
    v4.0\Client -> 4.0.0.0

    v4\Full\Release = 461808 (4.7.2)
    PASS > .Net Version 4.7.2 is above the required minimum

Dax Studio Configuration
=======================
    Path: "C:\Program Files\DAX Studio\DaxStudio.exe"
    Processing DaxStudio.exe.config file...
    Path: 'C:\Program Files\DAX Studio\DaxStudio.exe.config'
    Bindings Found: 23
    AMO : 19.16.0.0
    ADOMD : 19.16.0.0

Checking Excel Add-in
=======================
    Detected Excel Version: 16 - Excelv16
    Excel Path: C:\Program Files (x86)\Microsoft Office\Root\Office16\EXCEL.EXE
    Excel Architecture: x86

    DAX Studio Excel Add-in Registry keys
       Description: DAX Studio Excel Add-In
       FriendlyName: DAX Studio Excel Add-In
       Manifest: file:///C:/Program Files/DAX Studio/bin/DaxStudio.vsto|vstolocal
       LoadBehavior: 3

    Checking for Excel 2010 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2013 Disabled Add-ins
      PASS > No Disabled items found.
    Checking for Excel 2016 Disabled Add-ins
      PASS > No Disabled items found.

      PASS >  Found Excel Addin: Microsoft Power Pivot for Excel

    Attempting to load Excel Add-in: 
      PASS > Loaded Excel Add-in: DaxStudio, Version=2.14.1.484, Culture=neutral, PublicKeyToken=null

    Checking VSTO Configuration
    Architecture: x64
      v4
        Version 10.0.60828
        Install 1
        InstallerPath c:\Program Files (x86)\Common Files\Microsoft Shared\VSTO\10.0\VSTOInstaller.exe
      v4M
        VSTOMFeature_UNM 1
        VSTOMFeature_CLR35 1
        VSTOMFeature_CLR40 1
      v4M_1031
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4M_1036
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1
      v4M_1043
        VSTOM_res_UNM 1
        VSTOM_res_CLR35 1
        VSTOM_res_CLR40 1

Registry Settings
=======================

**Comment by dgosbell** [comment]
When issues like this have come up [previously](https://github.com/DaxStudio/DaxStudio/issues/402). I did find this [blog post](https://weblog.west-wind.com/posts/2019/Feb/14/WPF-Hanging-in-Infinite-Rendering-Loop) which discusses a very similar scenario where a small percentage of people running .Net 4.7.x were seeing application hangs. 

So there are 3 things worth trying:

1. Since you are using a display scale setting that is not 100% - as a test could you try changing this to 100% temporarily and see if DAX Studio will start?  (right click on an empty portion of your desktop, go to Display Settings and check the setting under Scale and layout)  If so you may be hitting the issue from the blog post above and it would be worth trying item 2 below.
2. In the folder where DAX Studio is installed is a file called daxstudio.exe.config. Copy this file out to your desktop or some other temporary location. Then open it in a text editor, about 14 lines down you will fine a line that says `<runtime>`, add a line under that and insert the following `<AppContextSwitchOverrides value="Switch.System.Windows.Controls.Grid.StarDefinitionsCanExceedAvailableSpace=true" />`. Then copy this edited file back over the top of the original file. Then try launching DAX Studio.
3. Another option would be to try updating to .net 4.8 (which you can get from https://dotnet.microsoft.com/download/dotnet-framework/net48 ) this has fixed a number of strange startup issues people have had

**Comment by vanessa2509** [comment]
Daren,

It’s ok !

Thanks a lot for your help

**Comment by vanessa2509** [comment]
In order !
