### ISSUE TITLE
Copy/Export Metrics Data

### ISSUE THREAD

**Issue by cbailiss** [DaxStudio/DaxStudio#517]
Thanks for continuing to develop this great tool.  

A feature request: (unless it already exists and I have just not figured out how to do it).

**Is your feature request related to a problem? Please describe.**
It is often helpful to analyse the "View Metrics" data further in Excel, though (using DAX Studio) there doesn't appear to be an easy way to copy it to the clipboard / export it. 
The "Export Metrics" feature seems to generate a zip file?
I know there is the original spreadsheet method, but sometimes (for speed) it would just be handy to copy what's in DAX Studio!

**Describe the solution you'd like**
Copy the data in the selected Metrics tab to the clipboard as tab separated.
Export the data in the selected Metrics tab to CSV/Excel.

**Comment by marcosqlbi** [comment]
The issue with that approach is that you wouldn't have the two-level structure you have in DAX Studio.
Is the issue only related to the performance required to import the VPAX file in Excel, or is there something else?

**Comment by cbailiss** [comment]
A few different reasons for supporting Copy-Paste e.g. into Excel:

- Convenience (one of the things that makes DAX Studio great) 
    - I would no longer need to use the older Excel workbook approach (which was great, but takes a bit longer to configure/use).
    - I could extract the JSON from the VPAX ZIP file and then read that file with Power Query - but that also takes a bit longer than a simple Copy-Paste.
- To be able to group/filter the columns differently.
- To be able to quickly sum up the total size.

I understand the reasoning about the two-levels.  Personally I'd be happy with the lower level of detail - I can sum in Excel :-)
Or a relatively easy solution to that (albeit more dev work) would be a couple of different copy options.

**Comment by marcosqlbi** [comment]
Based on your comment, you would like a "bulk copy" that would include different details of data that you can aggregate in a single table in Excel. Or in two different tables. The current visualization mixes different levels of granularity that you cannot aggregate. For example, the Cardinality column has different meanings for tables and columns. Copying the data that you have today wouldn't work very well because you should filter subtotal rows (table level) to get meaningful results.
Just to better understand your request: if getting the Excel file with the underlying data model would be possible with a single click in less than 2 seconds (just dreaming), would you still want to copy/paste data?
I'm trying to understand the goal of the copy action - not because I don't like it, but because I think that a simple copy of the existing visualization wouldn't work well.

**Comment by cbailiss** [comment]
Ahh yes, I was only thinking about the size columns when summing.

I was also not thinking of "Copy all metrics" button in the ribbon that would copy all tabs in one go.
I was more thinking of a quick copy from the current selected tab in the metrics window, e.g. see below - or a ribbon button that just copies the current metrics (current tab).

![image](https://user-images.githubusercontent.com/11745789/105881842-e434e080-5ffc-11eb-8702-ca0d38112973.png)
(please ignore the horrible looking data about some of the columns in this tabular model....!)

If there are multiple levels, then perhaps two options on the context menu to select the level.  
Or an additional column in the copied data that identifies whether the copied row from the visual relates to a table or column - then it's easy to filter to either in Excel (that is a bit ugly but would work).

If it were possible to open the Excel file quickly then that would meet the need as well.  Don't misunderstand - the metrics view in DAX studio is great and meets many needs - but as ever with data there is always eventually a need to filter, group, sum, etc.

**Comment by marcosqlbi** [comment]
I completely understand, this is the reason why we have Excel as the primary output of VertiPaq Analyzer. The DAX Studio visualization is a good substitute for a quick look, but we don't want to replicate the Excel features in DAX Studio.
I don't know how expensive a quick copy/paste could be, but I suspect you will never be completely satisfied by that.
Long term, I'd like to improve the generation of the Excel file from DAX Studio without having to save the VPAX file and then import it, but the real issue is that the import part in Excel is slow. Even though we automate the process (which is possible), the waiting time would be way more than 2-3 seconds.
I don't have a good solution. I have an idea, but it's expensive (to implement) and not necessarily faster.
No short-term solutions other than a minimal copy/paste if @dgosbell is willing to implement it.

**Comment by cbailiss** [comment]
>> I don't know how expensive a quick copy/paste could be, but 
>> I suspect you will never be completely satisfied by that.

I can only speak from my perspective, but a quick copy-paste would work for me.

**Comment by dgosbell** [comment]
I had a quick look at this today and it's probably not too complex to fix the copy/paste issues. I can set a special clipboard binding for the custom columns which have the hierarchies and bar chart graphics. So I'm thinking of re-mapping the **Name** column in the **Tables** tab to the one we use in the **Columns** tab which has `<table name>-<column name>` and I can add a setting to include the column headers in the copy so that you know which column is which.

**Comment by dgosbell** [comment]
I have a fix checked in that should now enable basic copy/paste. It will be included in the next release and when we publish that github will automatically close this issue.

**Comment by cbailiss** [comment]
Thanks.
