### ISSUE TITLE
add sort by function

### ISSUE THREAD

**Issue by dqaudithillstone** [DaxStudio/DaxStudio#523]
DAX Studio v2.14.1.484
Connection: PowerPivot - 11.0.9165.1186

## Summary of Issue
The query builder adds two functions:
1. When adding a measurement value, you can drag the new measurement value as a calculation item
2. It is recommended to add sorting options

## Steps to Reproduce
1.
2.

**Comment by dgosbell** [comment]
Can you explain what you mean by point 1? If you are talking about [Calculation Groups](https://docs.microsoft.com/en-us/analysis-services/tabular-models/calculation-groups?view=asallproducts-allversions) then this is not possible to add in a query, these need to be designed into your data model.

I think I understand point 2 - I actually have code in the query builder engine that can generate the ORDER BY clause in a DAX query, I just need to design how I want to display this. It's complicated a bit by the "sort by" property on columns as the way DAX works is that we actually need to include these in the query output in order to sort by the

**Comment by dgosbell** [comment]
closing due to lack of response
