### ISSUE TITLE
Pressing F1 on a Function should open https://dax.guide/

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#525]
Pressing F1 when cursor is over a function should open DaxGuide with the documentation for that function.

If I put cursor over CALCULATE and press F1, a webpage should open navigating to https://dax.guide/calculate/

Let me know what you think. Thanks!

**Comment by dgosbell** [comment]
Thanks, this is a good idea. I don't think I can do this when the cursor is just hovering over the function, this will display the tooltip, but technically any keyboard events still go to the control that has the blinking cursor in it. But I could make it so that if you single click on a function (so that it gets the blue background) - then you could push F1. I might also add a right-click menu for this also.

**Comment by SharmaAntriksh** [comment]
Awesome! Thanks for all your endless efforts on Dax Studio!!
