### ISSUE TITLE
Memory consumption by DAX Studio is pretty high even after clearing cache

### ISSUE THREAD

**Issue by SharmaAntriksh** [DaxStudio/DaxStudio#530]
I have noticed that even after clearing cache explicitly DAX Studio's memory consumption is extremely high.

Memory usage while PowerBI is open and DAX Studio isn't:
![1](https://user-images.githubusercontent.com/73054674/105878467-f0497f80-5fb5-11eb-8153-76fb94e81b30.png)

After opening DAX Studio:
![2](https://user-images.githubusercontent.com/73054674/105878544-00615f00-5fb6-11eb-987b-bda1196b3e2b.png)

After running the highlighted query on 12.5 million rows: ( Clearing cache or running a query that returns few rows has very low impact on RAM consumption)
![3](https://user-images.githubusercontent.com/73054674/105878649-1c650080-5fb6-11eb-9579-1eed9bd90a42.png)

![4](https://user-images.githubusercontent.com/73054674/105878709-2b4bb300-5fb6-11eb-8489-c3c46114c04f.png)

After closing DAX Studio:
![5](https://user-images.githubusercontent.com/73054674/105878876-5afabb00-5fb6-11eb-845a-41502a408999.png)

**Comment by marcosqlbi** [comment]
Clear cache is a command sent to the Analysis Services / Power BI engine.
This consumption in DAX Studio could be caused by a large result set you loaded before. 
The memory could be claimed back after you change the result grid by executing another query, or by closing the query window containing the large resultset. However, there is no guarantee you immediately see the memory released because of the way the application and the operating system interact.

**Comment by SharmaAntriksh** [comment]
Makes sense, I didn't factor in that output pane also consumes memory for loading the data. Thanks for the clarification!
