### ISSUE TITLE
Cannot copy Power BI Performance Data after loading in DAX Studio

### ISSUE THREAD

**Issue by aguinaldo92** [DaxStudio/DaxStudio#531]
**Describe the bug**
I want to copy the table formatted data DAX studio provides when you load the Power BI performance json into it.

**To Reproduce**
1. export PBI Performance data into json.
2. Click on "Load Perf Data" 
3. Select all (ctrl+a) in OBI Performance Pane
4. copy (both via ctrl+c or copy menu)
5. Paste anywhere

**Expected behavior**
i expect to be able to paste the table in excel or some other tools

**Additional context**
Dax Studio 2.14.1 Windows 10 1903

**Comment by dgosbell** [comment]
I'm sorry, I'm not sure what the issue is on your system, but the copy/paste definitely works both with selected rows and with ctrl-a. I can't think what could possibly cause this not to work.
 
![Copy-PBI-Perf-Data](https://user-images.githubusercontent.com/8241830/106198267-f3d44500-6207-11eb-9a8e-7bd358c65832.gif)

The other approach if you just want the data in Excel is to use Power Query in Excel just to import the json file directly.

**Comment by dgosbell** [comment]
@aguinaldo92  Is this still an issue for you? As you can see above I cannot reproduce this issue. Does the issue persist in between reboots?

**Comment by dgosbell** [comment]
Closing due to a lack of response and unable to replicate
