### ISSUE TITLE
Add DaxStudio in PowerBI desktop's external tools ribbon 

### ISSUE THREAD

**Issue by tyjulianchen** [DaxStudio/DaxStudio#542]
How to re-write the following line in Json file in order to have a DaxStudio button icon in the External Tools ribbon within Power BI Desktop?
**"iconData": "image/png;base64,<encoded png icon data>"**

**Comment by dgosbell** [comment]
You should not have to re-write anything. If you use the "All Users" option when installing it will write out the json file for Power BI Desktop with the correct data in order to display the icon in the external tools.

This is what I get when I install the latest version of DAX Studio on a machine with Power BI Desktop
![image](https://user-images.githubusercontent.com/8241830/107339700-17a16000-6b11-11eb-8aa0-1bd8333d1ee2.png)

**Comment by tyjulianchen** [comment]
I got it. Appreciate your immediate response.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
