### ISSUE TITLE
Export Data - SQL Tables

### ISSUE THREAD

**Issue by corycundy** [DaxStudio/DaxStudio#549]
When using the Export Data Wizard and select SQL Tables, the process fails when using SQL Auth with password that contains semicolons. 

**To Reproduce**
1. Connect to a tabular model
2. Select Export Data from the Advanced tab in the ribbon
3. Select SQL Tables
4. Enter a connection using SQL Authentication with an account that has a password with semicolons embedded within it

**Expected behavior**
I would expect this to export the tables as it normally would with and account that has a password without semicolons. An error is generated stating 

**Additional context**
The error message in the Output window displays the following:
Error when attempting to export all data - Error parsing connections string: ------------- - Format of the initialization string does not conform to specification starting at index 118.

In my specific case, I was connecting to a Managed Instance, but I wouldn't think that would matter.

**Comment by dgosbell** [comment]
Thanks for logging this. This is happening because we should be putting quotes around passwords with special characters like semi-colons. 

As a temporary work around you can click the **Edit Connection String** link at the bottom of the screen after entering your connection details, Then you will see a part of the connection string that has `Password=` followed by your password. If you put a quote character `"` at the start and end of your password then click next this should work around this issue. 

I've checked in a proper fix for this which will go out with the next release (and this issue will automatically close itself when that happens)

**Comment by corycundy** [comment]
Darren, 

Thanks for the quick reply and workaround.  Double quotes should work. I haven't had to deal with a password that had double quotes in it yet. I'm not sure how that should be handled. Possible escaping them somehow would be my guess. I haven't looked into it.

Thanks again!

Cory

**Comment by dgosbell** [comment]
So the connection string standard says that you can either use double or single quotes and if the value contains the quotes you are using you can escape them by doubling them up.  So something like `my"fancy;password`  would become `"my""fancy;password"` but this is only temporary. The updated code in the next release will handle the quoting and escaping automatically
