### ISSUE TITLE
Copy result timings from Server Timings pane

### ISSUE THREAD

**Issue by marcosqlbi** [DaxStudio/DaxStudio#559]
Implement "copy" feature from the server timings pane, copying in the clipboard the following information:
- Total
- FE
- SE
- SE CPU
- SE CPU (parallelism factor)
- SE Queries
- SE Cache

The number should be copied in the clipboard so that by pasting the data in Excel we would get one value for each column.
This way, it would be easy to copy/paste the result of a query execution to make comparisons between different query plans.

We don't have to copy the list of SE queries, the only data required comes from the left pane in the Server Timings window.

![servertimings](https://user-images.githubusercontent.com/13840816/109781310-180cb280-7c08-11eb-9693-7bf75471a13b.jpg)

**Comment by Oxenskiold-DAX** [comment]
**x56.6** ?! - that's quite a whopper machine you have at your disposal, Marco :-)

Btw. Great suggestion - hope it will be implemented.

**Comment by marcosqlbi** [comment]
It's the latest toy received by Alberto!

**Comment by dgosbell** [comment]
That should be pretty simple to implement, the trickiest bit is to figure out how to surface this in the UI. I could probably add a copy button on the little mini toolbar

**Comment by dgosbell** [comment]
So if I were to have add a new **Copy Results** button and it pasted into Excel like the following screenshot that would work right? :)  

![image](https://user-images.githubusercontent.com/8241830/109923196-876ec900-7d12-11eb-85b1-8dcc1f2c0bd0.png)

**Comment by marcosqlbi** [comment]
Yes @dgosbell it's exactly that!

Marco

**Comment by dgosbell** [comment]
So I've gone one step further and captured the DateTime from the QueryEnd event and added that to the output and I've added a context menu to the Server Timings summary so that you can just copy the headers the first time, then paste a bunch of rows for different runs.

![image](https://user-images.githubusercontent.com/8241830/109931542-18e33880-7d1d-11eb-9ff7-f6c84c0bbb25.png)

It includes the full hh:mm:ss (even though Excel defaults to not showing seconds) so that should be enough to sort and identify the order of different runs.

**Comment by marcosqlbi** [comment]
This is awsome!
