### ISSUE TITLE
Error when selecting Advanced | View Metrics

### ISSUE THREAD

**Issue by DaveStabilify** [DaxStudio/DaxStudio#562]
DAX Studio v2.14.1.484
Connection: PowerBIDesktop - 15.1.76.22

## Summary of Issue
Error returned when View Metrics is selected in the Advanced tab:
**"Error viewing metrics: One or more errors occurred. An unexpected error occurred (file 'xmtwdatacache.cpp', line 2719, function 'XMWindowingIterator::Init'"**

## Steps to Reproduce
1. Select Advanced tab
2. Select View Metrics

**Comment by dgosbell** [comment]
Duplicaate of #459 I'm going to close this issue as we are tracking that fault in the original issue. It's a microsoft bug, but the original issue has a workaround that may help

**Comment by DaveStabilify** [comment]
Sorry Darren I didn't realize this is an existing issue.

**Comment by dgosbell** [comment]
No worries, I've pinned that issue now as a few people are hitting it, so I'm trying to keep everyone who is affected on that one thread. But unfortunately it's not easy to reproduce consistently, so it's hard to say when MS will fix this. We are also looking at providing a fall back mechanism within View Metrics so that the metrics will still display, but maybe with slightly reduced accuracy when we hit errors like this.
