### ISSUE TITLE
Query Builder - don't collapse metadata tree pane upon field or measure selection

### ISSUE THREAD

**Issue by business-data-analytics** [DaxStudio/DaxStudio#563]
**Is your feature request related to a problem? Please describe.**

From a single table, I need to select multiple fields and measures. Whenever I select a field or measure from model metadata pane **using keyboard shortcuts**, the tree collapses, then again I need to expand the same table for next field / measure selection. 

**Describe the solution you'd like**
The tree should retain its state (expanded or collapsed when selecting fields or measures so that multiple fields can be quickly selected in query builder pane.

Working alternative:
Using mouse drag and drop, the tree view doesn't collapse.

**Comment by dgosbell** [comment]
Thanks for logging this. I always tend to either use drag/drop or I use search with the keyboard shortcuts. I've never tried to use a hybrid mouse and keyboard short cut approach like this. The collapse of the tree happens because I send a clear command to the metadata search pane which resets the tree. I've added a check that the search text is not empty before sending the clear command and this appears to fix this issue. This fix will be in the next release and this issue will auto close when we publish that.
