### ISSUE TITLE
Add hovering capability in the editor to display dax.guide information and link

### ISSUE THREAD

**Issue by erapade** [DaxStudio/DaxStudio#569]
**Is your feature request related to a problem? Please describe.**
This is an extension of #568 that will add a right-click option. If users are not aware of the right-click option, they will not realize they can right-click. Adding a Mouse-Hovering capability will make this more visible for the end users

**Describe the solution you'd like**
Hovering with the mouse over a DAX function shall show the same dax.guide information as when you type the function and end with an "("

**Describe alternatives you've considered**
Just stick with the right-click option that also will be helpful

**Additional context**
Sorry for not mentioning this already when requesting the right-click option

**Comment by dgosbell** [comment]
This is interesting. I had not looked at the hover event too closely before since I was worried that it would get fired too frequently, but it seems to wait half a second or so before it fires which is not too bad (since the code to figure out what word is under the mouse and then figure out if that word is a function is a little bit expensive if it had to be run every time the mouse moved).

The only minor problem is that the tooltip seems to "stick" sometimes even when you click away, but it does reset when you start typing or if you hit ESC so I think it's not too bad. And I've added an option to disable the hover if it people find it annoying.
