### ISSUE TITLE
Add column sorting to the query builder

### ISSUE THREAD

**Issue by samaguire** [DaxStudio/DaxStudio#570]
It would be great to get an additional section below filtering, and like the filtering section, where we could add columns and have a dropdown to define if they are ASC or DESC.

If the column has a sort by column set, then I thought that both columns get added but are 'linked', with the 'main' column greyed out and not able to be changed and the sort by column available to set as ASC or DESC.

**Comment by dgosbell** [comment]
So I've already added support to the QueryBuilder engine so that it can generate an ORDER BY clause in the query. The trickier bit is figuring out how to make the user experience work without confusing people.

> If the column has a sort by column set, then I thought that both columns get added but are 'linked', with the 'main' column greyed out and not able to be changed and the sort by column available to set as ASC or DESC.

Technically the "OrderBy" and "Main" column don't have to be at the same level of granularity and typically Power BI sorts first by the "OrderBy" and then by the "Main" column - so I'll probably leave both enabled to allow maximum flexibility. 

And the DAX language can **only** sort by columns that are included in the results, so I'll need to inject OrderBy columns into the "Columns" area. And technically you can have multiple columns with the same "OrderBy" column (eg. you could have a [Short Month Name] and a [Long Month Name] which both sort by [Month Number]) so I'll also need to ensure that I don't do this twice in those instances. 

So I will get this functionality into the Query Builder, there are just a few edge cases I need to figure out how best to handle some of these User Experience issues.

**Comment by samaguire** [comment]
Cool! It'll be a fantastic addition to the Query Builder. Super useful when trying to perform calculation validations / troubleshooting.

> Technically the "OrderBy" and "Main" column don't have to be at the same level of granularity and typically Power BI sorts first by the "OrderBy" and then by the "Main" column - so I'll probably leave both enabled to allow maximum flexibility.

I was thinking it might keep it simple only having the control against the 'SortBy' column - since the granularity can only be the same grain or less granular and Power BI's behaviour is to sort both columns the same. i.e. both ASC or both DESC. Maybe add a check box so you can override the default behaviour and specify the sort direction on the 'Main' column as well?

> And the DAX language can only sort by columns that are included in the results, so I'll need to inject OrderBy columns into the "Columns" area...

Yeah, no pretty way around this. Though, I guess it should be obvious to the user why the results contain the extra column(s) as they should be noting that adding a sort criteria for a 'Main' column where that column also has a specified 'SortBy' column is adding two fields instead of one.

The question of a shared 'SortBy' columns is something I hadn't considered. I guess a hierarchy type UI view with 'Main' columns sitting indented and underneath the related 'SortBy' columns makes most sense. 🤔

Whatever you end up doing, I'm looking forward to seeing it. 👍
