### ISSUE TITLE
Refresh Metadata hotkey

### ISSUE THREAD

**Issue by KPMTGG** [DaxStudio/DaxStudio#575]
Hello, for some reason the DaxStudio inline hint/autocompletion will stop working and I must often refresh the Metadata to fix it.  Would you please consider adding a hotkey for Metadata refresh?

BTW, great work on this application.  It is awesome!

**Comment by dgosbell** [comment]
So I _could_ add a hotkey for the metadata refresh, but if your only reason for asking is to get the autocompletion working then I'm pretty sure this will not do that.

The reason for this is that I've tracked the issue with the autocomplete down to the fact that a hidden autocomplete window gets "stuck" and the editor thinks it's displaying when it is not and what actually resets this is to click out of the editor and then back in, not specifically the Metadata refresh operation.

I've tried a number of things to fix this in the past, but the problem has been that I did not have a reliable way of triggering the autocomplete issue so it was next to impossible to figure out what the root cause is or if if the changes I was making were having any effect. 

However today I think I figured out a specific sequence that triggers this, it only works once, then I have to restart DAX Studio, but I think it's enabled me to isolate this issue and develop a work around.

So if what you were asking for is a fix for the autocomplete bug I think I have that. But I'm not sure if a hotkey for the metadata refresh is really needed as it should normally be a relatively rare operation.

**Comment by KPMTGG** [comment]
Just the comment about clicking outside of the application will fix the issue is helpful!  I hope you fix it in general, but that comment alone is useful.  Thank you for your reply and hard work.  I only WISH I could code something like you have.

Thank you again!

**Comment by dgosbell** [comment]
Yes, I've found that even doing a quick alt-tab, alt-tab to switch away and back to DAX Studio seems to clear this issue. 

But I do think I may have this issue solved now. I have found a sequence of steps that will repeatedly trigger this bug on the current release, but in the new build the code I've added can detect and auto-correct this situation so the autocomplete keeps working and I have not been able to make it fail so far which is looking very promising.
