### ISSUE TITLE
New feature - Report the resource (memory) usage for a query

### ISSUE THREAD

**Issue by jm98** [DaxStudio/DaxStudio#63]
As a developer
I want to easily obtain the resource (memory) requirements per query
So that I can build a concurrent query size model from either "Server Timings" or "All Queries"  without needing to remember which DMV to use and set up my own traces

**Comment by marcosqlbi** [comment]
This is not easy. There is a limit in the SE cache and just summing the memory of SE for the queries sent wouldn't make much sense. Moreover, you would sum queries that reuse existing cache (not possible to detect that in a safe way, you could just evaluate the presence of a Cache Hit event) but there is no way to know whether a previous cache has been evicted or not. Cache size does not depend on RAM available, it's a limit in number of queries kept in cache for each database that cannot be changed in configuration (it's fixed limit that might change in different versions of the engine).
I would close this issue because I don't see how it could be implemented in a reliable way, but I'm open to further comments and suggestions.

**Comment by jm98** [comment]
I was looking more into the Formulae Engine cost as that is not cached
between queries

**Comment by jm98** [comment]
Thanks. Since a pre-requisite doesn't exist then close the request.

**Comment by marcosqlbi** [comment]
Ok thanks!
