### ISSUE TITLE
DaxStudio does not launch

### ISSUE THREAD

**Issue by masterhouyi** [DaxStudio/DaxStudio#630]
**Describe the bug**
Dax Studio does not launch.  Nothing happens. No splash screen.

**To Reproduce**
1. Install Dax Studio
2. Launch Dax Studio

**Expected behavior**
Dax Studio to launch.

**Additional context**
I installed the latest .Net Framework from Microsoft and tried running .Net Framework repair tool.

**Comment by masterhouyi** [comment]
DaxStudioChecker:
    Version =  v2.15.0.525
    DaxStudio.exe Version =  v2.15.0.525

Checking Operating System
=======================


FATAL ERROR:
Invalid class 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at DaxStudio.CheckerApp.SystemInfo.GetOSInfo()
   at DaxStudio.CheckerApp.SystemInfo.OutputOSInfo(RichTextBox output)
   at DaxStudio.CheckerApp.Checker.CheckOSInfo()
   at DaxStudio.CheckerApp.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)

**Comment by masterhouyi** [comment]
Dax Studio Log
[DaxStudio-20210526.log](https://github.com/DaxStudio/DaxStudio/files/6549374/DaxStudio-20210526.log)

**Comment by masterhouyi** [comment]
Currently installed "classic" .NET Versions in the system:
2.0.50727.4927 Service Pack 2
3.0.30729.4926 Service Pack 2
3.5.30729.4926 Service Pack 1
4.0.0.0
4.8.04084

**Comment by dgosbell** [comment]
This is the first time I've seen an issue like that. I'm not entire sure what this is, but it's almost definitely an issue on your machine.

The fusion log has the following error message:
```
Rejecting native image because native image dependency 
C:\WINDOWS\Microsoft.Net\assembly\GAC_64\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll 
had a different identity than expected
```

mscorlib.dll is a core part of the .net framework so this is points to a corruption in your install of the .net framework. I'm not sure why the repair option would not work. DAX Studio requires .net 4.71 or higher so maybe try uninstalling and re-installing .net 4.8

There was a comment on [this](https://stackoverflow.com/questions/18683021/ngen-error-because-mscorlib-dll-does-not-have-a-native-image-x64-only-net-4) stackoverflow post about the same error message and in the comments on the answer someone mentioned that the repair option did not work for them either and they had to uninstall and re-install

**Comment by dgosbell** [comment]
I'm going to close this issue as it appears to be related to an issue with the .net framework on your specific computer rather than a bug with DAX Studio
