### ISSUE TITLE
Dual or Direct Query tables cardinality show as 0, only imports have cardinality showing with correct counts

### ISSUE THREAD

**Issue by JPpowerbi** [DaxStudio/DaxStudio#645]
**Describe the bug**
Connected to the dataset in the Power BI service and clicked 'View Metrics'.  The dataset is a composite.  Cardinality record counts are only showing on the imports in the dataset, anything that is a dual or direct query has 0 cardinality.

**To Reproduce**
1. Go to Advanced Tab
2. Click on View Metrics
3. Look at VertiPaq Analyzer Metrics

**Expected behavior**
I would expect that the dual and direct query tables record counts should show under cardinality, it should not be 0.

**Comment by marcosqlbi** [comment]
This behavior is by design.
The VertiPaq Analyzer provides information about the VertiPaq engine.
Getting information about the cardinality of a DirectQuery source would require a query to the data source that could be computationally expensive. While this is technically possible, it should not be the default behavior. However, it is not available as an option, yet.

**Comment by rgeorge001** [comment]
I agree with the explanation of the behavior for DirectQuery but what about for dual?  That data is imported and should be able to captured through VertiPaq Analyzer, correct?

**Comment by marcosqlbi** [comment]
I will investigate and keep you posted.
