### ISSUE TITLE
Issue opening a new query

### ISSUE THREAD

**Issue by OLTrustNo1** [DaxStudio/DaxStudio#657]
DAX Studio v2.16.0.603
Connection: PowerBIDesktop - 15.1.88.19

## Summary of Issue
Cannot open a new query

## Steps to Reproduce
1.  Open DAX Studio
2. Write any query or open an existing query
3. Click on "File" menu
4. Click on "New" or "New (Copy Connection)"
5. Nothing happens :(

**Comment by dgosbell** [comment]
Thanks so much for reporting this. There seems to be an issue loading the Query History that only affects the second tab you try to open. I'll try and get a 2.16.1 release out in the next few days

**Comment by OLTrustNo1** [comment]
Thanks for looking into it 😉
Such a great tool btw, absolutely love it!

**Comment by edhans** [comment]
I am seeing this too. This is the full error:
6/25/2021 11:18:06 AM		Error creating new document: The composition produced a single composition error. The root cause is provided below. Review the CompositionException.Errors property for more detailed information.

1) Object reference not set to an instance of an object.

Resulting in: An exception occurred while trying to create an instance of type 'DaxStudio.UI.ViewModels.DocumentViewModel'.

Resulting in: Cannot activate part 'DaxStudio.UI.ViewModels.DocumentViewModel'.
Element: DaxStudio.UI.ViewModels.DocumentViewModel -->  DaxStudio.UI.ViewModels.DocumentViewModel -->  AssemblyCatalog (Assembly="DaxStudio.UI, Version=2.16.0.603, Culture=neutral, PublicKeyToken=null")

Resulting in: Cannot get export 'DaxStudio.UI.ViewModels.DocumentViewModel (ContractName="DaxStudio.UI.ViewModels.DocumentViewModel")' from part 'DaxStudio.UI.ViewModels.DocumentViewModel'.
Element: DaxStudio.UI.ViewModels.DocumentViewModel (ContractName="DaxStudio.UI.ViewModels.DocumentViewModel") -->  DaxStudio.UI.ViewModels.DocumentViewModel -->  AssemblyCatalog (Assembly="DaxStudio.UI, Version=2.16.0.603, Culture=neutral, PublicKeyToken=null")

**Comment by dgosbell** [comment]
Thanks @edhans - this does happen on my home machine but not on my work laptop. So I've been able to use my home machine to isolate the root cause. I have a preview build on our build server with the fix here https://ci.appveyor.com/project/DarrenGosbell/daxstudio/builds/39747374/artifacts you are welcome to try this if you like. I'm going to do a bit more testing on this then I'm planning to push this out as a 2.16.1 release with a couple of other bug fixes in the next day or so.

**Comment by OLTrustNo1** [comment]
Seems to be fixed with 2.16.1 👍
