### ISSUE TITLE
DAX Snippets

### ISSUE THREAD

**Issue by darlove** [DaxStudio/DaxStudio#667]
Hi.

Would it be possible (or has this been considered at all?) to create something similar to code snippets that could be added with a keyboard shortcut in the editor? Often I need to demonstrate code or create a POC (right before people's eyes) and having snippets to do the tedious work for me (like, say, setting up DATATEBLE's and relevant standard measures) would be tremendously useful.

Thanks.

**Comment by dgosbell** [comment]
This has been raised before in #447 so I'm going to close this issue so that we can keep all of the discussion around the snippets idea in the one place. So feel free to add some input to that idea. 

I would be interested in seeing 5-6 specific examples of the sort of snippets that you would want to use in a feature like this. Because DAX is so context sensitive and contains references to specific tables, columns and measures I'm struggling to see how a feature like this could be used across different data models in DAX Studio. The examples of setting up date tables and standard measures would seem to fit better with a tool for editing the data model like Tabular Editor
