### ISSUE TITLE
DaxStudio_2_16_1 Does Not Register To External Tools

### ISSUE THREAD

**Issue by winstonsnyder** [DaxStudio/DaxStudio#687]
**Describe the bug**
I ran DaxStudio_2_16_1_setup.exe. I accepted all defaults. It did not register as an external tool. 

I previously had use Business Ops from powerbi.tips. I closed Power BI Desktop, uninstalled Business Ops and deleted everything from C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop\External Tools\

Before running DaxStudio_2_16_1_setup.exe

Thanks,
Winston

**Comment by dgosbell** [comment]
So when you say "accepted all defaults" does that include the option to install for **All Users** ? Because Microsoft put the External Tools folder under Program Files this is the only install option that can write to that folder. (which is noted [here](https://daxstudio.org/documentation/installation/) ) And note that if you have previously installed as Current User you would have to uninstall before re-running the installer since the installer only asks whether to use All Users/Current User on a fresh install.

**Comment by winstonsnyder** [comment]
Thanks Darren,

I was missing the uninstall bit previously.
I uninstalled and reinstalled and DAX Studio is now registered with External Tools.

Thanks,
-winston

**Comment by dgosbell** [comment]
Ah yeah, the installer technology we use does that automatically. If it detects that the app is already installed it runs in an "upgrade" mode.
