### ISSUE TITLE
Cannot connect to Power BI Premium per User

### ISSUE THREAD

**Issue by fmms** [DaxStudio/DaxStudio#699]
**Describe the bug**
I try to connect to my Power BI premium per user workspace with the XMLA endpoint:
![image](https://user-images.githubusercontent.com/908734/129630017-3bc699c5-3050-4552-8d16-d4a40e9c4d59.png)

**To Reproduce**
1. File --> New --> Connect and enter there a Premium URL powerbi://api.powerbi.com/v1.0/myorg/xxx

**Expected behavior**

**Screenshots**
I get an error message:
![image](https://user-images.githubusercontent.com/908734/129629922-c58e53fc-0aec-4889-8038-b94b43f1eed9.png)

with Fiddler I get:
```
{
   "code":"InternalError",
   "subCode":0,
   "message":"Internal error ApiException.Bad Request",
   "timeStamp":"2021-08-16T21:10:28.40923Z",
   "httpStatusCode":400,
   "hresult":-2147467259,
   "details":[
      {
         "code":"RootActivityId",
         "message":"d63c60e7-d106-4b5e-aa68-8e072af88422"
      },
      {
         "code":"Param1",
         "message":"Bad Request"
      }
   ]
}
```

What can I do to connect DAX Studio to my Premium per user workspace...?

**Additional context**

**Comment by dgosbell** [comment]
Thanks for reporting this, but unfortunately I cannot replicate this issue using DAX Studio 2.16.2 I am able to connect to a PPU workspace without error.

What version of DAX Studio are you using? I update the client libraries each time I do a release so if you are using an older version that could be the issue. I don't actually build the api request manually - I just pass the xmla endpoint to the Microsoft client libraries and they construct the appropriate low level api request.

Have you tried connecting to the XMLA endpoint with any other tools? (eg. Excel, SSMS)

Have you tried other workspaces? Is the issue just with this one workspace or does it happen on multiple workspaces

**Comment by fmms** [comment]
Hi @dgosbell ,

i am using 2.16.2 as well.

Unfortunately, neither SSMS nor Tabular Editor ( https://github.com/TabularEditor/TabularEditor/issues/901 ) can connect.

I have tried with several workspaces, none works.

**Comment by dgosbell** [comment]
Have you seen this post? https://community.powerbi.com/t5/Issues/Error-connecting-to-XMLA-endpoint/idi-p/656594 It sounds similar to your issue. Apparently you need to have both the **Analyze in Excel** and **XMLA Endpoint** features enabled in your tenant for the XMLA Endpoint to work. Can you check if you have both these settings enabled?

**Comment by fmms** [comment]
@dgosbell thanks for your support.

I have worked with our tenant admins. It is the following checkbox which must be flipped:
![image](https://user-images.githubusercontent.com/908734/129799943-81abc99a-cd9f-4fad-bc04-bb27b5f3f9da.png)

https://www.mmertens.eu/2021/01/configuration-of-power-bi-premium-per-user/


Afterwards it works great. I believe a better error message with possible reasons in Dax Studio would be nice. Though even better if Microsoft would respond with something more meaningful than `Internal error ApiException.Bad Request`...
.

**Comment by dgosbell** [comment]
> Afterwards it works great. I believe a better error message with possible reasons in Dax Studio would be nice.

I have not come across this before since I have the XMLA endpoint enabled on both me PPU and Premium Capacities. However I've tested with both **Read Only** and **Read Write** and they both work for me. I only get the "Bad Request" error when this setting is set of **Off**. This would suggest that maybe there was an issue enabling this in your tenant and toggling the setting to something else has forced it to be reset.

So I'll keep this issue open and look at adding some extra information when we get a "Bad Request" error when attempting to connect to an XMLA endpoint, but I'll probably keep the error text from Microsoft as well since the error is very generic and I don't know if there could be potentially be other things that trigger this.


> Though even better if Microsoft would respond with something more meaningful than Internal error ApiException.Bad Request...

I agree, I know they don't like to give too much information in error messages that potential attackers might exploit, but this seems ridiculously minimal.
