### ISSUE TITLE
Cannot connect to Power BI report with Live Connection

### ISSUE THREAD

**Issue by racheldherring** [DaxStudio/DaxStudio#700]
**Describe the bug**
I have tried opening a report that connects to the main model through live connection. The connection is an import from SSAS. 
I go to External tools in Power BI and open Dax Through then . Next, two errors come up: 
![Daxerror](https://user-images.githubusercontent.com/89266293/130258385-126e4684-c79f-4f78-81fd-abe0c62b2e29.jpg)

This does not happen while I am connected to the file with the model, only files that are using the live connection. 

Any help is much appreciated!

**Comment by dgosbell** [comment]
Can you hold down the SHIFT key while launching DAX Studio from the External Tools ribbon to enable the [diagnostic logging](https://daxstudio.org/documentation/troubleshooting/logging-settings/) (you will see a popup message telling you that the diagnostic logging has been enabled) then after you get the error close down DAX Studio and then upload the log file that gets generated to this issue? I use live connect reports all the time and I have not seen this issue.

I think I fixed the second error message in the last few days, that is just a cascading error from the first one so in the next release this should just output the first error. However a 401 error is not a standard SSAS error - it is a HTTP error code.  I'm not sure I understand how you have this configured.

Is it   `Report  ---(Live Connect)--->  SSAS`
or is it  `Report  ---(Live Connect)--->  Report  ---(Import)---> SSAS`

If it is the second option is the report deployed to a premium workspace with the XMLA endpoint enabled? If not that could be your issue since Microsoft does not allow external tools to connect to models hosted in a Pro Workspace.

**Comment by dgosbell** [comment]
Closing due to lack of response. If you have more information to add feel free to re-open this or raise a new issue
