### ISSUE TITLE
Keyword RETURN is not acknowledged by intellisence

### ISSUE THREAD

**Issue by jm98** [DaxStudio/DaxStudio#77]
The use of variables is strongly recommended.  However it is a pain that when creating these in DAX Studio, intellisence persists on changing the keyword "RETURN" followed by [Return] key to "WEEKDAY(".  The only ways around this is to either press [ESC] to cancel the intellisence replacement or put a [Space] after the keyword.

**Comment by dgosbell** [comment]
Yes, we have a hard coded list of keywords and I noticed yesterday that both VAR and RETURN were missing off this list. So this will be fixed in the next release. I also need to figure out how to exclude the parameter list from the matching process in the intellisense (this is why WEEKDAY is matching as it has a parameter called "ReturnType")

**Comment by dgosbell** [comment]
Fixed in 2.8.0
