### ISSUE TITLE
Analyzing Azure Analysis Services Request using DAX Studio

### ISSUE THREAD

**Issue by adamsummers1** [DaxStudio/DaxStudio#79]
I can connect to Azure Analysis services and run a query, but  when I try and start server tracings when connecting to Azure Analysis Services I get the following Error: "An error occurred while dispatching a call to the UI ...

**Comment by dgosbell** [comment]
I have been able to reproduce this issue, but not consistently. Sometimes everything works fine 3-4 times in a row before I see this error. And it appears that when this happens for me that the underlying error is a problem with the connection dropping. I have also found that sometimes stopping and starting the trace fixes this issue, so that might be one temporary work around you could try in the short term.

When we start one of the traces it takes a second or two for the trace to start capturing events. So we actually send through some empty batch commands and wait until the trace engine captures one of them before we report the Trace as started. It appears to be these empty batch commands that are occasionally failing so we might experiment with adding some retry logic.

**Comment by jm98** [comment]
I often get either that error or "Timeout exceeded attempting to Start Trace".
The only fix that works for me is to restart the SSAS service, which I can get away with on a development box

**Comment by adamsummers1** [comment]
My problem is because it's azure analysis services, I can't restart....

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dgosbell** [comment]
closing due to lack of response. Please feel free to open a new issue if this is still a problem under v2.8.1 or later
