### ISSUE TITLE
Issues with installing DAX studio into my external tools tab in PowerBI

### ISSUE THREAD

**Issue by KARE2022** [DaxStudio/DaxStudio#803]
Hello

I am unable to add DAX studio as part of my external tool within my PowerBI desktop, I have installed the latest version of DAX studio and expected it to synch with my powerbi desktop but to no avail

Please can you kindly advise how i can make DAX studio part of my external tools like the picture below

Thank you so much for your kind assistance

![ExternalTools](https://user-images.githubusercontent.com/99823820/154309591-e06014c9-b32e-4924-8600-becd23b9197f.png)

**Comment by dgosbell** [comment]
How did you install DAX Studio? You need to run the installer using the default **All Users** option if you want to get the External Tools integration. You can see a matrix [here](https://daxstudio.org/documentation/installation/) of the different features that are available in the different installation options.

This is because Microsoft secured the External Tools feature so that it requires an administrative rights install to register a new tool.

**Comment by KARE2022** [comment]
Thank you so much, it has worked,

I uninstalled and re-installed selecting all users

Andrew
