### ISSUE TITLE
Feature Request: Connect to Dataset in Power BI Service

### ISSUE THREAD

**Issue by smearp** [DaxStudio/DaxStudio#81]
It would be great to be able to connect to a dataset hosted in the Power BI service, similar to how Excel does the "Analyze in Excel" feature, or Power BI Desktop can access Power BI Datasets.  This would allow me to analyze the data model/performance/etc without needing to have the PBIX hosted locally.

**Comment by dgosbell** [comment]
We would like to offer this functionality too. Unfortunately at the moment Microsoft does not support this via the ADOMD.NET provider (which is what DAX Studio uses) They currently only support this through their OLEDB provider (which you can't use from .Net code). We have talked to the dev team about this and they would like to add support to their provider for this scenario at some point in the future, but I don't believe there is any time frame set for this at the moment.

**Comment by JJDE** [comment]
yes, to be able to analyse query performance for reports with live connection to a pbi.com-hosted datamodel would REALLY great! 
Has someone created a performance comparison regarding Report+Datamodel in one PBIX vs. Report connecting to a datamodel hosted in PBI-Service? I thought first it's a good idea to separate reports from dataset but now experiencing  very poor performance of the reports.. not sure yet if pbi-premium would help (because of dedicated capacity) or the "root" is the separation (longer query time because report needs to "remote" connect to the datamodel?!) Anyone with insights on that?

**Comment by dgosbell** [comment]
This is out of our hands at the moment. I'm keeping this issue open at the moment because Microsoft is looking to add support for connecting to data sets on PowerBI.com, but initially at least this will be only be available on **premium** workspaces so it's not really going to help in your scenario @JJDE . I don't think the separation of model and reports should cause performance issues. My understanding was that on powerbi.com the dataset hosting, dashboards and report rendering are done on different sets servers anyway.

**Comment by dgosbell** [comment]
As of version 2.8.0 DAX Studio now supports connecting to the PowerBI.com XMLA endpoint on Premium workspaces. Microsoft is current has this feature in a preview release, so you can test it if you have access to that or wait until this feature goes live.
