### ISSUE TITLE
Handle the dual queries generated by visuals using the Field Parameter feature

### ISSUE THREAD

**Issue by edhans** [DaxStudio/DaxStudio#854]
The new Field Parameter feature generates 2 queries with two DEFINE operations, and several of the variable names between the two are identical, like __DS0FilterTable and __DS0Core. While you can comment out one and run the other, then switch, you cannot run them at the same time without manually renaming the variables in the 2nd query. That means you cannot easily run benchmarks.

I don't know what the solution is. Perhaps when a second DEFINE is encountered, handle that as if it were in a separate window and just return two query results in the output pane. 

[Additional info and a screenshot here](https://twitter.com/ehansalytics/status/1527660357568942080).

**Comment by marcosqlbi** [comment]
This is a complex problem.
DAX supports executing multiple EVALUATE statements in the same request.
However, with the new Fields Parameters the visual sends two different statements - one for each query - to the engine. Indeed, if you enable All Queries, you will see that there are two different requests with a single query in each one, instead of one request with two queries.
We should be careful in considering what to do: for example, the evaluation of the performance and the query plan is based on the assumption that you analyze a single request. The right thing to do is to execute two queries and perform two analyses. We have neither the infrastructure nor the user interface to support that. Creating a second window with a second connection would raise another series of problems and would be very slow.
The two queries are sent in inverted order: the second query is the first one to be executed.
Because the first query executed (the second in the script) is just retrieving the list of columns, I would focus only on the second query executed (the first one in the script) and ignore the other. This means that we could introduce a setting to "ignore" the DAX code from the second DEFINE in the code. The easiest way would be to remove the code from the PASTE operation similarly to what we do for DirectQuery, which has a similar issue.
What do you think about that?

**Comment by dgosbell** [comment]
I was about to say the same thing as Marco. I don't see a lot of value in benchmarking the "second" query. I think it is only there to get the label for the axis on your visual. The main point of the benchmarking is to test measure performance and this second query contains no measures, so there is not a lot you can do to change the performance of that query. 

I think possibly trimming out the second query during the paste operation might be an option (as long as MS do not change the order of the queries. We could also bench mark the first query by ignoring anything after the second `// DAX Query` comment.

You can also just select the lines for the query you want to benchmark and DAX Studio will just run the selected text.

**Comment by edhans** [comment]
Thanks both. @dgosbell I agree with your simplistic approach of just trimming out the 2nd query, or commenting it out. Something so the average user doesn't get tripped up when trying to analyze it.

**Comment by dgosbell** [comment]
In v3 I've extended the "Multiple Queries Detected" feature so that it will now offer to remove the second DAX query for field parameters.
