### ISSUE TITLE
Issue with packaging Dax Studio 2.7.4 for distribution

### ISSUE THREAD

**Issue by falciond** [DaxStudio/DaxStudio#88]
If we run the install manually, it runs fine. If we attempt to deploy using SCCM, it runs the package using "system" account, and it fails because it always tries to download and install 2 pre-requirements ("SQL Server 2017 ADOMD.NET" & "SQL Server 2017 Analysis Management Objects") even if we have already installed them beforehand. Within the downloaded EXE, there seems to be a script which checks for these pre-reqs but when we deploy using "System" account for some reason it does not detect that the prerequisites are already installed and prompts to download and install them.

**Comment by dgosbell** [comment]
That is strange as the installer should just be checking if the dependencies are installed in the Global Assembly Cache on the local machine. But there is a work around for the current version and a better fix coming in the next version.

**Current Version:** if you can add a parameter when you call the installer exe you can add /skipdependencies=true and this will bypass the parts of the installer that checks for and downloads the dependencies

**vNext:** Microsoft has now released these 2 dependencies as Nuget packages which means that we can bundle the latest versions of these with DAX Studio rather than having to download and shell out to secondary installers

**Comment by dgosbell** [comment]
v2.8.0 has just been release which on has an external dependency on .Net 4.7.1 (and you can skip the checks for that by running setup from a command line with the `/skipdependencies=true` option
