### ISSUE TITLE
Improvements to Drop-Down Box

### ISSUE THREAD

**Issue by daryl-lynch-bzy** [DaxStudio/DaxStudio#930]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated with the Intellisence drop-down menu for 2 reasons.

1. The box should be wide enough to show all DAX functions name characters.  In the example below, "MONTH", "QUARTER", "YEAR" are always cut off, so it would make sense for the box to be a little wider to fit these.
2.  I don't like the way the last item of the list is partially or entirely covered by the Scroll Bars.

![image](https://user-images.githubusercontent.com/76914701/188934856-18558d98-e2ab-4fdc-ae27-226017e29639.png)

**Describe the solution you'd like**
Please make the drop-down box wide enough to show all characters from DAX functions.  I believe "CLOSINGBALANCEQUARTER" and "OPENBALANCEQUARTER" are the longest names.

Please make the "left-right" scroll bar appear after the last visible item or the 10th item, and the "up-down" scroll bar appear after the longer DAX Function names.

**Comment by dgosbell** [comment]
Thanks for logging this. I'm not directly controlling the code completion window, it's a feature provided by the edit control. But I have figured out a way to override the width and make the default width wider. This also fixes your second point since it prevents the horizontal scroll bar from appearing.

I cannot directly control where the horizontal scrollbar appears, but it needs to draw somewhere inside the dropdown and I don't think I can re-size the dropdown on the fly. I'm hoping that now that I've figured out a way to make it start up a lot wider that the horizontal scrollbar should rarely be needed anyway.

**Comment by daryl-lynch-bzy** [comment]
Thanks Darren (@dgosbell).  I guess it depends on the length of measure and dimension names as to how many will appear on the list, so it doesn't help when the last is covered.  However making the panel as wide as the DAX function will give more space for these longer name.

**Comment by dgosbell** [comment]
There is also an existing setting to increase the width of the dropdown, but I've increased the base size for the next release so that hopefully this will not be needed most of the time.

![image](https://user-images.githubusercontent.com/8241830/189803251-e9188101-fea2-461c-a32e-e64fd8629a61.png)
