### ISSUE TITLE
Date format in the file output

### ISSUE THREAD

**Issue by darekjara** [DaxStudio/DaxStudio#96]
Hello, I have a issue with date format of values in date column. In the source file in PBI Desktop the date format of column is "Date" e.g. 1.1.2018, in the Results pane of DAX Studio the same, or like this 1.1.2018 0:00:00 when connecting the Excel file, but in the file output (DAXStudio-Run-Output File) is the date in this format
2018-01-01 00:00:00.000
Is there a way to keep the source formatting or change the output format? Changing the "Locale option" has no effect...
Thank you

**Comment by dgosbell** [comment]
Formatting the results of ad-hoc DAX queries is actually quite tricky. The reason is due to the fact that the formatting is not done by the model. A DAX query always returns raw unformatted data and it's up to the client tool to apply the formatting. 

In the case of a tool like Power BI it's relatively simple as a given Power BI visual knows which exactly columns and measures are used in a given visual. But in the case of DAX Studio where the query is a user entered block of text we don't have any metadata to go off. We just have a column name and a data type in the result set, but column names are not necessarily unique within the model (you could have mulitple columns called "Date" in your model)

When you are displaying the results in the grid we use the current culture of the computer to format the dates. But in the case of exporting to a file we figured that the most common use of such a file would be to import the data into another program possible on a different computer. So we chose to use an ISO standard date format which should be imported correctly regardless of the culture settings of the system importing the file.

For example if you exported the date of April 3, 2018 on a US system (using mm/dd/yyyy) it would display as 4/3/2018 but if you then import that on a system with UK or AUS settings (dd/mm/yyyy) the same date would come in as March 4, 2018. Using the ISO 8601 date format of yyyy-mm-dd should avoid this sort of issue.

If you really need a specific formatted date you could either add a string column to your date table with the format you require. Or you could do this explicit formatting as part of your query 

eg.

```
DEFINE
    MEASURE 'Date'[FormattedDate] =
        FORMAT ( VALUES ( 'Date'[Date] ), "d MMM YYYY" )
EVALUATE
SELECTCOLUMNS ( VALUES ( 'date'[date] ), "FormattedDate", [FormattedDate] )
```

We could possibly fix this in future if we had a full DAX parser capable of mapping the text of an ad-hoc DAX query to specific objects in your data model. But this is quite a complex undertaking. We would like to add something like this in the future as it would open up a number of other possibilities but it's so complex that we don't currently know when/if it would be possible to implement this.

**Comment by darekjara** [comment]
Thank you for your quick and detailed answer. I tried to use FORMAT, but without success and the input and output of the query was quite confusing for me. Now I understand it better and both solutions (string column, FORMAT column) work well for me. 
I appreciate your time for explaining the context of the issue.
