### ISSUE TITLE
After insatlling dax studio it actulally does not start and says dax studio not responding

### ISSUE THREAD

**Issue by shilpibh** [DaxStudio/DaxStudio#97]
After insatlling dax studio it actulally does not start and says dax studio not responding. Attched are the log files
[daxcheckerlogs.txt](https://github.com/DaxStudio/DaxStudio/files/2357063/daxcheckerlogs.txt)

**Comment by dgosbell** [comment]
We've never seen or heard of this happening before so we are going to need some more information.

Do you see the start up splash screen logo? 
Where are you seeing the "not responding" message?
Does the User Interface load at all or are you seeing the not responding status in task manager?
Are you trying to run DAX Studio standalone or from the Excel addin?

The DaxStudioChecker logs are really only used if the app does not fire up at all due to missing dependencies, but it does not look like you have any issues there.
, 
Can you try activating the debug logging using the steps outlined [here](http://daxstudio.org/documentation/troubleshooting/logging-settings/) and see if that produces any output?

**Comment by shilpibh** [comment]
Thanks its working now.


Regards

Shilpi

________________________________
