### ISSUE TITLE
Feature: Ability to connect to Power BI reports in PB Report Server

### ISSUE THREAD

**Issue by hr-sn** [DaxStudio/DaxStudio#98]
I understand there's no ability to connect to Power BI service, but is there a way to connect to PB reports hosted on PB Report Server? Would be great for governance/documentation, etc.

**Comment by dgosbell** [comment]
So Microsoft is actually due to be adding a way that external tools such as DAX Studio can connect to models hosted in the cloud on the Power BI service in November 2018 (see [https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/power-bi-service/xmla-endpoint](https://docs.microsoft.com/en-us/business-applications-release-notes/october18/intelligence-platform/power-bi-service/xmla-endpoint) But to date I do not believe that they support any means of connecting to models hosted in Power BI Report server. 

One possible work around is to host your enterprise models in Analysis Services and just use Power BI Report Server to host the charts and visuals.
