### ISSUE TITLE
MDX Support?

### ISSUE THREAD

**Issue by cbailiss** [DaxStudio/DaxStudio#993]
Thanks for a great tool.

I notice that you can run MDX queries in it - but I am unclear whether this works in the same way as with DAX or (perhaps more likely) it is unsupported and even a stupid thing to do.

I was looking into some MDX generated by Excel against a tabular model.  A few observations:

- The MDX ran without error.
- Results appeared in DAX Studio.
- The same query ran significantly slower in DAX Studio vs. SSMS (e.g. 15 seconds in SSMS vs. 3+ mins in DAX Studio).  The result set was quite large (2364 rows and 281 columns) so perhaps the time difference is due to inefficient formatting/transport of MDX results?
- Server Timings was inconsistent - displaying seemingly randomly varying numbers of SE queries on multiple executions of the same deterministic query.  On some occasions I could clearly see large numbers of SE queries were missing.

A search of the documentation revealed no mention of MDX so I assume it isn't supported, but thought it would be worth asking the question to confirm and share the above.

**Comment by marcosqlbi** [comment]
MDX and DAX can be executed by DAX Studio because it's the Tabular engine doing the job, and the Tabular engine know both languages.
The difference in performance is potentially strange, but it's possible that the two products don't use the same technique to populate the resultset and DAX Studio results being slower doing so.
Also the Server Timings behavior seems strange, but consider that MDX caches the result of the query (like formula engine) and not only the storage engine result. The result should be identical in two executions if you clear the cache between them.
If you are able to provide a sample report to reproduce the issue, we could investigate more on it, because it is not a systematic known issue.

**Comment by cbailiss** [comment]
Hi Marco, thanks for the reply.  Unfortunately I am not able to provide a sample at the moment as I can't share the data I am working with and am very pressed for time so unable to prepare a cleansed example.  I will close this issue.
Re: MDX in DAX Studio...
I know that the Tabular engine can execute DAX and MDX - I've been working with Tabular since 2011.
My question was whether MDX is officially supported or not in DAX Studio, 
i.e. is DAX Studio tested with MDX?  Are there any known limitations or differences in DAX Studio with MDX vs. DAX?
It would be very helpful to include information in the DAX Studio documentation about this.
Thanks again for the response (and general community involvement that you do) and of course for a great tool.

**Comment by dgosbell** [comment]
I've added a new [MDX Support](https://daxstudio.org/docs/features/mdx-support/) page to the docs for this.

**Comment by cbailiss** [comment]
Thank you @dgosbell - that page is exactly what I was looking for.
